In [1]:
# ============================================================
# 0. Install Dependencies
# ============================================================

!pip -q install -U \
    datasets==2.21.0 \
    huggingface_hub==0.25.2 \
    pandas \
    pyarrow \
    tqdm \
    transformers==4.44.2 \
    accelerate==0.34.2 \
    peft==0.12.0 \
    trl==0.10.1 \
    bitsandbytes \
    sentencepiece \
    protobuf \
    sentence-transformers \
    tree-sitter \
    tree-sitter-java \
    rapidfuzz \
    evaluate \
    rouge-score \
    sacrebleu \
    nltk

print("All packages installed.")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 3.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.4/57.4 kB 2.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 3.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 527.3/527.3 kB 30.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 436.6/436.6 kB 23.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 83.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 324.4/324.4 kB 13.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.4/296.4 kB 12.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 280.1/280.1 kB 13.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 82.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 MB 14.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.3/78.3 kB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 12.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 327.1/327.1 kB 24.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 667.5/667.5 kB 33.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.0/84.0 kB 4.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 63.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 5.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 kB 5.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 59.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 177.6/177.6 kB 12.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 74.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 215.0/215.0 kB 19.3 MB/s eta 0:00:00
  Building wheel for rouge-score (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.3 which is incompatible.
google-ai-generativelanguage 0.6.15 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 7.35.1 which is incompatible.
ydf 0.15.0 requires protobuf<7.0.0,>=5.29.1, but you have protobuf 7.35.1 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.3 which is incompatible.
diffusers 0.38.0 requires huggingface-hub<2.0,>=0.34.0, but you have huggingface-hub 0.25.2 which is incompatible.
grpcio-status 1.71.2 requires protobuf<6.0dev,>=5.26.1, but you have protobuf 7.35.1 which is incompatible.
gradio 6.19.0 requires huggingface-hub<2.0,>=1.2.0, but you have huggingface-hub 0.25.2 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.3 which is incompatible.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2024.6.1 which is incompatible.
All packages installed.

In [1]:
# ============================================================
# 1. Environment Verification
# ============================================================

import platform
import sys

print("=" * 72)
print("RepoCoder Studio - Environment Verification")
print("=" * 72)

print(f"Python Version : {platform.python_version()}")
print(f"Executable     : {sys.executable}")

assert sys.version_info >= (3, 10), \
    "Python 3.10 or newer is required."

print("\nEnvironment verification successful.")

========================================================================
RepoCoder Studio - Environment Verification
========================================================================
Python Version : 3.12.13
Executable     : /usr/bin/python3

Environment verification successful.

In [2]:
# ============================================================
# 2. Mount Google Drive
# ============================================================

from google.colab import drive

drive.mount("/content/drive")

Mounted at /content/drive

In [3]:
# ============================================================
# 3. Project Initialization
# ============================================================

import sys
from pathlib import Path

PROJECT_ROOT = Path("/content/drive/MyDrive/RepoCoderStudio")

SRC_DIR = PROJECT_ROOT / "src"

assert PROJECT_ROOT.exists(), \
    f"Project folder not found:\n{PROJECT_ROOT}"

assert SRC_DIR.exists(), \
    f"Source folder not found:\n{SRC_DIR}"

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print("Project Root")
print(PROJECT_ROOT)

print("\nPython path configured successfully.")

Project Root
/content/drive/MyDrive/RepoCoderStudio

Python path configured successfully.

In [4]:
# ============================================================
# 4. Import Core Framework
# ============================================================

import importlib
import sys

#
# Clear previously loaded RepoCoder modules.
# This allows edited .py files to be re-imported without
# restarting the runtime.
#

for module_name in list(sys.modules.keys()):

    if module_name == "src" or module_name.startswith("src."):

        del sys.modules[module_name]

importlib.invalidate_caches()

#
# Core framework imports
#

from src.config import (
    CONFIG,
    print_config_summary,
)

from src.logger import (
    LOG,
    SectionPrinter,
    SummaryPrinter,
)

from src.storage import ProjectStorageManager

from src.registry import (
    DatasetRegistry,
    TaskRegistry,
    MetricRegistry,
)

print("Core framework imported successfully.")

Core framework imported successfully.

In [5]:
# ============================================================
# 5. Configuration Summary
# ============================================================

SectionPrinter.header("Configuration Summary")

print_config_summary(CONFIG)

# ============================================================
# CONFIG Structure Diagnostic
# ============================================================

print("CONFIG type:", type(CONFIG))
print("\nAvailable CONFIG attributes:\n")

for k in sorted(dir(CONFIG)):
    if not k.startswith("_"):
        print(k, "=", getattr(CONFIG, k))

====================================================================
Configuration Summary
====================================================================
========================================================================
RepoCoder Studio — Combined Stage Configuration
========================================================================
Project                 : RepoCoderStudio
Stage                   : CombinedStage
Specification Version   : 2.0
Run Mode                : demo
Google Drive Enabled    : True
Auto Resume             : True
Project Root            : /content/drive/MyDrive/RepoCoderStudio
------------------------------------------------------------------------
Primary Dataset         : XLCoST
XLCoST Dataset          : codeparrot/xlcost-text-to-code
Python Config           : Python-program-level
Java Config             : Java-program-level
CodeXGLUE Enabled       : True
Dataset Cache           : True
Alignment Strategy      : semantic+embedding
Alignment Threshold     : 0.5
Tree-sitter Java        : True
------------------------------------------------------------------------
Student Model           : Qwen/Qwen2.5-Coder-0.5B-Instruct
Max Sequence Length     : 1024
4-bit Loading           : True
------------------------------------------------------------------------
Training Enabled        : True
Auto Checkpoint Resume  : True
Final Adapter Name      : RepoCoderStudio_CombinedStage_LoRA_v1_0
Prompt Version          : prompt_contract_v2.6
========================================================================
CONFIG type: <class 'src.config.AppConfig'>

Available CONFIG attributes:

alignment = AlignmentConfig(use_embedding_alignment=True, embedding_model='sentence-transformers/all-MiniLM-L6-v2', alignment_top_k=10, confidence_threshold=0.5, structural_bonus=0.1, within_dataset_confidence=1.0)
corpus = CorpusConfig(corpus_version='combined_stage_v2.0', enable_deduplication=True, remove_exact_duplicates=True, remove_structural_duplicates=True, min_python_chars=20, min_java_chars=20, min_nl_words=4, save_candidate_corpus=True, save_duplicate_report=True, save_corpus_statistics=True)
dataset = DatasetConfig(use_xlcost=True, use_codexglue=True, xlcost_dataset_name='codeparrot/xlcost-text-to-code', xlcost_python_config='Python-program-level', xlcost_java_config='Java-program-level', codexglue_dataset_name='google/code_x_glue_ct_code_to_text', codexglue_fallback_dataset_name='code_search_net', codexglue_python_config='python', codexglue_java_config='java', dataset_cache_enabled=True, dataset_cache_dir='datasets/cache', demo_train_limit=300, demo_validation_limit=60, demo_test_limit=60, full_train_limit=None, full_validation_limit=None, full_test_limit=None, expected_splits=('train', 'validation', 'test'))
evaluation = EvaluationConfig(enable_evaluation=True, demo_eval_examples_per_task=10, full_eval_examples_per_task=100, save_prediction_logs=True, save_metric_rows=True, save_summary_reports=True, regression_threshold=-0.02)
experiment = ExperimentConfig(experiment_version='experiment_v2.6', prompt_version='prompt_contract_v2.6', task_contract_version='task_contract_v2.6', task_builder_version='task_builder_v2.3', task_registry_version='task_registry_v2.0', metric_registry_version='metric_registry_v2.0', training_manifest_version='training_manifest_v2.6')
logging = LoggingConfig(log_to_console=True, log_to_file=True, log_level='INFO', log_filename='repocoder_combined_stage.log')
models = ModelConfig(student_model_name='Qwen/Qwen2.5-Coder-0.5B-Instruct', teacher_model_name='Qwen/Qwen2.5-Coder-0.5B-Instruct', use_4bit=True, use_flash_attention=False, max_seq_length=1024, max_new_tokens=384)
project = ProjectConfig(name='RepoCoderStudio', stage='CombinedStage', specification_version='2.0')
runtime = RuntimeConfig(run_mode='demo', use_google_drive=True, auto_resume=True, overwrite_existing=False, random_seed=42)
storage = StorageConfig(drive_mount_point='/content/drive', drive_project_root='/content/drive/MyDrive/RepoCoderStudio', notebooks_dir='notebooks', src_dir='src', configs_dir='configs', datasets_dir='datasets', outputs_dir='outputs', candidate_corpus_dir='outputs/candidate_corpus', approved_corpus_dir='outputs/approved_corpus', rejected_corpus_dir='outputs/rejected_corpus', trusted_tests_dir='outputs/trusted_tests', task_datasets_dir='outputs/task_datasets', checkpoints_dir='outputs/checkpoints', adapters_dir='outputs/adapters', evaluation_dir='outputs/evaluation', reports_dir='outputs/reports', logs_dir='outputs/logs', manifests_dir='outputs/manifests')
to_dict = <bound method AppConfig.to_dict of AppConfig(project=ProjectConfig(name='RepoCoderStudio', stage='CombinedStage', specification_version='2.0'), experiment=ExperimentConfig(experiment_version='experiment_v2.6', prompt_version='prompt_contract_v2.6', task_contract_version='task_contract_v2.6', task_builder_version='task_builder_v2.3', task_registry_version='task_registry_v2.0', metric_registry_version='metric_registry_v2.0', training_manifest_version='training_manifest_v2.6'), runtime=RuntimeConfig(run_mode='demo', use_google_drive=True, auto_resume=True, overwrite_existing=False, random_seed=42), storage=StorageConfig(drive_mount_point='/content/drive', drive_project_root='/content/drive/MyDrive/RepoCoderStudio', notebooks_dir='notebooks', src_dir='src', configs_dir='configs', datasets_dir='datasets', outputs_dir='outputs', candidate_corpus_dir='outputs/candidate_corpus', approved_corpus_dir='outputs/approved_corpus', rejected_corpus_dir='outputs/rejected_corpus', trusted_tests_dir='outputs/trusted_tests', task_datasets_dir='outputs/task_datasets', checkpoints_dir='outputs/checkpoints', adapters_dir='outputs/adapters', evaluation_dir='outputs/evaluation', reports_dir='outputs/reports', logs_dir='outputs/logs', manifests_dir='outputs/manifests'), dataset=DatasetConfig(use_xlcost=True, use_codexglue=True, xlcost_dataset_name='codeparrot/xlcost-text-to-code', xlcost_python_config='Python-program-level', xlcost_java_config='Java-program-level', codexglue_dataset_name='google/code_x_glue_ct_code_to_text', codexglue_fallback_dataset_name='code_search_net', codexglue_python_config='python', codexglue_java_config='java', dataset_cache_enabled=True, dataset_cache_dir='datasets/cache', demo_train_limit=300, demo_validation_limit=60, demo_test_limit=60, full_train_limit=None, full_validation_limit=None, full_test_limit=None, expected_splits=('train', 'validation', 'test')), corpus=CorpusConfig(corpus_version='combined_stage_v2.0', enable_deduplication=True, remove_exact_duplicates=True, remove_structural_duplicates=True, min_python_chars=20, min_java_chars=20, min_nl_words=4, save_candidate_corpus=True, save_duplicate_report=True, save_corpus_statistics=True), alignment=AlignmentConfig(use_embedding_alignment=True, embedding_model='sentence-transformers/all-MiniLM-L6-v2', alignment_top_k=10, confidence_threshold=0.5, structural_bonus=0.1, within_dataset_confidence=1.0), validation=ValidationConfig(enable_python_validation=True, enable_java_validation=True, enable_trusted_test_builder=True, enable_execution_validation=True, enable_csr_validation=True, enable_nl_validation=True, allow_execution_not_feasible=True, min_csr_similarity=0.2, max_repair_attempts_per_component=3, enable_nl_repair=True, enable_python_repair=True, enable_java_wrapper_repair=True, enable_teacher_repair=True, enable_teacher_test_generation=False, enable_teacher_completion_queue_processing=False, teacher_repair_only_generated_modalities=True, java_compile_timeout_seconds=10, python_parse_timeout_seconds=5, max_execution_tests_per_row=5, use_tree_sitter_java=True), models=ModelConfig(student_model_name='Qwen/Qwen2.5-Coder-0.5B-Instruct', teacher_model_name='Qwen/Qwen2.5-Coder-0.5B-Instruct', use_4bit=True, use_flash_attention=False, max_seq_length=1024, max_new_tokens=384), training=TrainingConfig(enable_training=True, num_train_epochs_demo=1.0, num_train_epochs_full=2.0, per_device_train_batch_size=1, gradient_accumulation_steps=8, learning_rate=0.0002, warmup_ratio=0.03, weight_decay=0.0, lora_rank=8, lora_alpha=16, lora_dropout=0.05, logging_steps=10, save_steps_demo=50, save_steps_full=100, save_total_limit=3, auto_resume_from_checkpoint=True, use_task_contract_prompts=True, demo_task_cap_per_split=10000, final_adapter_name='RepoCoderStudio_CombinedStage_LoRA_v1_0'), evaluation=EvaluationConfig(enable_evaluation=True, demo_eval_examples_per_task=10, full_eval_examples_per_task=100, save_prediction_logs=True, save_metric_rows=True, save_summary_reports=True, regression_threshold=-0.02), logging=LoggingConfig(log_to_console=True, log_to_file=True, log_level='INFO', log_filename='repocoder_combined_stage.log'))>
training = TrainingConfig(enable_training=True, num_train_epochs_demo=1.0, num_train_epochs_full=2.0, per_device_train_batch_size=1, gradient_accumulation_steps=8, learning_rate=0.0002, warmup_ratio=0.03, weight_decay=0.0, lora_rank=8, lora_alpha=16, lora_dropout=0.05, logging_steps=10, save_steps_demo=50, save_steps_full=100, save_total_limit=3, auto_resume_from_checkpoint=True, use_task_contract_prompts=True, demo_task_cap_per_split=10000, final_adapter_name='RepoCoderStudio_CombinedStage_LoRA_v1_0')
validate = <bound method AppConfig.validate of AppConfig(project=ProjectConfig(name='RepoCoderStudio', stage='CombinedStage', specification_version='2.0'), experiment=ExperimentConfig(experiment_version='experiment_v2.6', prompt_version='prompt_contract_v2.6', task_contract_version='task_contract_v2.6', task_builder_version='task_builder_v2.3', task_registry_version='task_registry_v2.0', metric_registry_version='metric_registry_v2.0', training_manifest_version='training_manifest_v2.6'), runtime=RuntimeConfig(run_mode='demo', use_google_drive=True, auto_resume=True, overwrite_existing=False, random_seed=42), storage=StorageConfig(drive_mount_point='/content/drive', drive_project_root='/content/drive/MyDrive/RepoCoderStudio', notebooks_dir='notebooks', src_dir='src', configs_dir='configs', datasets_dir='datasets', outputs_dir='outputs', candidate_corpus_dir='outputs/candidate_corpus', approved_corpus_dir='outputs/approved_corpus', rejected_corpus_dir='outputs/rejected_corpus', trusted_tests_dir='outputs/trusted_tests', task_datasets_dir='outputs/task_datasets', checkpoints_dir='outputs/checkpoints', adapters_dir='outputs/adapters', evaluation_dir='outputs/evaluation', reports_dir='outputs/reports', logs_dir='outputs/logs', manifests_dir='outputs/manifests'), dataset=DatasetConfig(use_xlcost=True, use_codexglue=True, xlcost_dataset_name='codeparrot/xlcost-text-to-code', xlcost_python_config='Python-program-level', xlcost_java_config='Java-program-level', codexglue_dataset_name='google/code_x_glue_ct_code_to_text', codexglue_fallback_dataset_name='code_search_net', codexglue_python_config='python', codexglue_java_config='java', dataset_cache_enabled=True, dataset_cache_dir='datasets/cache', demo_train_limit=300, demo_validation_limit=60, demo_test_limit=60, full_train_limit=None, full_validation_limit=None, full_test_limit=None, expected_splits=('train', 'validation', 'test')), corpus=CorpusConfig(corpus_version='combined_stage_v2.0', enable_deduplication=True, remove_exact_duplicates=True, remove_structural_duplicates=True, min_python_chars=20, min_java_chars=20, min_nl_words=4, save_candidate_corpus=True, save_duplicate_report=True, save_corpus_statistics=True), alignment=AlignmentConfig(use_embedding_alignment=True, embedding_model='sentence-transformers/all-MiniLM-L6-v2', alignment_top_k=10, confidence_threshold=0.5, structural_bonus=0.1, within_dataset_confidence=1.0), validation=ValidationConfig(enable_python_validation=True, enable_java_validation=True, enable_trusted_test_builder=True, enable_execution_validation=True, enable_csr_validation=True, enable_nl_validation=True, allow_execution_not_feasible=True, min_csr_similarity=0.2, max_repair_attempts_per_component=3, enable_nl_repair=True, enable_python_repair=True, enable_java_wrapper_repair=True, enable_teacher_repair=True, enable_teacher_test_generation=False, enable_teacher_completion_queue_processing=False, teacher_repair_only_generated_modalities=True, java_compile_timeout_seconds=10, python_parse_timeout_seconds=5, max_execution_tests_per_row=5, use_tree_sitter_java=True), models=ModelConfig(student_model_name='Qwen/Qwen2.5-Coder-0.5B-Instruct', teacher_model_name='Qwen/Qwen2.5-Coder-0.5B-Instruct', use_4bit=True, use_flash_attention=False, max_seq_length=1024, max_new_tokens=384), training=TrainingConfig(enable_training=True, num_train_epochs_demo=1.0, num_train_epochs_full=2.0, per_device_train_batch_size=1, gradient_accumulation_steps=8, learning_rate=0.0002, warmup_ratio=0.03, weight_decay=0.0, lora_rank=8, lora_alpha=16, lora_dropout=0.05, logging_steps=10, save_steps_demo=50, save_steps_full=100, save_total_limit=3, auto_resume_from_checkpoint=True, use_task_contract_prompts=True, demo_task_cap_per_split=10000, final_adapter_name='RepoCoderStudio_CombinedStage_LoRA_v1_0'), evaluation=EvaluationConfig(enable_evaluation=True, demo_eval_examples_per_task=10, full_eval_examples_per_task=100, save_prediction_logs=True, save_metric_rows=True, save_summary_reports=True, regression_threshold=-0.02), logging=LoggingConfig(log_to_console=True, log_to_file=True, log_level='INFO', log_filename='repocoder_combined_stage.log'))>
validation = ValidationConfig(enable_python_validation=True, enable_java_validation=True, enable_trusted_test_builder=True, enable_execution_validation=True, enable_csr_validation=True, enable_nl_validation=True, allow_execution_not_feasible=True, min_csr_similarity=0.2, max_repair_attempts_per_component=3, enable_nl_repair=True, enable_python_repair=True, enable_java_wrapper_repair=True, enable_teacher_repair=True, enable_teacher_test_generation=False, enable_teacher_completion_queue_processing=False, teacher_repair_only_generated_modalities=True, java_compile_timeout_seconds=10, python_parse_timeout_seconds=5, max_execution_tests_per_row=5, use_tree_sitter_java=True)

In [6]:
# ============================================================
# 6. Initialize Project Storage
# ============================================================

storage = ProjectStorageManager(CONFIG)

storage.initialize_project()

storage.save_config_snapshot()

storage.print_project_status()

LOG.info("Project storage initialized successfully.")

====================================================================
Project Folder Initialization
====================================================================

====================================================================
Storage Initialization Summary
====================================================================
Project Root                : /content/drive/MyDrive/RepoCoderStudio
Folders Created             : 8
Folders Already Existing    : 14
====================================================================
14:24:04 | INFO     | RepoCoderStudio.Main | Saved JSON: /content/drive/MyDrive/RepoCoderStudio/outputs/manifests/config_snapshot_20260704_142404.json

====================================================================
Project Artifact Status
====================================================================
Candidate Corpus        : FOUND
Duplicate Report        : FOUND
Approved Corpus         : FOUND
Rejected Corpus         : FOUND
Task Dataset            : FOUND
Checkpoints Folder      : FOUND
Adapters Folder         : FOUND
====================================================================
14:24:05 | INFO     | RepoCoderStudio.Main | Project storage initialized successfully.

In [ ]:
# ============================================================
# 7. Registry Summary
# ============================================================

dataset_registry = DatasetRegistry()

task_registry = TaskRegistry()

metric_registry = MetricRegistry()

SectionPrinter.header("Dataset Registry")

print(dataset_registry.summary())

SectionPrinter.header("Task Registry")

for task_id, task in task_registry.all_tasks().items():

    print(task_id, ":", task)

SectionPrinter.header("Metric Registry")

print(metric_registry.summary())

====================================================================
Dataset Registry
====================================================================
{'XLCoST': {'enabled': True, 'role': 'primary', 'source': 'codeparrot/xlcost-text-to-code', 'python_config': 'Python-program-level', 'java_config': 'Java-program-level'}, 'CodeXGLUE': {'enabled': True, 'role': 'second_evidence_source', 'source': 'google/code_x_glue_ct_code_to_text', 'python_config': 'python', 'java_config': 'java'}}

====================================================================
Task Registry
====================================================================
T1 : {'source': 'Natural Language', 'target': 'Python', 'description': 'Generate Python code from natural language.'}
T2 : {'source': 'Natural Language', 'target': 'Java', 'description': 'Generate Java code from natural language.'}
T3 : {'source': 'Python', 'target': 'Java', 'description': 'Translate Python code to Java.'}
T4 : {'source': 'Java', 'target': 'Python', 'description': 'Translate Java code to Python.'}
T5 : {'source': 'Python', 'target': 'Natural Language', 'description': 'Explain Python code in natural language.'}
T6 : {'source': 'Java', 'target': 'Natural Language', 'description': 'Explain Java code in natural language.'}

====================================================================
Metric Registry
====================================================================
{'Natural Language -> Python': {'primary': ['python_parse_success'], 'secondary': ['execution_if_feasible', 'official_codebleu', 'csr_score'], 'diagnostic': ['codebleu_lite', 'failure_category']}, 'Natural Language -> Java': {'primary': ['java_compile_success'], 'secondary': ['execution_if_feasible', 'official_codebleu', 'csr_score'], 'diagnostic': ['codebleu_lite', 'failure_category']}, 'Python -> Java': {'primary': ['java_compile_success'], 'secondary': ['official_codebleu', 'csr_score'], 'diagnostic': ['codebleu_lite', 'failure_category']}, 'Java -> Python': {'primary': ['python_parse_success'], 'secondary': ['official_codebleu', 'csr_score'], 'diagnostic': ['codebleu_lite', 'failure_category']}, 'Python -> Natural Language': {'primary': ['rouge_l'], 'secondary': ['sacrebleu'], 'diagnostic': ['semantic_similarity', 'failure_category']}, 'Java -> Natural Language': {'primary': ['rouge_l'], 'secondary': ['sacrebleu'], 'diagnostic': ['semantic_similarity', 'failure_category']}}

In [ ]:
# ============================================================
# 8. Load Raw Datasets
# ============================================================

from src.dataset_loader import DatasetLoader

SectionPrinter.header("Loading Raw Datasets")

loader = DatasetLoader(CONFIG)

raw_datasets = loader.load_all()

#
# XLCoST
#

xlcost_python = raw_datasets["XLCoST"]["python"]

xlcost_java = raw_datasets["XLCoST"]["java"]

first_split = list(xlcost_python.keys())[0]

SectionPrinter.header("Dataset Summary")

print("Python Dataset")

print(xlcost_python)

print()

print("Java Dataset")

print(xlcost_java)

print()

print("First Split")

print(first_split)

print()

print("Python Columns")

print(xlcost_python[first_split].column_names)

print()

print("Java Columns")

print(xlcost_java[first_split].column_names)

print()

print("Example Python Record")

print(xlcost_python[first_split][0])

print()

print("Example Java Record")

print(xlcost_java[first_split][0])

#
# CodeXGLUE (if enabled)
#

if "CodeXGLUE" in raw_datasets:
    codexglue_python = raw_datasets["CodeXGLUE"]["python"]
    codexglue_java   = raw_datasets["CodeXGLUE"]["java"]
    if codexglue_python is not None:
      split = "train"
      sample = codexglue_python[split][0]

      print("CodeXGLUE Python Columns:", codexglue_python[split].column_names)
      print("Example NL (docstring):")
      print(sample.get("docstring", "")[:500])
      print("\nExample Code (code):")
      print(sample.get("code", "")[:500])

    if codexglue_java is not None:
        split = "train"
        sample = codexglue_java[split][0]

        print("\nCodeXGLUE Java Columns:", codexglue_java[split].column_names)
        print("Example NL (docstring):")
        print(sample.get("docstring", "")[:500])
        print("\nExample Code (code):")
        print(sample.get("code", "")[:500])
else:
    print()
    print("CodeXGLUE not loaded (use_codexglue=False).")

====================================================================
Loading Raw Datasets
====================================================================

====================================================================
Loading XLCoST
====================================================================
02:00:34 | INFO     | RepoCoderStudio.Main | [cache MISS] XLCoST not in cache — downloading from HuggingFace
02:00:34 | INFO     | RepoCoderStudio.Main | Downloading XLCoST Python config...

Downloading data:   0%|          | 0.00/3.92M [00:00<?, ?B/s]

Downloading data:   0%|          | 0.00/357k [00:00<?, ?B/s]

Downloading data:   0%|          | 0.00/200k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/9263 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/887 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/472 [00:00<?, ? examples/s]

02:00:42 | INFO     | RepoCoderStudio.Main | Downloading XLCoST Java config...

Downloading data:   0%|          | 0.00/4.44M [00:00<?, ?B/s]

Downloading data:   0%|          | 0.00/395k [00:00<?, ?B/s]

Downloading data:   0%|          | 0.00/217k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/9623 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/911 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/494 [00:00<?, ? examples/s]

02:00:45 | INFO     | RepoCoderStudio.Main | Saving XLCoST to disk cache: /content/drive/MyDrive/RepoCoderStudio/datasets/cache

Saving the dataset (0/1 shards):   0%|          | 0/9263 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/887 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/472 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/9623 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/911 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/494 [00:00<?, ? examples/s]

02:00:45 | INFO     | RepoCoderStudio.Main | XLCoST saved to cache.

====================================================================
XLCoST Load Summary  [downloaded]
====================================================================
Python Splits               : ['train', 'test', 'validation']
Java Splits                 : ['train', 'test', 'validation']
Cached                      : True
====================================================================

====================================================================
Loading CodeXGLUE
====================================================================
02:00:45 | INFO     | RepoCoderStudio.Main | [cache MISS] CodeXGLUE not in cache — downloading from HuggingFace
02:00:45 | INFO     | RepoCoderStudio.Main | Downloading CodeXGLUE Python config...

Downloading readme:   0%|          | 0.00/26.7k [00:00<?, ?B/s]

Downloading data:   0%|          | 0.00/144M [00:00<?, ?B/s]

Downloading data:   0%|          | 0.00/147M [00:00<?, ?B/s]

Downloading data:   0%|          | 0.00/16.7M [00:00<?, ?B/s]

Downloading data:   0%|          | 0.00/18.0M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/251820 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/13914 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/14918 [00:00<?, ? examples/s]

02:00:59 | INFO     | RepoCoderStudio.Main | Downloading CodeXGLUE Java config...

Downloading data:   0%|          | 0.00/141M [00:00<?, ?B/s]

Downloading data:   0%|          | 0.00/4.25M [00:00<?, ?B/s]

Downloading data:   0%|          | 0.00/9.38M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/164923 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/5183 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/10955 [00:00<?, ? examples/s]

02:01:05 | INFO     | RepoCoderStudio.Main | Saving CodeXGLUE to disk cache: /content/drive/MyDrive/RepoCoderStudio/datasets/cache

Saving the dataset (0/2 shards):   0%|          | 0/251820 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/13914 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/14918 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/164923 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/5183 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/10955 [00:00<?, ? examples/s]

02:01:14 | INFO     | RepoCoderStudio.Main | CodeXGLUE saved to cache.

====================================================================
CodeXGLUE Load Summary  [downloaded]
====================================================================
Python Splits               : ['train', 'validation', 'test']
Java Splits                 : ['train', 'validation', 'test']
Cached                      : True
====================================================================

====================================================================
Dataset Summary
====================================================================
Python Dataset
DatasetDict({
    train: Dataset({
        features: ['text', 'code'],
        num_rows: 9263
    })
    test: Dataset({
        features: ['text', 'code'],
        num_rows: 887
    })
    validation: Dataset({
        features: ['text', 'code'],
        num_rows: 472
    })
})

Java Dataset
DatasetDict({
    train: Dataset({
        features: ['text', 'code'],
        num_rows: 9623
    })
    test: Dataset({
        features: ['text', 'code'],
        num_rows: 911
    })
    validation: Dataset({
        features: ['text', 'code'],
        num_rows: 494
    })
})

First Split
train

Python Columns
['text', 'code']

Java Columns
['text', 'code']

Example Python Record
{'text': 'Maximum Prefix Sum possible by merging two given arrays | Python3 implementation of the above approach ; Stores the maximum prefix sum of the array A [ ] ; Traverse the array A [ ] ; Stores the maximum prefix sum of the array B [ ] ; Traverse the array B [ ] ; Driver code', 'code': 'def maxPresum ( a , b ) : NEW_LINE INDENT X = max ( a [ 0 ] , 0 ) NEW_LINE for i in range ( 1 , len ( a ) ) : NEW_LINE INDENT a [ i ] += a [ i - 1 ] NEW_LINE X = max ( X , a [ i ] ) NEW_LINE DEDENT Y = max ( b [ 0 ] , 0 ) NEW_LINE for i in range ( 1 , len ( b ) ) : NEW_LINE INDENT b [ i ] += b [ i - 1 ] NEW_LINE Y = max ( Y , b [ i ] ) NEW_LINE DEDENT return X + Y NEW_LINE DEDENT A = [ 2 , - 1 , 4 , - 5 ] NEW_LINE B = [ 4 , - 3 , 12 , 4 , - 3 ] NEW_LINE print ( maxPresum ( A , B ) ) NEW_LINE'}

Example Java Record
{'text': 'Maximum Prefix Sum possible by merging two given arrays | Java Program to implement the above approach ; Stores the maximum prefix sum of the array A [ ] ; Traverse the array A [ ] ; Stores the maximum prefix sum of the array B [ ] ; Traverse the array B [ ] ; Driver code', 'code': 'import java . util . * ; class GFG { static int maxPresum ( int [ ] a , int [ ] b ) { int X = Math . max ( a [ 0 ] , 0 ) ; for ( int i = 1 ; i < a . length ; i ++ ) { a [ i ] += a [ i - 1 ] ; X = Math . max ( X , a [ i ] ) ; } int Y = Math . max ( b [ 0 ] , 0 ) ; for ( int i = 1 ; i < b . length ; i ++ ) { b [ i ] += b [ i - 1 ] ; Y = Math . max ( Y , b [ i ] ) ; } return X + Y ; } public static void main ( String [ ] args ) { int [ ] A = { 2 , - 1 , 4 , - 5 } ; int [ ] B = { 4 , - 3 , 12 , 4 , - 3 } ; System . out . print ( maxPresum ( A , B ) ) ; } }'}
CodeXGLUE Python Columns: ['id', 'repo', 'path', 'func_name', 'original_string', 'language', 'code', 'code_tokens', 'docstring', 'docstring_tokens', 'sha', 'url']
Example NL (docstring):
Set the text for this element.

        Arguments:
            text (str): The text
            cls (str): The class of the text, defaults to ``current`` (leave this unless you know what you are doing). There may be only one text content element of each class associated with the element.

Example Code (code):
def settext(self, text, cls='current'):
        """Set the text for this element.

        Arguments:
            text (str): The text
            cls (str): The class of the text, defaults to ``current`` (leave this unless you know what you are doing). There may be only one text content element of each class associated with the element.
        """
        self.replace(TextContent, value=text, cls=cls)

CodeXGLUE Java Columns: ['id', 'repo', 'path', 'func_name', 'original_string', 'language', 'code', 'code_tokens', 'docstring', 'docstring_tokens', 'sha', 'url']
Example NL (docstring):
Compare the supplied plaintext password to a hashed password.

@param   passwd  Plaintext password.
@param   hashed  scrypt hashed password.

@return true if passwd matches hashed value.

Example Code (code):
public static boolean check(String passwd, String hashed) {
        try {
            String[] parts = hashed.split("\\$");

            if (parts.length != 5 || !parts[1].equals("s0")) {
                throw new IllegalArgumentException("Invalid hashed value");
            }

            long params = Long.parseLong(parts[2], 16);
            byte[] salt = decode(parts[3].toCharArray());
            byte[] derived0 = decode(parts[4].toCharArray());

            int N = (int) Math.pow(2, params

In [ ]:
# ============================================================
# 9. Build Candidate Corpus  [v2 — Semantic Alignment]
# ============================================================

import sys
import importlib
from pathlib import Path

# ------------------------------------------------------------
# Reload source modules after file replacement.
# This prevents Colab from using stale imported versions.
# ------------------------------------------------------------

for module_name in list(sys.modules.keys()):
    if module_name == "src" or module_name.startswith("src."):
        del sys.modules[module_name]

importlib.invalidate_caches()

from src.config import CONFIG
from src.dataset_loader import DatasetLoader
from src.corpus_builder import CandidateCorpusBuilder
from src.storage import ProjectStorageManager
from src.logger import SectionPrinter, SummaryPrinter

SectionPrinter.header("Candidate Corpus Construction  [v2.2 — Semantic Alignment]")

storage = ProjectStorageManager(CONFIG)

# ------------------------------------------------------------
# Remove stale corpus artifacts before rebuilding.
# This is intentional for v2.2 because alignment logic changed.
# ------------------------------------------------------------

stale_artifacts = [
    storage.candidate_corpus_path(),
    storage.duplicate_report_path(),
    storage.approved_corpus_path(),
    storage.rejected_corpus_path(),
    f"{CONFIG.storage.reports_dir}/validation_report.jsonl",
    "outputs/reports/alignment_analytics.jsonl",
    "outputs/teacher_queue/teacher_completion_queue.jsonl",
]

for rel_path in stale_artifacts:
    path = storage.path(rel_path)
    if path.exists():
        path.unlink()
        print(f"Deleted stale artifact: {path}")

# ------------------------------------------------------------
# Load cached datasets or download missing datasets.
# ------------------------------------------------------------

loader = DatasetLoader(CONFIG)
raw_datasets = loader.load_all()

# ------------------------------------------------------------
# Build Candidate Corpus using semantic alignment.
# ------------------------------------------------------------

candidate_builder = CandidateCorpusBuilder(CONFIG)
candidate_rows = candidate_builder.build(raw_datasets)

print(f"\nCandidate rows: {len(candidate_rows)}")

if candidate_rows:
    first = candidate_rows[0]
    print("\nAlignment strategy distribution:")
    strategy_counts = {}
    for row in candidate_rows:
        strategy = row.metadata.get("alignment_strategy", "unknown")
        strategy_counts[strategy] = strategy_counts.get(strategy, 0) + 1
    for strategy, count in sorted(strategy_counts.items()):
        print(f"  {strategy}: {count}")

    confidences = [
        float(row.metadata.get("alignment_confidence", 0.0))
        for row in candidate_rows
    ]
    print(
        "\nAlignment confidence: "
        f"min={min(confidences):.3f}  "
        f"mean={sum(confidences)/len(confidences):.3f}  "
        f"max={max(confidences):.3f}"
    )

    print("\nSample normalized Python:")
    print(first.python_code[:1200])

    print("\nSample normalized Java:")
    print(first.java_code[:1200])

SummaryPrinter.print_summary(
    "Candidate Corpus Notebook Summary  [v2.2]",
    {
        "Candidate Rows": len(candidate_rows),
        "Alignment Strategy": candidate_rows[0].metadata.get("alignment_strategy") if candidate_rows else "NONE",
        "First Dataset": candidate_rows[0].dataset if candidate_rows else "NONE",
        "First Split": candidate_rows[0].split if candidate_rows else "NONE",
    },
)

====================================================================
Candidate Corpus Construction  [v2.2 — Semantic Alignment]
====================================================================
Deleted stale artifact: /content/drive/MyDrive/RepoCoderStudio/outputs/candidate_corpus/candidate_corpus.jsonl
Deleted stale artifact: /content/drive/MyDrive/RepoCoderStudio/outputs/candidate_corpus/duplicate_report.jsonl
Deleted stale artifact: /content/drive/MyDrive/RepoCoderStudio/outputs/approved_corpus/approved_corpus.jsonl
Deleted stale artifact: /content/drive/MyDrive/RepoCoderStudio/outputs/rejected_corpus/rejected_corpus.jsonl
Deleted stale artifact: /content/drive/MyDrive/RepoCoderStudio/outputs/reports/validation_report.jsonl

====================================================================
Loading XLCoST
====================================================================
02:01:24 | INFO     | RepoCoderStudio.Main | [cache HIT] Loading XLCoST from disk: /content/drive/MyDrive/RepoCoderStudio/datasets/cache

====================================================================
XLCoST Load Summary  [from cache]
====================================================================
Python Splits               : ['train', 'test', 'validation']
Java Splits                 : ['train', 'test', 'validation']
Cache Path                  : /content/drive/MyDrive/RepoCoderStudio/datasets/cache
====================================================================

====================================================================
Loading CodeXGLUE
====================================================================
02:01:24 | INFO     | RepoCoderStudio.Main | [cache HIT] Loading CodeXGLUE from disk: /content/drive/MyDrive/RepoCoderStudio/datasets/cache

====================================================================
CodeXGLUE Load Summary  [from cache]
====================================================================
Python Splits               : ['train', 'validation', 'test']
Java Splits                 : ['train', 'validation', 'test']
Cache Path                  : /content/drive/MyDrive/RepoCoderStudio/datasets/cache
====================================================================

====================================================================
Candidate Corpus Builder  [v2 — Semantic Alignment]
====================================================================

====================================================================
Building XLCoST Candidate Rows (Semantic Alignment)
====================================================================

====================================================================
Semantic Alignment — XLCoST
====================================================================
02:01:26 | INFO     | RepoCoderStudio.Main | [test] Pools — NL: 120  Python: 60  Java: 60
02:01:42 | INFO     | RepoCoderStudio.Main | Loading sentence-transformer: sentence-transformers/all-MiniLM-L6-v2

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

02:01:48 | INFO     | RepoCoderStudio.Main | [test] Semantic triples formed: 120
02:01:48 | INFO     | RepoCoderStudio.Main | [train] Pools — NL: 598  Python: 300  Java: 300
02:02:11 | INFO     | RepoCoderStudio.Main | [train] Semantic triples formed: 594
02:02:11 | INFO     | RepoCoderStudio.Main | [validation] Pools — NL: 120  Python: 60  Java: 60
02:02:12 | INFO     | RepoCoderStudio.Main | [validation] Semantic triples formed: 118
02:02:12 | INFO     | RepoCoderStudio.Main | Saved JSONL: /content/drive/MyDrive/RepoCoderStudio/outputs/reports/alignment_analytics.jsonl (3 rows)

====================================================================
XLCoST Alignment Summary
====================================================================
Total triples               : 832
Above threshold             : 832
Confidence threshold        : 0.5
Strategy                    : xlcost_semantic_embedding
Tree-sitter Java            : True
====================================================================

====================================================================
XLCoST Candidate Row Summary
====================================================================
Aligned pairs               : 832
Rows Created                : 832
Splits                      : ['test', 'train', 'validation']
====================================================================

====================================================================
Building CodeXGLUE Candidate Rows (Embedding Alignment)
====================================================================

====================================================================
Semantic Alignment — CodeXGLUE
====================================================================
02:02:13 | INFO     | RepoCoderStudio.Main | [test] CodeXGLUE evidence — Python: 60  Java: 60
02:02:13 | INFO     | RepoCoderStudio.Main | [test] CodeXGLUE accepted triples: 0 | below threshold: 60 | teacher queue py/java: 60/60
02:02:13 | INFO     | RepoCoderStudio.Main | [train] CodeXGLUE evidence — Python: 300  Java: 300
02:02:13 | INFO     | RepoCoderStudio.Main | [train] CodeXGLUE accepted triples: 8 | below threshold: 292 | teacher queue py/java: 292/292
02:02:13 | INFO     | RepoCoderStudio.Main | [validation] CodeXGLUE evidence — Python: 60  Java: 60
02:02:14 | INFO     | RepoCoderStudio.Main | [validation] CodeXGLUE accepted triples: 1 | below threshold: 59 | teacher queue py/java: 59/59
02:02:14 | INFO     | RepoCoderStudio.Main | Saved JSONL: /content/drive/MyDrive/RepoCoderStudio/outputs/teacher_queue/teacher_completion_queue.jsonl (822 rows)
02:02:14 | INFO     | RepoCoderStudio.Main | Saved JSONL: /content/drive/MyDrive/RepoCoderStudio/outputs/reports/alignment_analytics.jsonl (6 rows)

====================================================================
CodeXGLUE Alignment Summary
====================================================================
Accepted triples            : 9
Confidence threshold        : 0.5
Strategy                    : codexglue_docstring_embedding
Tree-sitter Java            : True
Teacher queue rows          : 822
====================================================================

====================================================================
CodeXGLUE Candidate Row Summary
====================================================================
Aligned pairs               : 9
Rows Created                : 9
Splits                      : ['test', 'train', 'validation']
====================================================================

====================================================================
Duplicate Detection
====================================================================

====================================================================
Duplicate Detection Summary
====================================================================
Input Rows                  : 841
Kept Rows                   : 432
Duplicates Removed          : 409
====================================================================
02:02:14 | INFO     | RepoCoderStudio.Main | Saved JSONL: /content/drive/MyDrive/RepoCoderStudio/outputs/candidate_corpus/candidate_corpus.jsonl (432 rows)
02:02:14 | INFO     | RepoCoderStudio.Main | Saved JSONL: /content/drive/MyDrive/RepoCoderStudio/outputs/candidate_corpus/duplicate_report.jsonl (409 rows)

====================================================================
Candidate Corpus Build Summary
====================================================================
Final Candidate Rows        : 432
Duplicates Removed          : 409
Saved Path                  : outputs/candidate_corpus/candidate_corpus.jsonl
====================================================================

Candidate rows: 432

Alignment strategy distribution:
  codexglue_docstring_embedding: 9
  xlcost_semantic_embedding: 423

Alignment confidence: min=0.573  mean=0.988  max=1.000

Sample normalized Python:
def minSum(A, N):
    mp = {}
    sum = 0
    for i in range(N):
        sum += A[i]
        if A[i] in mp:
            mp[A[i]] += 1
        else:
            mp[A[i]] = 1
    minSum = float('inf')
    for it in mp:
        minSum = min(minSum, sum - (it * mp[it]))
    return minSum
arr = [4, 5, 6, 6]
N = len(arr)
print(minSum(arr, N))

Sample normalized Java:
import java.util.*; class GFG {static int minSum(int A[], int N) {HashMap <Integer, Integer> mp = new HashMap <Integer, Integer> (); int sum = 0; for(int i = 0; i <N; i ++) {sum += A [i]; if(mp.containsKey(A [i])) {mp.put(A [i], mp.get(A [i]) + 1);} else {mp.put(A [i], 1);}} int minSum = Integer.MAX_VALUE; for(Map.Entry <Integer, Integer> it: mp.entrySet()) {minSum = Math.min(minSum, sum - (it.getKey() * it.getValue()));} return minSum;} public static void main(String[] args) {int arr[] = {4, 5, 6, 6}; int N = arr.length; System.out.print(minSum(arr, N) + "\n");}}

====================================================================
Candidate Corpus Notebook Summary  [v2.2]
====================================================================
Candidate Rows              : 432
Alignment Strategy          : xlcost_semantic_embedding
First Dataset               : XLCoST
First Split                 : test
====================================================================

In [ ]:
# ============================================================
# 9A: Alignment Analytics  [v2.2]
# ============================================================
import pandas as pd
from src.storage import ProjectStorageManager
from src.logger import SectionPrinter, SummaryPrinter

SectionPrinter.header("Alignment Analytics  [v2.2]")

storage = ProjectStorageManager(CONFIG)

alignment_rows = []

for row in candidate_rows:
    java_meta = row.metadata.get("java_structural_metadata", {}) or {}
    alignment_rows.append(
        {
            "dataset": row.dataset,
            "split": row.split,
            "alignment_strategy": row.metadata.get("alignment_strategy"),
            "alignment_confidence": row.metadata.get("alignment_confidence"),
            "java_structural_backend": java_meta.get("backend"),
            "java_parse_ok": java_meta.get("parse_ok"),
            "python_parse_ok": (row.metadata.get("python_ast_metadata", {}) or {}).get("parse_ok"),
        }
    )

alignment_df = pd.DataFrame(alignment_rows)

print("Rows by dataset:")
display(alignment_df["dataset"].value_counts().reset_index())

print("\nRows by split:")
display(pd.crosstab(alignment_df["dataset"], alignment_df["split"]))

print("\nRows by alignment strategy:")
display(alignment_df["alignment_strategy"].value_counts().reset_index())

print("\nAlignment confidence summary:")
display(alignment_df["alignment_confidence"].astype(float).describe())

print("\nJava structural backend:")
display(alignment_df["java_structural_backend"].value_counts(dropna=False).reset_index())

print("\nJava parse status:")
display(alignment_df["java_parse_ok"].value_counts(dropna=False).reset_index())

# ------------------------------------------------------------
# Engine-level analytics saved by semantic_alignment_engine.py
# ------------------------------------------------------------

analytics_path = "outputs/reports/alignment_analytics.jsonl"
if storage.exists(analytics_path):
    analytics_rows = storage.load_jsonl(analytics_path)
    analytics_stage_df = pd.DataFrame(analytics_rows)
    print("\nStage-level alignment analytics:")
    display(analytics_stage_df)
else:
    analytics_stage_df = pd.DataFrame()
    print("\nNo stage-level alignment analytics artifact found yet.")

# ------------------------------------------------------------
# Teacher completion queue summary
# ------------------------------------------------------------

teacher_queue_path = "outputs/teacher_queue/teacher_completion_queue.jsonl"
if storage.exists(teacher_queue_path):
    teacher_queue_rows = storage.load_jsonl(teacher_queue_path)
    teacher_queue_df = pd.DataFrame(teacher_queue_rows)
    print("\nTeacher completion queue:")
    display(teacher_queue_df[["dataset", "split", "missing_modality", "reason"]].value_counts().reset_index())
else:
    teacher_queue_rows = []
    print("\nTeacher completion queue not created or empty.")

SummaryPrinter.print_summary(
    "Alignment Analytics Summary  [v2.2]",
    {
        "Candidate Rows": len(alignment_df),
        "Datasets": alignment_df["dataset"].nunique() if not alignment_df.empty else 0,
        "Mean Confidence": round(float(alignment_df["alignment_confidence"].astype(float).mean()), 4) if not alignment_df.empty else 0.0,
        "Min Confidence": round(float(alignment_df["alignment_confidence"].astype(float).min()), 4) if not alignment_df.empty else 0.0,
        "Max Confidence": round(float(alignment_df["alignment_confidence"].astype(float).max()), 4) if not alignment_df.empty else 0.0,
        "Teacher Queue Rows": len(teacher_queue_rows),
    },
)

====================================================================
Alignment Analytics  [v2.2]
====================================================================
Rows by dataset:

     dataset  count
0     XLCoST    423
1  CodeXGLUE      9

Rows by split:

split      test  train  validation
dataset
CodeXGLUE     0      8           1
XLCoST       60    301          62

Rows by alignment strategy:

              alignment_strategy  count
0      xlcost_semantic_embedding    423
1  codexglue_docstring_embedding      9

Alignment confidence summary:

count    432.000000
mean       0.987673
std        0.057338
min        0.573315
25%        1.000000
50%        1.000000
75%        1.000000
max        1.000000
Name: alignment_confidence, dtype: float64

Java structural backend:

  java_structural_backend  count
0             tree_sitter    432

Java parse status:

   java_parse_ok  count
0           True    401
1          False     31

02:02:25 | INFO     | RepoCoderStudio.Main | Loaded JSONL: /content/drive/MyDrive/RepoCoderStudio/outputs/reports/alignment_analytics.jsonl (6 rows)

Stage-level alignment analytics:

,dataset,split,strategy,nl_records,python_records,java_records,candidate_pairs_examined,accepted,below_threshold_or_unmatched,threshold,mean_accepted_confidence,min_accepted_confidence,max_accepted_confidence,tree_sitter_available,tree_sitter_error,below_threshold,unmatched_python_for_teacher,unmatched_java_for_teacher
0,XLCoST,test,xlcost_semantic_embedding,120.0,60,60,4730.0,120,0.0,0.5,0.998076,0.973737,1.000000,True,None,NaN,NaN,NaN
1,XLCoST,train,xlcost_semantic_embedding,598.0,300,300,51120.0,594,4.0,0.5,0.997375,0.825565,1.000000,True,None,NaN,NaN,NaN
2,XLCoST,validation,xlcost_semantic_embedding,120.0,60,60,3800.0,118,1.0,0.5,0.993380,0.845064,1.000000,True,None,NaN,NaN,NaN
3,CodeXGLUE,test,codexglue_docstring_embedding,NaN,60,60,NaN,0,NaN,0.5,0.000000,0.000000,0.000000,True,None,60.0,60.0,60.0
4,CodeXGLUE,train,codexglue_docstring_embedding,NaN,300,300,NaN,8,NaN,0.5,0.621361,0.573315,0.698572,True,None,292.0,292.0,292.0
5,CodeXGLUE,validation,codexglue_docstring_embedding,NaN,60,60,NaN,1,NaN,0.5,0.628054,0.628054,0.628054,True,None,59.0,59.0,59.0

02:02:25 | INFO     | RepoCoderStudio.Main | Loaded JSONL: /content/drive/MyDrive/RepoCoderStudio/outputs/teacher_queue/teacher_completion_queue.jsonl (822 rows)

Teacher completion queue:

,dataset,split,missing_modality,reason,count
0,CodeXGLUE,train,java,no_high_confidence_java_match,292
1,CodeXGLUE,train,python,not_used_in_high_confidence_match,292
2,CodeXGLUE,test,java,no_high_confidence_java_match,60
3,CodeXGLUE,test,python,not_used_in_high_confidence_match,60
4,CodeXGLUE,validation,java,no_high_confidence_java_match,59
5,CodeXGLUE,validation,python,not_used_in_high_confidence_match,59

====================================================================
Alignment Analytics Summary  [v2.2]
====================================================================
Candidate Rows              : 432
Datasets                    : 2
Mean Confidence             : 0.9877
Min Confidence              : 0.5733
Max Confidence              : 1.0
Teacher Queue Rows          : 822
====================================================================

In [ ]:
# ============================================================
# 10. Validation Smoke Test  [v2 — Richer AST Artifacts]
# ============================================================

import sys
import importlib

for module_name in list(sys.modules.keys()):
    if module_name == "src" or module_name.startswith("src."):
        del sys.modules[module_name]

importlib.invalidate_caches()

from src.logger import SectionPrinter, SummaryPrinter
from src.python_validator import PythonValidator
from src.java_validator import JavaValidator
from src.csr_builder import CSRBuilder

SectionPrinter.header("Validation Smoke Test  [v2]")

py_validator = PythonValidator()
java_validator = JavaValidator()
csr_builder = CSRBuilder()

sample = candidate_rows[0]

py_result = py_validator.validate(sample.python_code)
java_result = java_validator.validate(sample.java_code)

csr_python = csr_builder.build_python(sample.python_code)
csr_java = csr_builder.build_java(sample.java_code)
csr_score = csr_builder.similarity(csr_python, csr_java)

print("Corpus ID:", sample.corpus_id)
print("\nPython validation (v2 richer artifacts):")
print(f"  status         : {py_result['status']}")
print(f"  function_names : {py_result.get('function_names', [])}")
print(f"  class_names    : {py_result.get('class_names', [])}")
print(f"  import_count   : {py_result.get('import_count', 0)}")
print(f"  has_loop       : {py_result.get('has_loop', False)}")
print(f"  has_conditional: {py_result.get('has_conditional', False)}")
print(f"  has_recursion  : {py_result.get('has_recursion', False)}")
print(f"  ast_node_count : {py_result.get('ast_node_count', 0)}")

print("\nJava validation (v2 + Tree-sitter):")
print(f"  status        : {java_result['status']}")
print(f"  compiles      : {java_result['compiles']}")
print(f"  class_name    : {java_result.get('class_name')}")
struct = java_result.get('structural_artifacts', {})
if struct:
    print(f"  method_names  : {struct.get('method_names', [])}")
    print(f"  class_names   : {struct.get('class_names', [])}")
    print(f"  has_loop      : {struct.get('has_loop', False)}")
    print(f"  backend       : {struct.get('structural_backend', 'none')}")
else:
    print("  structural_artifacts: (tree-sitter not available)")

print(f"\nCSR score       : {csr_score:.4f}")
print(f"CSR Python backend: {csr_python.get('backend')}")
print(f"CSR Java backend  : {csr_java.get('backend')}")

SummaryPrinter.print_summary(
    "Validation Smoke Test Summary  [v2]",
    {
        "Python Status": py_result["status"],
        "Java Status": java_result["status"],
        "Java Tree-sitter": bool(struct),
        "CSR Score": round(csr_score, 4),
    },
)

02:02:45 | INFO     | RepoCoderStudio.Main | Tree-sitter Java grammar loaded (v2 structural analysis active).

====================================================================
Validation Smoke Test  [v2]
====================================================================
Corpus ID: xlcost_6347b5fff72f6575

Python validation (v2 richer artifacts):
  status         : PASS
  function_names : ['minSum']
  class_names    : []
  import_count   : 0
  has_loop       : True
  has_conditional: True
  has_recursion  : True
  ast_node_count : 132

Java validation (v2 + Tree-sitter):
  status        : PASS
  compiles      : True
  class_name    : GFG
  method_names  : ['minSum', 'main']
  class_names   : ['GFG']
  has_loop      : True
  backend       : none

CSR score       : 0.5385
CSR Python backend: ast
CSR Java backend  : tree_sitter

====================================================================
Validation Smoke Test Summary  [v2]
====================================================================
Python Status               : PASS
Java Status                 : PASS
Java Tree-sitter            : True
CSR Score                   : 0.5385
====================================================================

In [ ]:
# ============================================================
# 11. Corpus Validation
# ============================================================

import sys
import importlib

# Reload src modules after replacing .py files.
for module_name in list(sys.modules.keys()):
    if module_name == "src" or module_name.startswith("src."):
        del sys.modules[module_name]

importlib.invalidate_caches()

from src.config import CONFIG
from src.logger import SectionPrinter, SummaryPrinter
from src.storage import ProjectStorageManager
from src.schemas import CandidateRow
from src.validation_engine import ValidationEngine

SectionPrinter.header("Candidate Corpus Validation  [v2.3]")

storage = ProjectStorageManager(CONFIG)

# Use in-memory candidate_rows when available; otherwise load from Drive.
try:
    candidate_rows
    print(f"Using in-memory candidate_rows: {len(candidate_rows)}")
except NameError:
    candidate_dicts = storage.load_jsonl(storage.candidate_corpus_path())
    candidate_rows = [CandidateRow(**row) for row in candidate_dicts]
    print(f"Loaded candidate_rows from Drive: {len(candidate_rows)}")

validation_engine = ValidationEngine(CONFIG)

approved_rows, rejected_rows, validation_reports = validation_engine.run(candidate_rows)

print(f"Approved rows: {len(approved_rows)}")
print(f"Rejected rows: {len(rejected_rows)}")

if approved_rows:
    print("\nSample ApprovedRow:")
    print(approved_rows[0])

if rejected_rows:
    print("\nSample RejectedRow:")
    print(rejected_rows[0])

SummaryPrinter.print_summary(
    "Validation Notebook Summary  [v2.3]",
    {
        "Candidate Rows": len(candidate_rows),
        "Approved Rows": len(approved_rows),
        "Rejected Rows": len(rejected_rows),
        "Approval Rate": round(len(approved_rows) / max(1, len(candidate_rows)), 4),
    },
)

02:03:10 | INFO     | RepoCoderStudio.Main | Tree-sitter Java grammar loaded (v2 structural analysis active).

====================================================================
Candidate Corpus Validation  [v2.3]
====================================================================
Using in-memory candidate_rows: 432

====================================================================
Corpus Validation Engine  [v2.2]
====================================================================

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/659 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/988M [00:00<?, ?B/s]

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

generation_config.json:   0%|          | 0.00/243 [00:00<?, ?B/s]

02:04:05 | INFO     | RepoCoderStudio.Main | Teacher model loaded: Qwen/Qwen2.5-Coder-0.5B-Instruct

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

02:20:03 | INFO     | RepoCoderStudio.Main | Validated 100/432 rows

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

02:27:14 | INFO     | RepoCoderStudio.Main | Validated 200/432 rows

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

02:32:05 | INFO     | RepoCoderStudio.Main | Validated 300/432 rows

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

02:40:59 | INFO     | RepoCoderStudio.Main | Validated 400/432 rows

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

02:56:11 | INFO     | RepoCoderStudio.Main | Saved JSONL: /content/drive/MyDrive/RepoCoderStudio/outputs/approved_corpus/approved_corpus.jsonl (403 rows)
02:56:11 | INFO     | RepoCoderStudio.Main | Saved JSONL: /content/drive/MyDrive/RepoCoderStudio/outputs/rejected_corpus/rejected_corpus.jsonl (29 rows)
02:56:11 | INFO     | RepoCoderStudio.Main | Saved JSONL: /content/drive/MyDrive/RepoCoderStudio/outputs/reports/validation_report.jsonl (432 rows)
02:56:11 | INFO     | RepoCoderStudio.Main | Saved JSONL: /content/drive/MyDrive/RepoCoderStudio/outputs/trusted_tests/trusted_tests.jsonl (403 rows)

====================================================================
Corpus Validation Summary  [v2.2]
====================================================================
Candidate Rows              : 432
Approved Rows               : 403
Rejected Rows               : 29
Approval Rate               : 0.9329
CSR Below Threshold (approved, recorded): 1
Execution NOT_FEASIBLE      : 403
Trusted Test Repository Rows: 403
Tree-sitter Java            : True
====================================================================
Approved rows: 403
Rejected rows: 29

Sample ApprovedRow:
ApprovedRow(corpus_id='xlcost_6347b5fff72f6575', natural_language='Minimum sum possible by removing all occurrences of any array element | Function to find minimum sum after deletion ; Stores frequency of array elements ; Traverse the array ; Calculate sum ; Update frequency of the current element ; Stores the minimum sum required ; Traverse map ; Find the minimum sum obtained ; Return minimum sum ; Input array ; Size of array', python_code="def minSum(A, N):\n    mp = {}\n    sum = 0\n    for i in range(N):\n        sum += A[i]\n        if A[i] in mp:\n            mp[A[i]] += 1\n        else:\n            mp[A[i]] = 1\n    minSum = float('inf')\n    for it in mp:\n        minSum = min(minSum, sum - (it * mp[it]))\n    return minSum\narr = [4, 5, 6, 6]\nN = len(arr)\nprint(minSum(arr, N))", java_code='import java.util.*; class GFG {static int minSum(int A[], int N) {HashMap <Integer, Integer> mp = new HashMap <Integer, Integer> (); int sum = 0; for(int i = 0; i <N; i ++) {sum += A [i]; if(mp.containsKey(A [i])) {mp.put(A [i], mp.get(A [i]) + 1);} else {mp.put(A [i], 1);}} int minSum = Integer.MAX_VALUE; for(Map.Entry <Integer, Integer> it: mp.entrySet()) {minSum = Math.min(minSum, sum - (it.getKey() * it.getValue()));} return minSum;} public static void main(String[] args) {int arr[] = {4, 5, 6, 6}; int N = arr.length; System.out.print(minSum(arr, N) + "\\n");}}', trusted_tests={'status': 'insufficient', 'tests': [], 'candidate_tests': [], 'sources': [], 'notes': 'No trusted logical tests available.'}, python_ast={'backend': 'ast', 'parse_ok': True, 'function_names': ['minSum'], 'class_names': [], 'import_names': [], 'import_count': 0, 'has_loop': True, 'has_conditional': True, 'has_recursion': True, 'line_count': 16, 'ast_node_count': 132}, java_parse_tree={'backend': 'tree_sitter', 'tree_sitter_available': True, 'tree_sitter_error': None, 'parse_ok': True, 'has_parse_error': False, 'class_names': ['GFG'], 'method_names': ['minSum', 'main'], 'constructor_names': [], 'import_names': ['import java.util.*;'], 'package_name': None, 'class_count': 1, 'method_count': 2, 'constructor_count': 0, 'import_count': 1, 'has_loop': True, 'has_conditional': True, 'parse_tree_node_count': 332, 'class_name': 'GFG', 'compiles': True, 'java_status': 'PASS', 'normalized_compilation_unit_available': True, 'repair_metadata': {'stripped_generation_artifacts': False, 'wrapped_missing_class': False, 'detected_class_name': 'GFG'}}, csr_score=0.5384615384615384, validation_status='APPROVED', repair_history=[], corpus_version='combined_stage_v2.0', metadata={'alignment_strategy': 'xlcost_semantic_embedding', 'alignment_confidence': 1.0, 'python_ast_metadata': {'backend': 'ast', 'parse_ok': True, 'function_count': 1, 'class_count': 0, 'import_count': 0, 'function_names': ['minSum'], 'class_names': [], 'has_loop': True, 'has_conditional': True, 'has_recursion': True, 'ast_node_count': 132}, 'java_structural_metadata': {'backend': 'tree_sitter', 'parse_ok': True, 'method_count': 2, 'class_count': 1, 'method_names': ['minSum', 'main'], 'class_names': ['GFG'], 'has_loop': True, 'has_conditional': True, 'parse_tree_node_count': 332}, 'normalized': True, 'normalizer_version': 'normalization_engine_v2.0', 'csr_score': 0.5384615384615384, 'csr_above_threshold': True, 'execution_status': 'NOT_FEASIBLE', 'tree_sitter_java': True, 'java_structural_backend': 'tree_sitter'}, provenance={'dataset': 'codeparrot/xlcost-text-to-code', 'python_config': 'Python-program-level', 'java_config': 'Java-program-level', 'split': 'test', 'alignment_provenance': {'dataset': 'XLCoST', 'split': 'test', 'nl_record_id': 'xlcost_python_nl_test_0', 'py_record_id': '0', 'java_record_id': '0', 'nl_py_similarity': 1.0, 'nl_java_similarity': 0.9326, 'structural_bonus': 0.07, 'python_candidate_rank': 0, 'java_candidate_rank': 0}, 'adapter_version': 'xlcost_adapter_v2.0_semantic', 'corpus_version': 'combined_stage_v2.0'}, semantic_artifacts={'python_ast': {'backend': 'ast', 'parse_ok': True, 'function_names': ['minSum'], 'class_names': [], 'import_names': [], 'import_count': 0, 'has_loop': True, 'has_conditional': True, 'has_recursion': True, 'line_count': 16, 'ast_node_count': 132}, 'java_parse_tree': {'backend': 'tree_sitter', 'tree_sitter_available': True, 'tree_sitter_error': None, 'parse_ok': True, 'has_parse_error': False, 'class_names': ['GFG'], 'method_names': ['minSum', 'main'], 'constructor_names': [], 'import_names': ['import java.util.*;'], 'package_name': None, 'class_count': 1, 'method_count': 2, 'constructor_count': 0, 'import_count': 1, 'has_loop': True, 'has_conditional': True, 'parse_tree_node_count': 332, 'class_name': 'GFG', 'compiles': True, 'java_status': 'PASS', 'normalized_compilation_unit_available': True, 'repair_metadata': {'stripped_generation_artifacts': False, 'wrapped_missing_class': False, 'detected_class_name': 'GFG'}}, 'csr': {'csr_score': 0.5384615384615384, 'note': 'CSR score only is stored; CSR token bags are recomputed when needed.'}, 'alignment': {'strategy': 'xlcost_semantic_embedding', 'confidence': 1.0, 'python_ast_metadata_from_alignment': {'backend': 'ast', 'parse_ok': True, 'function_count': 1, 'class_count': 0, 'import_count': 0, 'function_names': ['minSum'], 'class_names': [], 'has_loop': True, 'has_conditional': True, 'has_recursion': True, 'ast_node_count': 132}, 'java_structural_metadata_from_alignment': {'backend': 'tree_sitter', 'parse_ok': True, 'method_count': 2, 'class_count': 1, 'method_names': ['minSum', 'main'], 'class_names': ['GFG'], 'has_loop': True, 'has_conditional': True, 'parse_tree_node_count': 332}}, 'trusted_tests': {'status': 'insufficient', 'num_tests': 0, 'num_candidate_tests': 0}, 'execution': {'status': 'NOT_FEASIBLE', 'reason': 'no_trusted_tests', 'num_tests': 0}})

Sample RejectedRow:
RejectedRow(corpus_id='xlcost_03ac454aecfccdb0', dataset='XLCoST', split='test', reason='java_validation_failed', details={'status': 'FAIL', 'compiles': False, 'class_name': 'Solution', 'reason': 'javac_error', 'stderr': '/tmp/tmpdj8jhfcx/Solution.java:17: error: int cannot be dereferenced\n            if (!Character.isDigit(c) || !k.contains(String.valueOf(c))) {\n                                           ^\n1 error\n', 'stdout': '', 'normalized_compilation_unit': 'import java.util.*;\n\npublic class Solution {\n    public static int solve(int[] A, int N, int k) {\n        List<Integer> result = new ArrayList<>();\n        for (int i = 0; i < N; i++) {\n            if (isDigitValid(A[i], k)) {\n                result.add(A[i]);\n            }\n        }\n        return result.size();\n    }\n\n    private static boolean isDigitValid(int num, int k) {\n        String numStr = Integer.toString(num);\n        for (char c : numStr.toCharArray()) {\n            if (!Character.isDigit(c) || !k.contains(String.valueOf(c))) {\n                return false;\n            }\n        }\n        return true;\n    }\n\n    public static void main(String[] args) {\n        int[] A = {0, 1, 2, 5};\n        int N = 2;\n        int k = 21;\n        System.out.println(solve(A, N, k)); // Output: 4\n    }\n}', 'repair_metadata': {'stripped_generation_artifacts': False, 'wrapped_missing_class': False, 'detected_class_name': 'Solution'}, 'structural_artifacts': {}, 'tree_sitter_available': True, 'tree_sitter_error': None}, metadata={'alignment_strategy': 'xlcost_semantic_embedding', 'alignment_confidence': 1.0, 'python_ast_metadata': {'backend': 'ast', 'parse_ok': True, 'function_count': 2, 'class_count': 0, 'import_count': 0, 'function_names': ['numToVec', 'solve'], 'class_names': [], 'has_loop': True, 'has_conditional': True, 'has_recursion': True, 'ast_node_count': 441}, 'java_structural_metadata': {'backend': 'tree_sitter', 'parse_ok': False, 'method_count': 3, 'class_count': 1, 'method_names': ['numToVec', 'solve', 'main'], 'class_names': ['GFG'], 'has_loop': True, 'has_conditional': True, 'parse_tree_node_count': 773}, 'normalized': True, 'normalizer_version': 'normalization_engine_v2.0', 'java_repaired': True, 'java_repair_attempt_1': 'teacher_generate_java', 'java_repair_attempt_2': 'teacher_generate_java', 'java_repair_attempt_3': 'teacher_generate_java'}, provenance={'dataset': 'codeparrot/xlcost-text-to-code', 'python_config': 'Python-program-level', 'java_config': 'Java-program-level', 'split': 'test', 'alignment_provenance': {'dataset': 'XLCoST', 'split': 'test', 'nl_record_id': 'xlcost_python_nl_test_32', 'py_record_id': '32', 'java_record_id': '32', 'nl_py_similarity': 1.0, 'nl_java_similarity': 0.9279, 'structural_bonus': 0.08, 'python_candidate_rank': 0, 'java_candidate_rank': 0}, 'adapter_version': 'xlcost_adapter_v2.0_semantic', 'corpus_version': 'combined_stage_v2.0', 'java_repair_1': 'teacher_generate_java', 'java_repair_2': 'teacher_generate_java', 'java_repair_3': 'teacher_generate_java'}, validation_diagnostics={'nl': {'status': 'PASS', 'reason': None, 'word_count': 215}, 'python': {'status': 'PASS', 'parse_ok': True, 'function_names': ['numToVec', 'solve'], 'class_names': [], 'import_names': [], 'import_count': 0, 'has_loop': True, 'has_conditional': True, 'has_recursion': True, 'line_count': 43, 'ast_node_count': 441, 'reason': None}, 'java': {'status': 'FAIL', 'compiles': False, 'class_name': 'Solution', 'reason': 'javac_error', 'stderr': '/tmp/tmpdj8jhfcx/Solution.java:17: error: int cannot be dereferenced\n            if (!Character.isDigit(c) || !k.contains(String.valueOf(c))) {\n                                           ^\n1 error\n', 'stdout': '', 'normalized_compilation_unit': 'import java.util.*;\n\npublic class Solution {\n    public static int solve(int[] A, int N, int k) {\n        List<Integer> result = new ArrayList<>();\n        for (int i = 0; i < N; i++) {\n            if (isDigitValid(A[i], k)) {\n                result.add(A[i]);\n            }\n        }\n        return result.size();\n    }\n\n    private static boolean isDigitValid(int num, int k) {\n        String numStr = Integer.toString(num);\n        for (char c : numStr.toCharArray()) {\n            if (!Character.isDigit(c) || !k.contains(String.valueOf(c))) {\n                return false;\n            }\n        }\n        return true;\n    }\n\n    public static void main(String[] args) {\n        int[] A = {0, 1, 2, 5};\n        int N = 2;\n        int k = 21;\n        System.out.println(solve(A, N, k)); // Output: 4\n    }\n}', 'repair_metadata': {'stripped_generation_artifacts': False, 'wrapped_missing_class': False, 'detected_class_name': 'Solution'}, 'structural_artifacts': {}, 'tree_sitter_available': True, 'tree_sitter_error': None}})

====================================================================
Validation Notebook Summary  [v2.3]
====================================================================
Candidate Rows              : 432
Approved Rows               : 403
Rejected Rows               : 29
Approval Rate               : 0.9329
====================================================================

In [ ]:
# ============================================================
# 12. Validation Analytics + Trusted Test Repository Summary
# ============================================================

import pandas as pd

from src.logger import SectionPrinter, SummaryPrinter
from src.storage import ProjectStorageManager
from src.schemas import dataclass_to_dict

SectionPrinter.header("Validation Analytics  [v2.3]")

storage = ProjectStorageManager(CONFIG)

approved_dicts = [dataclass_to_dict(row) for row in approved_rows]
rejected_dicts = [dataclass_to_dict(row) for row in rejected_rows]

approved_df = pd.DataFrame(approved_dicts)
rejected_df = pd.DataFrame(rejected_dicts)
report_df = pd.DataFrame(validation_reports)

print(f"Approved rows: {len(approved_df)}")
print(f"Rejected rows : {len(rejected_df)}")

if not rejected_df.empty:
    print("\nRejection reasons:")
    display(rejected_df["reason"].value_counts().reset_index())

if not approved_df.empty:
    print("\nApproved rows by dataset:")
    display(approved_df["metadata"].apply(lambda x: x.get("alignment_strategy", "unknown") if isinstance(x, dict) else "unknown").value_counts().reset_index())

    print("\nApproved rows by split:")
    display(approved_df["provenance"].apply(lambda x: x.get("split") if isinstance(x, dict) else None).value_counts(dropna=False).reset_index())

    print("\nCSR score summary:")
    display(approved_df["csr_score"].describe())

    print("\nExecution status summary:")
    display(approved_df["metadata"].apply(lambda x: x.get("execution_status") if isinstance(x, dict) else None).value_counts(dropna=False).reset_index())

    print("\nJava parse backend summary:")
    display(approved_df["java_parse_tree"].apply(lambda x: x.get("backend") if isinstance(x, dict) else None).value_counts(dropna=False).reset_index())

SectionPrinter.header("Trusted Test Repository Summary  [v2.3]")

trusted_path = f"{CONFIG.storage.trusted_tests_dir}/trusted_tests.jsonl"
try:
    trusted_rows = storage.load_jsonl(trusted_path)
except Exception:
    trusted_rows = []

trusted_df = pd.DataFrame(trusted_rows)
print(f"Trusted test repository rows: {len(trusted_df)}")

if not trusted_df.empty:
    print("\nTrusted test status:")
    display(trusted_df["trusted_test_status"].value_counts(dropna=False).reset_index())

    print("\nTrusted test counts:")
    display(trusted_df[["num_trusted_tests", "num_candidate_tests"]].describe())

SummaryPrinter.print_summary(
    "Validation Analytics Summary  [v2.3]",
    {
        "Approved Rows": len(approved_df),
        "Rejected Rows": len(rejected_df),
        "Trusted Test Rows": len(trusted_df),
        "Execution NOT_FEASIBLE": int((approved_df["metadata"].apply(lambda x: x.get("execution_status") if isinstance(x, dict) else None) == "NOT_FEASIBLE").sum()) if not approved_df.empty else 0,
    },
)

====================================================================
Validation Analytics  [v2.3]
====================================================================
Approved rows: 403
Rejected rows : 29

Rejection reasons:

                     reason  count
0    java_validation_failed     28
1  python_validation_failed      1

Approved rows by dataset:

                        metadata  count
0      xlcost_semantic_embedding    402
1  codexglue_docstring_embedding      1

Approved rows by split:

   provenance  count
0       train    296
1  validation     57
2        test     50

CSR score summary:

count    403.000000
mean       0.554511
std        0.101776
min        0.166667
25%        0.500000
50%        0.555556
75%        0.636364
max        0.750000
Name: csr_score, dtype: float64

Execution status summary:

       metadata  count
0  NOT_FEASIBLE    403

Java parse backend summary:

  java_parse_tree  count
0     tree_sitter    403

====================================================================
Trusted Test Repository Summary  [v2.3]
====================================================================
02:56:26 | INFO     | RepoCoderStudio.Main | Loaded JSONL: /content/drive/MyDrive/RepoCoderStudio/outputs/trusted_tests/trusted_tests.jsonl (403 rows)
Trusted test repository rows: 403

Trusted test status:

  trusted_test_status  count
0        insufficient    403

Trusted test counts:

       num_trusted_tests  num_candidate_tests
count              403.0                403.0
mean                 0.0                  0.0
std                  0.0                  0.0
min                  0.0                  0.0
25%                  0.0                  0.0
50%                  0.0                  0.0
75%                  0.0                  0.0
max                  0.0                  0.0

====================================================================
Validation Analytics Summary  [v2.3]
====================================================================
Approved Rows               : 403
Rejected Rows               : 29
Trusted Test Rows           : 403
Execution NOT_FEASIBLE      : 403
====================================================================

In [ ]:
# ============================================================
# 13. Save Validation Analytics
# ============================================================

from src.storage import ProjectStorageManager
from src.config import CONFIG

storage = ProjectStorageManager(CONFIG)

storage.save_csv(
    approved_df,
    "outputs/reports/approved_validation_analytics.csv",
)

storage.save_csv(
    rejected_df,
    "outputs/reports/rejected_validation_analytics.csv",
)

print("Validation analytics saved.")

13:13:41 | INFO     | RepoCoderStudio.Main | Saved CSV: /content/drive/MyDrive/RepoCoderStudio/outputs/reports/approved_validation_analytics.csv (207 rows)
13:13:41 | INFO     | RepoCoderStudio.Main | Saved CSV: /content/drive/MyDrive/RepoCoderStudio/outputs/reports/rejected_validation_analytics.csv (211 rows)
Validation analytics saved.

In [5]:
# ============================================================
# 13.A: Load Approved Corpus from previous validation run
# ============================================================

from src.schemas import ApprovedRow
from src.storage import ProjectStorageManager
from src.logger import SectionPrinter, SummaryPrinter

SectionPrinter.header("Load Existing Approved Corpus")

storage = ProjectStorageManager(CONFIG)
approved_dicts = storage.load_jsonl(storage.approved_corpus_path())

approved_rows = [ApprovedRow(**row) for row in approved_dicts]

SummaryPrinter.print_summary(
    "Approved Corpus Loaded",
    {
        "Approved Rows": len(approved_rows),
        "Source": storage.approved_corpus_path(),
        "Validation Rerun": "No",
    },
)

print("Sample approved corpus_id:", approved_rows[0].corpus_id if approved_rows else None)

====================================================================
Load Existing Approved Corpus
====================================================================
16:14:53 | INFO     | RepoCoderStudio.Main | Loaded JSONL: /content/drive/MyDrive/RepoCoderStudio/outputs/approved_corpus/approved_corpus.jsonl (403 rows)

====================================================================
Approved Corpus Loaded
====================================================================
Approved Rows               : 403
Source                      : outputs/approved_corpus/approved_corpus.jsonl
Validation Rerun            : No
====================================================================
Sample approved corpus_id: xlcost_6347b5fff72f6575

In [6]:
# ============================================================
# 14. Task Dataset Construction  [v2.6]
# ============================================================

from src.logger import SectionPrinter, SummaryPrinter
from src.task_builder import TaskDatasetBuilder

SectionPrinter.header("Task Dataset Construction  [v2.6]")

task_builder = TaskDatasetBuilder(CONFIG)
task_examples = task_builder.build(approved_rows)

print(f"Task examples: {len(task_examples)}")
print("Split summary:", task_builder.split_summary(task_examples))

if task_examples:
    print("\nSample training text:")
    print(task_examples[0].metadata.get("training_text", "")[:1800])
    print("\nSample prompt hash:", task_examples[0].metadata.get("prompt_hash"))
    print("Sample response header:", task_examples[0].metadata.get("response_header"))

====================================================================
Task Dataset Construction  [v2.6]
====================================================================

====================================================================
Task Dataset Builder  [v2.3]
====================================================================
16:15:03 | INFO     | RepoCoderStudio.Main | Saved JSONL: /content/drive/MyDrive/RepoCoderStudio/outputs/task_datasets/task_dataset.jsonl (2418 rows)
16:15:04 | INFO     | RepoCoderStudio.Main | Saved CSV: /content/drive/MyDrive/RepoCoderStudio/outputs/reports/task_distribution_v2_3.csv (18 rows)
16:15:04 | INFO     | RepoCoderStudio.Main | Saved CSV: /content/drive/MyDrive/RepoCoderStudio/outputs/reports/task_family_difficulty_v2_3.csv (18 rows)
16:15:05 | INFO     | RepoCoderStudio.Main | Saved CSV: /content/drive/MyDrive/RepoCoderStudio/outputs/reports/task_dataset_contribution_v2_3.csv (12 rows)
16:15:05 | INFO     | RepoCoderStudio.Main | Saved JSON: /content/drive/MyDrive/RepoCoderStudio/outputs/reports/task_dataset_summary_v2_3.json

====================================================================
Task Dataset Summary  [v2.3]
====================================================================
Approved Rows               : 403
Task Examples               : 2418
Expected Max                : 2418
Skipped Empty Tasks         : 0
Prompt Version              : prompt_contract_v2.6
====================================================================
Task examples: 2418
Split summary: {'test': 300, 'train': 1776, 'validation': 342}

Sample training text:
<TASK_NL_TO_PYTHON>
### Task Contract
Prompt Version: prompt_contract_v2.6
Task Token: <TASK_NL_TO_PYTHON>
Task ID: T1
Task: T1: Natural Language -> Python
Source Modality: Natural Language
Target Modality: Python
Role: You are a Python code generator.
Objective: Convert the programming task description into executable Python source code.
Output Contract: Return Python source code only.
Expected Response Header: ### Python
Forbidden Output Types: markdown, explanation, java, pseudocode
Constraints:
- Do not include Markdown fences.
- Do not include explanations or prose.
- Do not output Java or pseudocode.
- Preserve the intended algorithm and observable behaviour.
- Prefer clear functions and executable Python syntax.
Quality Checks:
- The output should parse with Python ast.parse.
- The output should contain only Python code.
Success Criteria:
- Valid Python syntax.
- Implements the requested task behaviour.
- Contains no markdown or explanatory prose.

### Instruction
Generate a correct Python implementation for the programming task.

### Input
Minimum sum possible by removing all occurrences of any array element | Function to find minimum sum after deletion ; Stores frequency of array elements ; Traverse the array ; Calculate sum ; Update frequency of the current element ; Stores the minimum sum required ; Traverse map ; Find the minimum sum obtained ; Return minimum sum ; Input array ; Size of array

### Python
def minSum(A, N):
    mp = {}
    sum = 0
    for i in range(N):
        sum += A[i]
        if A[i] in mp:
            mp[A[i]] += 1
        else:
            mp[A[i]] = 1
    minSum = float('inf')
    for it in mp:
        minSum = min(minSum, sum - (it * mp[it]))
    return minSum
arr = [4, 5, 6, 6]
N = len(arr)
print(minSum(arr, N))

Sample prompt hash: 69fe5435efaa060d9c53024e92985af2513a6b290a6b6b2df8204775287bb32e
Sample response header: ### Python

In [7]:
# ============================================================
# 15. HF Dataset Preparation  [v2.6]
# ============================================================

from src.logger import SectionPrinter
from src.tokenizer_builder import TokenizerDatasetBuilder

SectionPrinter.header("HF Dataset Preparation  [v2.6]")

tokenizer_builder = TokenizerDatasetBuilder(CONFIG)
train_dataset, validation_dataset, test_dataset = tokenizer_builder.build(task_examples)

print(train_dataset)
print(validation_dataset)
print(test_dataset)

if len(train_dataset) > 0:
    print("\nSample row text:")
    print(train_dataset[0]["text"][:1800])
    print("\nSample prompt hash:", train_dataset[0].get("prompt_hash"))
    print("Sample response header:", train_dataset[0].get("response_header"))

====================================================================
HF Dataset Preparation  [v2.6]
====================================================================

====================================================================
Tokenizer Dataset Builder  [v2.6]
====================================================================

====================================================================
HF Dataset Summary  [v2.6]
====================================================================
Train Rows                  : 1776
Validation Rows             : 342
Test Rows                   : 300
Train Task Counts           : {'T1': 296, 'T2': 296, 'T3': 296, 'T4': 296, 'T5': 296, 'T6': 296}
Validation Task Counts      : {'T1': 57, 'T2': 57, 'T3': 57, 'T4': 57, 'T5': 57, 'T6': 57}
Test Task Counts            : {'T1': 50, 'T2': 50, 'T3': 50, 'T4': 50, 'T5': 50, 'T6': 50}
Curriculum                  : round_robin_by_task
====================================================================
Dataset({
    features: ['task_id', 'corpus_id', 'source_modality', 'target_modality', 'split', 'instruction', 'input_text', 'output_text', 'text', 'prompt_version', 'task_contract_version', 'prompt_hash', 'response_header', 'task_family', 'curriculum_stage', 'difficulty', 'expected_output_kind', 'prompt_task_token', 'output_contract', 'prompt_success_criteria', 'csr_score', 'alignment_strategy', 'teacher_generated_or_repaired', 'trusted_test_status'],
    num_rows: 1776
})
Dataset({
    features: ['task_id', 'corpus_id', 'source_modality', 'target_modality', 'split', 'instruction', 'input_text', 'output_text', 'text', 'prompt_version', 'task_contract_version', 'prompt_hash', 'response_header', 'task_family', 'curriculum_stage', 'difficulty', 'expected_output_kind', 'prompt_task_token', 'output_contract', 'prompt_success_criteria', 'csr_score', 'alignment_strategy', 'teacher_generated_or_repaired', 'trusted_test_status'],
    num_rows: 342
})
Dataset({
    features: ['task_id', 'corpus_id', 'source_modality', 'target_modality', 'split', 'instruction', 'input_text', 'output_text', 'text', 'prompt_version', 'task_contract_version', 'prompt_hash', 'response_header', 'task_family', 'curriculum_stage', 'difficulty', 'expected_output_kind', 'prompt_task_token', 'output_contract', 'prompt_success_criteria', 'csr_score', 'alignment_strategy', 'teacher_generated_or_repaired', 'trusted_test_status'],
    num_rows: 300
})

Sample row text:
<TASK_NL_TO_PYTHON>
### Task Contract
Prompt Version: prompt_contract_v2.6
Task Token: <TASK_NL_TO_PYTHON>
Task ID: T1
Task: T1: Natural Language -> Python
Source Modality: Natural Language
Target Modality: Python
Role: You are a Python code generator.
Objective: Convert the programming task description into executable Python source code.
Output Contract: Return Python source code only.
Expected Response Header: ### Python
Forbidden Output Types: markdown, explanation, java, pseudocode
Constraints:
- Do not include Markdown fences.
- Do not include explanations or prose.
- Do not output Java or pseudocode.
- Preserve the intended algorithm and observable behaviour.
- Prefer clear functions and executable Python syntax.
Quality Checks:
- The output should parse with Python ast.parse.
- The output should contain only Python code.
Success Criteria:
- Valid Python syntax.
- Implements the requested task behaviour.
- Contains no markdown or explanatory prose.

### Instruction
Generate a correct Python implementation for the programming task.

### Input
Find nth Hermite number | Function to return nth Hermite number ; Base conditions ; Driver Code ; Print nth Hermite number

### Python
def getHermiteNumber(n):
    if n == 0:
        return 1
    if n == 1:
        return 0
    else:
        return(- 2 * (n - 1) * getHermiteNumber(n - 2))
n = 6
print(getHermiteNumber(n));

Sample prompt hash: ff16c5e947d970fd2302b963a1ab7bc453c47249e621115075bc456941d2303a
Sample response header: ### Python

In [8]:
# ============================================================
# Training Manifest  [v2.6]
# ============================================================

import json
import os
import time
import hashlib
import numpy as np
import pandas as pd

from src.logger import SectionPrinter

SectionPrinter.header("Training Manifest  [v2.6]")


# ------------------------------------------------------------
# Helper: convert numpy objects into JSON-safe Python objects
# ------------------------------------------------------------

def make_json_safe(obj):

    if isinstance(obj, dict):
        return {str(k): make_json_safe(v) for k, v in obj.items()}

    if isinstance(obj, list):
        return [make_json_safe(v) for v in obj]

    if isinstance(obj, tuple):
        return [make_json_safe(v) for v in obj]

    if isinstance(obj, np.integer):
        return int(obj)

    if isinstance(obj, np.floating):
        return float(obj)

    if isinstance(obj, np.bool_):
        return bool(obj)

    if isinstance(obj, np.ndarray):
        return obj.tolist()

    return obj


# ------------------------------------------------------------
# Dataset statistics
# ------------------------------------------------------------

train_task_counts = (
    pd.Series(train_dataset["task_id"])
    .value_counts()
    .sort_index()
    .to_dict()
)

validation_task_counts = (
    pd.Series(validation_dataset["task_id"])
    .value_counts()
    .sort_index()
    .to_dict()
)

test_task_counts = (
    pd.Series(test_dataset["task_id"])
    .value_counts()
    .sort_index()
    .to_dict()
)

prompt_hash = hashlib.sha256(
    train_dataset[0]["text"].encode("utf-8")
).hexdigest()


# ------------------------------------------------------------
# Manifest
# ------------------------------------------------------------

manifest = {

    "manifest_version":
        CONFIG.experiment.training_manifest_version,

    "created_at":
        time.strftime("%Y-%m-%d %H:%M:%S"),

    "project": {

        "name":
            CONFIG.project.name,

        "stage":
            CONFIG.project.stage,

        "specification_version":
            CONFIG.project.specification_version,

    },

    "runtime": {

        "run_mode":
            CONFIG.runtime.run_mode,

        "random_seed":
            CONFIG.runtime.random_seed,

    },

    "experiment": {

        "experiment_version":
            CONFIG.experiment.experiment_version,

        "prompt_version":
            CONFIG.experiment.prompt_version,

        "task_contract_version":
            CONFIG.experiment.task_contract_version,

        "task_builder_version":
            CONFIG.experiment.task_builder_version,

        "metric_registry_version":
            CONFIG.experiment.metric_registry_version,

    },

    "dataset": {

        "approved_rows":
            len(approved_rows),

        "task_examples":
            len(task_examples),

        "train_rows":
            len(train_dataset),

        "validation_rows":
            len(validation_dataset),

        "test_rows":
            len(test_dataset),

    },

    "curriculum": {

        "strategy":
            "round_robin_by_task",

        "train_task_counts":
            train_task_counts,

        "validation_task_counts":
            validation_task_counts,

        "test_task_counts":
            test_task_counts,

    },

    "model": {

        "student_model":
            CONFIG.models.student_model_name,

        "teacher_model":
            CONFIG.models.teacher_model_name,

        "load_in_4bit":
            CONFIG.models.use_4bit,

        "max_sequence_length":
            CONFIG.models.max_seq_length,

        "max_new_tokens":
            CONFIG.models.max_new_tokens,

    },

    "training": {

        "epochs_demo":
            CONFIG.training.num_train_epochs_demo,

        "epochs_full":
            CONFIG.training.num_train_epochs_full,

        "learning_rate":
            CONFIG.training.learning_rate,

        "batch_size":
            CONFIG.training.per_device_train_batch_size,

        "gradient_accumulation":
            CONFIG.training.gradient_accumulation_steps,

        "lora_rank":
            CONFIG.training.lora_rank,

        "lora_alpha":
            CONFIG.training.lora_alpha,

        "lora_dropout":
            CONFIG.training.lora_dropout,

        "adapter_name":
            CONFIG.training.final_adapter_name,

    },

    "prompt_engineering": {

        "prompt_hash":
            prompt_hash,

        "response_headers":
            sorted(
                set(train_dataset["response_header"])
            ),

        "task_tokens":
            sorted(
                set(train_dataset["prompt_task_token"])
            ),

    },

    "validation": {

        "csr_enabled":
            CONFIG.validation.enable_csr_validation,

        "teacher_repair":
            CONFIG.validation.enable_teacher_repair,

        "tree_sitter":
            CONFIG.validation.use_tree_sitter_java,

    },

}


manifest = make_json_safe(manifest)


# ------------------------------------------------------------
# Save
# ------------------------------------------------------------

manifest_dir = os.path.join(
    CONFIG.storage.drive_project_root,
    CONFIG.storage.manifests_dir,
)

os.makedirs(manifest_dir, exist_ok=True)

manifest_path = os.path.join(
    manifest_dir,
    "training_manifest_v2_6.json",
)

with open(manifest_path, "w", encoding="utf-8") as f:
    json.dump(manifest, f, indent=4)

print()

print("Training manifest saved successfully.")

print(manifest_path)

print()

print(json.dumps(manifest, indent=2)[:2500])

====================================================================
Training Manifest  [v2.6]
====================================================================

Training manifest saved successfully.
/content/drive/MyDrive/RepoCoderStudio/outputs/manifests/training_manifest_v2_6.json

{
  "manifest_version": "training_manifest_v2.6",
  "created_at": "2026-07-04 16:15:19",
  "project": {
    "name": "RepoCoderStudio",
    "stage": "CombinedStage",
    "specification_version": "2.0"
  },
  "runtime": {
    "run_mode": "demo",
    "random_seed": 42
  },
  "experiment": {
    "experiment_version": "experiment_v2.6",
    "prompt_version": "prompt_contract_v2.6",
    "task_contract_version": "task_contract_v2.6",
    "task_builder_version": "task_builder_v2.3",
    "metric_registry_version": "metric_registry_v2.0"
  },
  "dataset": {
    "approved_rows": 403,
    "task_examples": 2418,
    "train_rows": 1776,
    "validation_rows": 342,
    "test_rows": 300
  },
  "curriculum": {
    "strategy": "round_robin_by_task",
    "train_task_counts": {
      "T1": 296,
      "T2": 296,
      "T3": 296,
      "T4": 296,
      "T5": 296,
      "T6": 296
    },
    "validation_task_counts": {
      "T1": 57,
      "T2": 57,
      "T3": 57,
      "T4": 57,
      "T5": 57,
      "T6": 57
    },
    "test_task_counts": {
      "T1": 50,
      "T2": 50,
      "T3": 50,
      "T4": 50,
      "T5": 50,
      "T6": 50
    }
  },
  "model": {
    "student_model": "Qwen/Qwen2.5-Coder-0.5B-Instruct",
    "teacher_model": "Qwen/Qwen2.5-Coder-0.5B-Instruct",
    "load_in_4bit": true,
    "max_sequence_length": 1024,
    "max_new_tokens": 384
  },
  "training": {
    "epochs_demo": 1.0,
    "epochs_full": 2.0,
    "learning_rate": 0.0002,
    "batch_size": 1,
    "gradient_accumulation": 8,
    "lora_rank": 8,
    "lora_alpha": 16,
    "lora_dropout": 0.05,
    "adapter_name": "RepoCoderStudio_CombinedStage_LoRA_v1_0"
  },
  "prompt_engineering": {
    "prompt_hash": "ff16c5e947d970fd2302b963a1ab7bc453c47249e621115075bc456941d2303a",
    "response_headers": [
      "### Explanation",
      "### Java",
      "### Java Translation",
      "### Python",
      "### Python Translation"
    ],
    "task_tokens": [
      "<TASK_JAVA_TO_NL>",
      "<TASK_JAVA_TO_PYTHON>",
      "<TASK_NL_TO_JAVA>",
      "<TASK_NL_TO_PYTHON>",
      "<TASK_PYTHON_TO_JAVA>",
      "<TASK_PYTHON_TO_NL>"
    ]
  },
  "validation": {
    "csr_enabled": true,
    "teacher_repair": true,
    "tree_sitter": true
  }
}

In [9]:
# ============================================================
# 16. Task Distribution Audit  [v2.6]
# ============================================================

import pandas as pd
from src.logger import SectionPrinter, SummaryPrinter

SectionPrinter.header("Task Distribution Audit  [v2.6]")

rows = []
for ex in task_examples:
    md = ex.metadata or {}
    rows.append({
        "task_id": ex.task_id,
        "split": ex.split,
        "source_modality": ex.source_modality,
        "target_modality": ex.target_modality,
        "prompt_version": md.get("prompt_version"),
        "response_header": md.get("response_header"),
        "difficulty": md.get("difficulty"),
        "task_family": md.get("task_family"),
        "prompt_hash": md.get("prompt_hash"),
    })

df = pd.DataFrame(rows)

print("Task counts:")
display(df["task_id"].value_counts().sort_index().reset_index(name="count"))

print("\nTask counts by split:")
display(pd.crosstab(df["task_id"], df["split"]))

print("\nResponse headers:")
display(df[["task_id", "response_header"]].drop_duplicates().sort_values("task_id"))

print("\nPrompt versions:")
display(df["prompt_version"].value_counts().reset_index(name="count"))

print("\nPrompt hash uniqueness:")
print("unique prompt hashes:", df["prompt_hash"].nunique())
print("total examples     :", len(df))

SummaryPrinter.print_summary(
    "Task Distribution Audit Summary  [v2.6]",
    {
        "Total Task Examples": len(df),
        "Unique Tasks": df["task_id"].nunique(),
        "Unique Corpus Rows": len({ex.corpus_id for ex in task_examples}),
        "Prompt Version": df["prompt_version"].iloc[0] if len(df) else None,
    },
)

====================================================================
Task Distribution Audit  [v2.6]
====================================================================
Task counts:

  task_id  count
0      T1    403
1      T2    403
2      T3    403
3      T4    403
4      T5    403
5      T6    403

Task counts by split:

split    test  train  validation
task_id
T1         50    296          57
T2         50    296          57
T3         50    296          57
T4         50    296          57
T5         50    296          57
T6         50    296          57

Response headers:

  task_id         response_header
0      T1              ### Python
1      T2                ### Java
2      T3    ### Java Translation
3      T4  ### Python Translation
4      T5         ### Explanation
5      T6         ### Explanation

Prompt versions:

         prompt_version  count
0  prompt_contract_v2.6   2418

Prompt hash uniqueness:
unique prompt hashes: 2418
total examples     : 2418

====================================================================
Task Distribution Audit Summary  [v2.6]
====================================================================
Total Task Examples         : 2418
Unique Tasks                : 6
Unique Corpus Rows          : 403
Prompt Version              : prompt_contract_v2.6
====================================================================

In [11]:
# ============================================================
# CodeBLEU Test Using Current MetricEngine API
# ============================================================

from fractions import Fraction as _BaseFraction
import nltk.translate.bleu_score as bleu_score

class CompatFraction(_BaseFraction):
    def __new__(cls, numerator=0, denominator=None, *, _normalize=True):
        if denominator is None:
            return super().__new__(cls, numerator)
        return super().__new__(cls, numerator, denominator)

bleu_score.Fraction = CompatFraction

from src.metric_engine import MetricEngine

metric_engine = MetricEngine(CONFIG)

test = metric_engine.codebleu(
    reference="def add(a, b):\n    return a + b",
    prediction="def add(a, b):\n    return a + b",
    lang="python",
)

print(test)

14:46:16 | INFO     | RepoCoderStudio.Main | Tree-sitter Java grammar loaded (v2 structural analysis active).

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading extra modules: 0.00B [00:00, ?B/s]

Downloading extra modules: 0.00B [00:00, ?B/s]

Downloading extra modules: 0.00B [00:00, ?B/s]

Downloading extra modules: 0.00B [00:00, ?B/s]

Downloading extra modules: 0.00B [00:00, ?B/s]

Downloading extra modules: 0.00B [00:00, ?B/s]

Downloading extra modules: 0.00B [00:00, ?B/s]

Downloading extra modules: 0.00B [00:00, ?B/s]

Downloading data:   0%|          | 0.00/917 [00:00<?, ?B/s]

Downloaded keywords to /root/.cache/huggingface/metrics/codebleu/default/downloads/extracted/67c115902ce4a05b395e29085b24f9706ff8a253b83cb2505a8d9d9cef445aea

Downloading data:   0%|          | 0.00/3.00M [00:00<?, ?B/s]

Downloaded languages.so to /root/.cache/huggingface/metrics/codebleu/default/downloads/46aff845b03a4565a25afbb505e64d45b6c12ef6546d66630b2dc81989359af1
14:46:36 | INFO     | RepoCoderStudio.Main | Official CodeBLEU metric available via evaluate/dvitel/codebleu.
14:46:37 | WARNING  | RepoCoderStudio.Main | Official CodeBLEU failed once and will be disabled for the rest of this run. lang=python; reason=Fraction.__new__() got an unexpected keyword argument '_normalize'
{'official_codebleu': None, 'codebleu_lite': 1.0, 'codebleu': 1.0, 'official_codebleu_used': False, 'codebleu_backend': 'lite_fallback', 'official_codebleu_error': "Fraction.__new__() got an unexpected keyword argument '_normalize'"}

In [12]:
# ============================================================
# 17. Baseline Evaluation  [v2 — Modular Pipeline]
# ============================================================

import sys
import importlib

for module_name in list(sys.modules.keys()):
    if module_name == "src" or module_name.startswith("src."):
        del sys.modules[module_name]

importlib.invalidate_caches()

from src.config import CONFIG
from src.evaluator import EvaluationEngine
from src.logger import SectionPrinter

SectionPrinter.header("Baseline Evaluation: Pretrained Qwen  [v2]")

baseline_evaluator = EvaluationEngine(CONFIG)

baseline_prediction_logs, baseline_metric_rows, baseline_summary_df = baseline_evaluator.evaluate(
    test_dataset=test_dataset,
    model_type="baseline",
    max_examples_per_task=CONFIG.evaluation.demo_eval_examples_per_task,
    print_inspection=True,
    print_failures=True,
)

print("\nBaseline Summary:")
display(baseline_summary_df)

14:46:54 | INFO     | RepoCoderStudio.Main | Tree-sitter Java grammar loaded (v2 structural analysis active).

====================================================================
Baseline Evaluation: Pretrained Qwen  [v2]
====================================================================

====================================================================
BASELINE Evaluation  [v2.4]
====================================================================

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

14:47:00 | INFO     | RepoCoderStudio.Main | Loading base model: Qwen/Qwen2.5-Coder-0.5B-Instruct

config.json:   0%|          | 0.00/659 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/988M [00:00<?, ?B/s]

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

generation_config.json:   0%|          | 0.00/243 [00:00<?, ?B/s]

14:47:19 | INFO     | RepoCoderStudio.Main | [baseline] 1/60 | T1

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

Downloaded keywords to /root/.cache/huggingface/metrics/codebleu/default/downloads/extracted/67c115902ce4a05b395e29085b24f9706ff8a253b83cb2505a8d9d9cef445aea
Downloaded languages.so to /root/.cache/huggingface/metrics/codebleu/default/downloads/46aff845b03a4565a25afbb505e64d45b6c12ef6546d66630b2dc81989359af1
14:47:52 | INFO     | RepoCoderStudio.Main | Official CodeBLEU metric available via evaluate/dvitel/codebleu.
14:47:53 | WARNING  | RepoCoderStudio.Main | Official CodeBLEU failed once and will be disabled for the rest of this run. lang=python; reason=Fraction.__new__() got an unexpected keyword argument '_normalize'
14:47:53 | INFO     | RepoCoderStudio.Main | [baseline] 2/60 | T1
14:48:22 | INFO     | RepoCoderStudio.Main | [baseline] 3/60 | T1
14:48:50 | INFO     | RepoCoderStudio.Main | [baseline] 4/60 | T1
14:49:18 | INFO     | RepoCoderStudio.Main | [baseline] 5/60 | T1
14:49:47 | INFO     | RepoCoderStudio.Main | [baseline] 6/60 | T1
14:50:15 | INFO     | RepoCoderStudio.Main | [baseline] 7/60 | T1
14:50:43 | INFO     | RepoCoderStudio.Main | [baseline] 8/60 | T1
14:51:11 | INFO     | RepoCoderStudio.Main | [baseline] 9/60 | T1
14:51:39 | INFO     | RepoCoderStudio.Main | [baseline] 10/60 | T1
14:52:07 | INFO     | RepoCoderStudio.Main | [baseline] 11/60 | T2
14:52:37 | INFO     | RepoCoderStudio.Main | [baseline] 12/60 | T2

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

14:53:06 | INFO     | RepoCoderStudio.Main | [baseline] 13/60 | T2

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

14:53:35 | INFO     | RepoCoderStudio.Main | [baseline] 14/60 | T2

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

14:54:04 | INFO     | RepoCoderStudio.Main | [baseline] 15/60 | T2

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

14:54:33 | INFO     | RepoCoderStudio.Main | [baseline] 16/60 | T2

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

14:55:02 | INFO     | RepoCoderStudio.Main | [baseline] 17/60 | T2

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

14:55:31 | INFO     | RepoCoderStudio.Main | [baseline] 18/60 | T2

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

14:55:59 | INFO     | RepoCoderStudio.Main | [baseline] 19/60 | T2

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

14:56:28 | INFO     | RepoCoderStudio.Main | [baseline] 20/60 | T2

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

14:56:57 | INFO     | RepoCoderStudio.Main | [baseline] 21/60 | T3

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

14:57:25 | INFO     | RepoCoderStudio.Main | [baseline] 22/60 | T3

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

14:57:58 | INFO     | RepoCoderStudio.Main | [baseline] 23/60 | T3

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

14:58:27 | INFO     | RepoCoderStudio.Main | [baseline] 24/60 | T3

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

14:58:56 | INFO     | RepoCoderStudio.Main | [baseline] 25/60 | T3

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

14:59:24 | INFO     | RepoCoderStudio.Main | [baseline] 26/60 | T3
14:59:59 | INFO     | RepoCoderStudio.Main | [baseline] 27/60 | T3

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

15:00:28 | INFO     | RepoCoderStudio.Main | [baseline] 28/60 | T3

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

15:00:56 | INFO     | RepoCoderStudio.Main | [baseline] 29/60 | T3

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

15:01:25 | INFO     | RepoCoderStudio.Main | [baseline] 30/60 | T3

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

15:01:54 | INFO     | RepoCoderStudio.Main | [baseline] 31/60 | T4

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

15:02:22 | INFO     | RepoCoderStudio.Main | [baseline] 32/60 | T4
15:02:50 | INFO     | RepoCoderStudio.Main | [baseline] 33/60 | T4
15:03:17 | INFO     | RepoCoderStudio.Main | [baseline] 34/60 | T4
15:03:45 | INFO     | RepoCoderStudio.Main | [baseline] 35/60 | T4
15:04:13 | INFO     | RepoCoderStudio.Main | [baseline] 36/60 | T4
15:04:40 | INFO     | RepoCoderStudio.Main | [baseline] 37/60 | T4
15:05:08 | INFO     | RepoCoderStudio.Main | [baseline] 38/60 | T4
15:05:35 | INFO     | RepoCoderStudio.Main | [baseline] 39/60 | T4
15:06:03 | INFO     | RepoCoderStudio.Main | [baseline] 40/60 | T4
15:06:32 | INFO     | RepoCoderStudio.Main | [baseline] 41/60 | T5

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

15:07:08 | INFO     | RepoCoderStudio.Main | [baseline] 42/60 | T5

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

15:07:37 | INFO     | RepoCoderStudio.Main | [baseline] 43/60 | T5
15:08:06 | INFO     | RepoCoderStudio.Main | [baseline] 44/60 | T5
15:08:34 | INFO     | RepoCoderStudio.Main | [baseline] 45/60 | T5
15:09:03 | INFO     | RepoCoderStudio.Main | [baseline] 46/60 | T5
15:09:31 | INFO     | RepoCoderStudio.Main | [baseline] 47/60 | T5
15:10:00 | INFO     | RepoCoderStudio.Main | [baseline] 48/60 | T5
15:10:29 | INFO     | RepoCoderStudio.Main | [baseline] 49/60 | T5
15:10:58 | INFO     | RepoCoderStudio.Main | [baseline] 50/60 | T5
15:11:21 | INFO     | RepoCoderStudio.Main | [baseline] 51/60 | T6
15:11:50 | INFO     | RepoCoderStudio.Main | [baseline] 52/60 | T6
15:12:19 | INFO     | RepoCoderStudio.Main | [baseline] 53/60 | T6
15:12:48 | INFO     | RepoCoderStudio.Main | [baseline] 54/60 | T6
15:13:16 | INFO     | RepoCoderStudio.Main | [baseline] 55/60 | T6
15:13:46 | INFO     | RepoCoderStudio.Main | [baseline] 56/60 | T6
15:14:14 | INFO     | RepoCoderStudio.Main | [baseline] 57/60 | T6
15:14:43 | INFO     | RepoCoderStudio.Main | [baseline] 58/60 | T6
15:15:11 | INFO     | RepoCoderStudio.Main | [baseline] 59/60 | T6
15:15:40 | INFO     | RepoCoderStudio.Main | [baseline] 60/60 | T6
15:16:09 | INFO     | RepoCoderStudio.Main | Saved JSONL: /content/drive/MyDrive/RepoCoderStudio/outputs/evaluation/baseline_prediction_logs.jsonl (60 rows)
15:16:09 | INFO     | RepoCoderStudio.Main | Saved JSONL: /content/drive/MyDrive/RepoCoderStudio/outputs/evaluation/baseline_metric_rows.jsonl (60 rows)

======================================================================
  PREDICTION INSPECTION [BASELINE]
======================================================================

[Task: T1 | Natural Language -> Python]
  INPUT     : Minimum sum possible by removing all occurrences of any array element | Function to find minimum sum after deletion ; Stores frequency of array elements ; Traverse the array ; Calculate sum ; Update frequency of the curr...
  REFERENCE : def minSum(A, N): ↵     mp = {} ↵     sum = 0 ↵     for i in range(N): ↵         sum += A[i] ↵         if A[i] in mp: ↵             mp[A[i]] += 1 ↵         else: ↵             mp[A[i]] = 1 ↵     minSum = float('inf') ↵  ...
  PREDICTION: def min_sum_after_deletion(arr): ↵     frequency = {} ↵     for num in arr: ↵         if num in frequency: ↵             frequency[num] += 1 ↵         else: ↵             frequency[num] = 1 ↵      ↵     min_sum = float('...
  METRICS   : primary_success=True | codebleu=0.6230 | csr_score=0.9091 | failure_category=ok

[Task: T1 | Natural Language -> Python]
  INPUT     : Maximum difference between a pair of adjacent elements by excluding every element once | Function to calculate maximum difference between adjacent elements excluding every array element once ; Traverse the array ; Stores...
  REFERENCE : def maxAdjacent(arr, N): ↵     res = [] ↵     for i in range(1, N - 1): ↵         prev = arr[0] ↵         maxi = - 1 * float('inf') ↵         for j in range(1, N): ↵             if(i == j): ↵                 continue ↵  ...
  PREDICTION: def max_adjacent_diff(arr): ↵     # Initialize variables ↵     max_diff = float('-inf') ↵     prev_val = arr[0] ↵      ↵     # Iterate through the array starting from the second element ↵     for i in range(1, len(arr)):...
  METRICS   : primary_success=True | codebleu=0.4792 | csr_score=0.8889 | failure_category=ok

[Task: T2 | Natural Language -> Java]
  INPUT     : Minimum sum possible by removing all occurrences of any array element | Function to find minimum sum after deletion ; Stores frequency of array elements ; Traverse the array ; Calculate sum ; Update frequency of the curr...
  REFERENCE : import java.util.*; class GFG {static int minSum(int A[], int N) {HashMap <Integer, Integer> mp = new HashMap <Integer, Integer> (); int sum = 0; for(int i = 0; i <N; i ++) {sum += A [i]; if(mp.containsKey(A [i])) {mp.pu...
  PREDICTION: public class Solution { ↵     public int minSumAfterDeletion(int[] arr) { ↵         // Implement the logic to find the minimum sum after deletion ↵         // Example implementation:  ↵         // int minSum = Integer.MA...
  METRICS   : primary_success=False | codebleu=0.6446 | csr_score=0.5556 | failure_category=java_compile_error

[Task: T2 | Natural Language -> Java]
  INPUT     : Maximum difference between a pair of adjacent elements by excluding every element once | Function to calculate maximum difference between adjacent elements excluding every array element once ; Traverse the array ; Stores...
  REFERENCE : import java.util.*; class GFG {static void maxAdjacent(int[] arr, int N) {ArrayList <Integer> res = new ArrayList <Integer> (); for(int i = 1; i <N - 1; i ++) {int prev = arr [0]; int maxi = Integer.MIN_VALUE; for(int j ...
  PREDICTION: public class MaxDifferenceCalculator { ↵     public static int[] calculateMaxDifference(int[] arr) { ↵         if (arr == null || arr.length < 2) { ↵             throw new IllegalArgumentException("Array must contain at ...
  METRICS   : primary_success=False | codebleu=0.6610 | csr_score=0.8889 | failure_category=java_compile_error

[Task: T3 | Python -> Java]
  INPUT     : def minSum(A, N): ↵     mp = {} ↵     sum = 0 ↵     for i in range(N): ↵         sum += A[i] ↵         if A[i] in mp: ↵             mp[A[i]] += 1 ↵         else: ↵             mp[A[i]] = 1 ↵     minSum = float('inf') ↵  ...
  REFERENCE : import java.util.*; class GFG {static int minSum(int A[], int N) {HashMap <Integer, Integer> mp = new HashMap <Integer, Integer> (); int sum = 0; for(int i = 0; i <N; i ++) {sum += A [i]; if(mp.containsKey(A [i])) {mp.pu...
  PREDICTION: public class MinSum { ↵     public static int minSum(int[] A, int N) { ↵         Map<Integer, Integer> mp = new HashMap<>(); ↵         int sum = 0; ↵         for (int i = 0; i < N; i++) { ↵             sum += A[i]; ↵    ...
  METRICS   : primary_success=False | codebleu=0.8718 | csr_score=1.0000 | failure_category=java_compile_error

[Task: T3 | Python -> Java]
  INPUT     : def maxAdjacent(arr, N): ↵     res = [] ↵     for i in range(1, N - 1): ↵         prev = arr[0] ↵         maxi = - 1 * float('inf') ↵         for j in range(1, N): ↵             if(i == j): ↵                 continue ↵  ...
  REFERENCE : import java.util.*; class GFG {static void maxAdjacent(int[] arr, int N) {ArrayList <Integer> res = new ArrayList <Integer> (); for(int i = 1; i <N - 1; i ++) {int prev = arr [0]; int maxi = Integer.MIN_VALUE; for(int j ...
  PREDICTION: public class MaxAdjacent { ↵     public static void main(String[] args) { ↵         int[] arr = {1, 3, 4, 7, 8}; ↵         int N = arr.length; ↵          ↵         int[] result = new int[N]; ↵          ↵         for (int...
  METRICS   : primary_success=True | codebleu=0.8889 | csr_score=0.8750 | failure_category=ok

[Task: T4 | Java -> Python]
  INPUT     : import java.util.*; class GFG {static int minSum(int A[], int N) {HashMap <Integer, Integer> mp = new HashMap <Integer, Integer> (); int sum = 0; for(int i = 0; i <N; i ++) {sum += A [i]; if(mp.containsKey(A [i])) {mp.pu...
  REFERENCE : def minSum(A, N): ↵     mp = {} ↵     sum = 0 ↵     for i in range(N): ↵         sum += A[i] ↵         if A[i] in mp: ↵             mp[A[i]] += 1 ↵         else: ↵             mp[A[i]] = 1 ↵     minSum = float('inf') ↵  ...
  PREDICTION: def min_sum(A, N): ↵     # Create a dictionary to store the frequency of each element ↵     mp = {} ↵     total_sum = 0 ↵      ↵     # Iterate through the array to calculate the sum of elements ↵     for i in range(N): ↵...
  METRICS   : primary_success=True | codebleu=0.5739 | csr_score=1.0000 | failure_category=ok

[Task: T4 | Java -> Python]
  INPUT     : import java.util.*; class GFG {static void maxAdjacent(int[] arr, int N) {ArrayList <Integer> res = new ArrayList <Integer> (); for(int i = 1; i <N - 1; i ++) {int prev = arr [0]; int maxi = Integer.MIN_VALUE; for(int j ...
  REFERENCE : def maxAdjacent(arr, N): ↵     res = [] ↵     for i in range(1, N - 1): ↵         prev = arr[0] ↵         maxi = - 1 * float('inf') ↵         for j in range(1, N): ↵             if(i == j): ↵                 continue ↵  ...
  PREDICTION: def max_adjacent(arr, N): ↵     res = [] ↵     for i in range(1, N - 1): ↵         prev = arr[0] ↵         maxi = float('-inf') ↵         for j in range(1, N): ↵             if i == j: ↵                 continue ↵       ...
  METRICS   : primary_success=True | codebleu=0.9231 | csr_score=1.0000 | failure_category=ok

[Task: T5 | Python -> Natural Language]
  INPUT     : def minSum(A, N): ↵     mp = {} ↵     sum = 0 ↵     for i in range(N): ↵         sum += A[i] ↵         if A[i] in mp: ↵             mp[A[i]] += 1 ↵         else: ↵             mp[A[i]] = 1 ↵     minSum = float('inf') ↵  ...
  REFERENCE : Minimum sum possible by removing all occurrences of any array element | Function to find minimum sum after deletion ; Stores frequency of array elements ; Traverse the array ; Calculate sum ; Update frequency of the curr...
  PREDICTION: The function `minSum` takes two parameters: an array `A` of integers and an integer `N`. It calculates the minimum sum of a subarray of length `N` in the array `A`. The function uses a dictionary `mp` to count the occurr...
  METRICS   : csr_score=0.5385 | rouge_l=0.1699 | sacrebleu=1.7047 | failure_category=ok

[Task: T5 | Python -> Natural Language]
  INPUT     : def maxAdjacent(arr, N): ↵     res = [] ↵     for i in range(1, N - 1): ↵         prev = arr[0] ↵         maxi = - 1 * float('inf') ↵         for j in range(1, N): ↵             if(i == j): ↵                 continue ↵  ...
  REFERENCE : Maximum difference between a pair of adjacent elements by excluding every element once | Function to calculate maximum difference between adjacent elements excluding every array element once ; Traverse the array ; Stores...
  PREDICTION: The function `maxAdjacent` takes an array `arr` and its length `N` as input. It iterates over the array, calculating the maximum absolute difference between consecutive elements. For each element, it checks if it is the ...
  METRICS   : csr_score=0.6000 | rouge_l=0.1569 | sacrebleu=0.7294 | failure_category=ok

[Task: T6 | Java -> Natural Language]
  INPUT     : import java.util.*; class GFG {static int minSum(int A[], int N) {HashMap <Integer, Integer> mp = new HashMap <Integer, Integer> (); int sum = 0; for(int i = 0; i <N; i ++) {sum += A [i]; if(mp.containsKey(A [i])) {mp.pu...
  REFERENCE : Minimum sum possible by removing all occurrences of any array element | Function to find minimum sum after deletion ; Stores frequency of array elements ; Traverse the array ; Calculate sum ; Update frequency of the curr...
  PREDICTION: The task is to find the minimum sum of a subarray in an array of integers. The subarray must be non-empty and contain at least one element. The function `minSum` takes two parameters: an array of integers `A` and its len...
  METRICS   : csr_score=0.5385 | rouge_l=0.1750 | sacrebleu=1.1723 | failure_category=ok

[Task: T6 | Java -> Natural Language]
  INPUT     : import java.util.*; class GFG {static void maxAdjacent(int[] arr, int N) {ArrayList <Integer> res = new ArrayList <Integer> (); for(int i = 1; i <N - 1; i ++) {int prev = arr [0]; int maxi = Integer.MIN_VALUE; for(int j ...
  REFERENCE : Maximum difference between a pair of adjacent elements by excluding every element once | Function to calculate maximum difference between adjacent elements excluding every array element once ; Traverse the array ; Stores...
  PREDICTION: The task is to find the maximum adjacent difference between any two elements in an array. The function `maxAdjacent` takes an array of integers and its length as input. It iterates through the array, comparing each eleme...
  METRICS   : csr_score=0.6000 | rouge_l=0.1762 | sacrebleu=1.0367 | failure_category=ok

======================================================================


======================================================================
  FAILURE ANALYSIS [BASELINE]
======================================================================

Overall (60 predictions):
  ok                      :   45 (75.0%)
  java_compile_error      :   11 (18.3%)
  python_syntax_error     :    4 (6.7%)

Per task:
  T1: ok=7  python_syntax_error=3
  T2: java_compile_error=6  ok=4
  T3: java_compile_error=5  ok=5
  T4: ok=9  python_syntax_error=1
  T5: ok=10
  T6: ok=10

======================================================================


====================================================================
BASELINE Evaluation Summary  [v2.4]
====================================================================
Evaluated Examples          : 60
Prediction Logs             : outputs/evaluation/baseline_prediction_logs.jsonl
Metric Rows                 : outputs/evaluation/baseline_metric_rows.jsonl
Summary CSV                 : /content/drive/MyDrive/RepoCoderStudio/outputs/evaluation/baseline_summary.csv
====================================================================

Baseline Summary:

,task_id,model_type,source_modality,target_modality,num_examples,primary_success,python_parse_success,java_compile_success,official_codebleu,codebleu,codebleu_lite,csr_score,csr_similarity,sacrebleu,rouge_l,semantic_similarity,prediction_empty
0,T1,baseline,Natural Language,Python,10,0.7,0.7,NaN,NaN,0.391010,0.391010,0.538727,0.538727,NaN,NaN,NaN,0.0
1,T2,baseline,Natural Language,Java,10,0.4,NaN,0.4,NaN,0.636490,0.636490,0.809762,0.809762,NaN,NaN,NaN,0.0
2,T3,baseline,Python,Java,10,0.5,NaN,0.5,NaN,0.815425,0.815425,0.838889,0.838889,NaN,NaN,NaN,0.0
3,T4,baseline,Java,Python,10,0.9,0.9,NaN,NaN,0.811594,0.811594,0.860000,0.860000,NaN,NaN,NaN,0.0
4,T5,baseline,Python,Natural Language,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.497212,0.167657,0.586510,0.0
5,T6,baseline,Java,Natural Language,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.621005,0.159869,0.570606,0.0

In [16]:
# ============================================================
# 17A. Save Baseline Evaluation  [v2.6]
# ============================================================

import json
import pickle
from pathlib import Path

import pandas as pd

from src.logger import SectionPrinter, SummaryPrinter

SectionPrinter.header("Save Baseline Evaluation  [v2.6]")

project_root = CONFIG.storage.project_root()

baseline_dir = (
    project_root
    / CONFIG.storage.outputs_dir
    / "evaluation"
    / "baseline"
)

baseline_dir.mkdir(parents=True, exist_ok=True)


def save_pickle(name, obj):
    with open(baseline_dir / f"{name}.pkl", "wb") as f:
        pickle.dump(obj, f)


saved = []

# --------------------------------------------------
# Save dataframes
# --------------------------------------------------

for var in [
    "baseline_results_df",
    "baseline_summary_df",
    "baseline_predictions_df",
]:

    if var in globals():

        df = globals()[var]

        if isinstance(df, pd.DataFrame):
            df.to_csv(
                baseline_dir / f"{var}.csv",
                index=False,
            )

        save_pickle(var, df)
        saved.append(var)

# --------------------------------------------------
# Save python objects
# --------------------------------------------------

for var in [
    "baseline_results",
    "baseline_summary",
]:

    if var in globals():

        save_pickle(var, globals()[var])
        saved.append(var)

# --------------------------------------------------
# Metadata
# --------------------------------------------------

metadata = {

    "prompt_version":
        CONFIG.experiment.prompt_version,

    "task_contract_version":
        CONFIG.experiment.task_contract_version,

    "training_manifest_version":
        CONFIG.experiment.training_manifest_version,

    "student_model":
        CONFIG.models.student_model_name,

    "evaluation":
        "baseline",

}

with open(
    baseline_dir / "baseline_metadata.json",
    "w",
    encoding="utf-8",
) as f:

    json.dump(metadata, f, indent=2)

SummaryPrinter.print_summary(
    "Baseline Saved",
    {
        "Directory": str(baseline_dir),
        "Artifacts": len(saved),
    },
)

====================================================================
Save Baseline Evaluation  [v2.6]
====================================================================

====================================================================
Baseline Saved
====================================================================
Directory                   : /content/drive/MyDrive/RepoCoderStudio/outputs/evaluation/baseline
Artifacts                   : 1
====================================================================

In [10]:
# ============================================================
# 17B. Load Baseline Evaluation  [v2.6]
# ============================================================

import json
import pickle
from pathlib import Path

import pandas as pd

from src.logger import SectionPrinter, SummaryPrinter

SectionPrinter.header("Load Baseline Evaluation  [v2.6]")

project_root = CONFIG.storage.project_root()

baseline_dir = (
    project_root
    / CONFIG.storage.outputs_dir
    / "evaluation"
    / "baseline"
)

assert baseline_dir.exists(), "Saved baseline directory not found."


def load_pickle(name):

    path = baseline_dir / f"{name}.pkl"

    if path.exists():

        with open(path, "rb") as f:
            return pickle.load(f)

    return None


# --------------------------------------------------
# Restore DataFrames
# --------------------------------------------------

baseline_results_df = None
baseline_summary_df = None
baseline_predictions_df = None

if (baseline_dir / "baseline_results_df.csv").exists():
    baseline_results_df = pd.read_csv(
        baseline_dir / "baseline_results_df.csv"
    )

if (baseline_dir / "baseline_summary_df.csv").exists():
    baseline_summary_df = pd.read_csv(
        baseline_dir / "baseline_summary_df.csv"
    )

if (baseline_dir / "baseline_predictions_df.csv").exists():
    baseline_predictions_df = pd.read_csv(
        baseline_dir / "baseline_predictions_df.csv"
    )

# --------------------------------------------------
# Restore Python Objects
# --------------------------------------------------

baseline_results = load_pickle("baseline_results")
baseline_summary = load_pickle("baseline_summary")

metadata = json.load(
    open(
        baseline_dir / "baseline_metadata.json",
        "r",
        encoding="utf-8",
    )
)

SummaryPrinter.print_summary(
    "Baseline Loaded",
    {
        "Prompt Version":
            metadata["prompt_version"],

        "Task Contract":
            metadata["task_contract_version"],

        "Rows":
            len(baseline_results_df)
            if baseline_results_df is not None
            else 0,

        "Tasks":
            baseline_summary_df["task_id"].nunique()
            if baseline_summary_df is not None
            else 0,
    },
)

====================================================================
Load Baseline Evaluation  [v2.6]
====================================================================

====================================================================
Baseline Loaded
====================================================================
Prompt Version              : prompt_contract_v2.6
Task Contract               : task_contract_v2.6
Rows                        : 0
Tasks                       : 6
====================================================================

In [11]:
# ============================================================
# 18. Checkpoint Status
# ============================================================

import sys
import importlib

for module_name in list(sys.modules.keys()):
    if module_name == "src" or module_name.startswith("src."):
        del sys.modules[module_name]

importlib.invalidate_caches()

from src.checkpoint_manager import CheckpointManager
from src.logger import SectionPrinter

SectionPrinter.header("Checkpoint Status")

checkpoint_manager = CheckpointManager(CONFIG)
checkpoint_manager.print_status()

====================================================================
Checkpoint Status
====================================================================

====================================================================
Checkpoint Manager Summary
====================================================================
Checkpoint Dir              : /content/drive/MyDrive/RepoCoderStudio/outputs/checkpoints
Latest Checkpoint           : None
Final Adapter Dir           : /content/drive/MyDrive/RepoCoderStudio/outputs/adapters/RepoCoderStudio_CombinedStage_LoRA_v1_0
====================================================================

In [12]:
# ============================================================
# 19. Combined Stage LoRA Training  [v2.5]
# ============================================================

import gc
import torch

from src.trainer import RepoCoderTrainer
from src.logger import SectionPrinter

SectionPrinter.header("Combined Stage LoRA Training")

# Clear GPU memory before loading the student model
gc.collect()

if torch.cuda.is_available():
    torch.cuda.empty_cache()
    torch.cuda.ipc_collect()

repocoder_trainer = RepoCoderTrainer(CONFIG)

trainer = repocoder_trainer.train(
    train_dataset=train_dataset,
    validation_dataset=validation_dataset,
)

# Keep these references for later save/load/evaluation blocks
trained_trainer = trainer
trained_model = trainer.model
trained_tokenizer = repocoder_trainer.tokenizer

print("Training completed.")

====================================================================
Combined Stage LoRA Training
====================================================================

====================================================================
LoRA Training  [v2.5]
====================================================================

====================================================================
Loading Student Model
====================================================================

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/659 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/988M [00:00<?, ?B/s]

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

generation_config.json:   0%|          | 0.00/243 [00:00<?, ?B/s]

16:16:48 | INFO     | RepoCoderStudio.Main | Loaded model: Qwen/Qwen2.5-Coder-0.5B-Instruct

====================================================================
Preparing LoRA Model
====================================================================
trainable params: 4,399,104 || all params: 498,431,872 || trainable%: 0.8826

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_deprecation.py:100: FutureWarning: Deprecated argument(s) used in '__init__': dataset_text_field, max_seq_length. Will not be supported from version '1.0.0'.

Deprecated positional argument(s) used in SFTTrainer, please use the SFTConfig to set these arguments instead.
  warnings.warn(message, FutureWarning)
/usr/local/lib/python3.12/dist-packages/trl/trainer/sft_trainer.py:283: UserWarning: You passed a `max_seq_length` argument to the SFTTrainer, the value you passed will override the one in the `SFTConfig`.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/trl/trainer/sft_trainer.py:321: UserWarning: You passed a `dataset_text_field` argument to the SFTTrainer, the value you passed will override the one in the `SFTConfig`.
  warnings.warn(

Map:   0%|          | 0/1776 [00:00<?, ? examples/s]

16:16:53 | INFO     | RepoCoderStudio.Main | No checkpoint found. Training will start fresh.

/usr/local/lib/python3.12/dist-packages/accelerate/accelerator.py:494: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = torch.cuda.amp.GradScaler(**kwargs)
/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:1263: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. Starting in PyTorch 2.9, calling checkpoint without use_reentrant will raise an exception. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:1263: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. Starting in PyTorch 2.9, calling checkpoint without use_reentrant will raise an exception. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:1263: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. Starting in PyTorch 2.9, calling checkpoint without use_reentrant will raise an exception. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:1263: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. Starting in PyTorch 2.9, calling checkpoint without use_reentrant will raise an exception. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:1263: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. Starting in PyTorch 2.9, calling checkpoint without use_reentrant will raise an exception. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

====================================================================
Training Summary  [v2.5]
====================================================================
Train Rows                  : 1776
Validation Rows             : 342
Final Adapter               : /content/drive/MyDrive/RepoCoderStudio/outputs/adapters/RepoCoderStudio_CombinedStage_LoRA_v1_0
Training History            : /content/drive/MyDrive/RepoCoderStudio/outputs/reports/training_history.csv
Training Summary            : /content/drive/MyDrive/RepoCoderStudio/outputs/reports/training_summary.json
Eval During Training        : Disabled
====================================================================
Training completed.

In [13]:
# ============================================================
# 19A. Save Final Trained LoRA Adapter  [v2.6]
# ============================================================

import json
import shutil
import time
from pathlib import Path

from src.logger import SectionPrinter, SummaryPrinter

SectionPrinter.header("Save Final Trained LoRA Adapter  [v2.6]")

project_root = CONFIG.storage.project_root()

model_dir = (
    project_root
    / CONFIG.storage.outputs_dir
    / "trained_model"
)

if model_dir.exists():
    shutil.rmtree(model_dir)

model_dir.mkdir(parents=True, exist_ok=True)

# Save LoRA adapter
trainer.model.save_pretrained(model_dir)

# Save tokenizer from RepoCoderTrainer wrapper
repocoder_trainer.tokenizer.save_pretrained(model_dir)

manifest = {
    "manifest_version": "trained_lora_adapter_v2.6",
    "created_at": time.strftime("%Y-%m-%d %H:%M:%S"),
    "base_model": CONFIG.models.student_model_name,
    "adapter_directory": str(model_dir),
    "prompt_version": CONFIG.experiment.prompt_version,
    "task_contract_version": CONFIG.experiment.task_contract_version,
    "training_manifest_version": CONFIG.experiment.training_manifest_version,
    "train_rows": len(train_dataset),
    "validation_rows": len(validation_dataset),
    "test_rows": len(test_dataset),
    "lora_rank": CONFIG.training.lora_rank,
    "lora_alpha": CONFIG.training.lora_alpha,
    "lora_dropout": CONFIG.training.lora_dropout,
    "learning_rate": CONFIG.training.learning_rate,
}

with open(model_dir / "trained_model_manifest.json", "w", encoding="utf-8") as f:
    json.dump(manifest, f, indent=2)

SummaryPrinter.print_summary(
    "Final LoRA Adapter Saved",
    {
        "Directory": str(model_dir),
        "Base Model": manifest["base_model"],
        "Prompt Version": manifest["prompt_version"],
        "Train Rows": manifest["train_rows"],
    },
)

====================================================================
Save Final Trained LoRA Adapter  [v2.6]
====================================================================

====================================================================
Final LoRA Adapter Saved
====================================================================
Directory                   : /content/drive/MyDrive/RepoCoderStudio/outputs/trained_model
Base Model                  : Qwen/Qwen2.5-Coder-0.5B-Instruct
Prompt Version              : prompt_contract_v2.6
Train Rows                  : 1776
====================================================================

In [14]:
# ============================================================
# 19B. Load Saved Fine-Tuned LoRA Adapter  [v2.6]
# ============================================================

import json
import gc
import torch

from peft import PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

from src.logger import SectionPrinter, SummaryPrinter

SectionPrinter.header("Load Saved Fine-Tuned LoRA Adapter  [v2.6]")

project_root = CONFIG.storage.project_root()

model_dir = (
    project_root
    / CONFIG.storage.outputs_dir
    / "trained_model"
)

assert model_dir.exists(), f"Saved trained model not found: {model_dir}"

manifest_path = model_dir / "trained_model_manifest.json"
assert manifest_path.exists(), f"Missing trained model manifest: {manifest_path}"

with open(manifest_path, "r", encoding="utf-8") as f:
    trained_model_manifest = json.load(f)

gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()
    torch.cuda.ipc_collect()

bnb_config = None
if CONFIG.models.use_4bit and torch.cuda.is_available():
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.float16,
        bnb_4bit_use_double_quant=True,
    )

base_model_kwargs = {
    "trust_remote_code": True,
    "device_map": "auto",
}

if bnb_config is not None:
    base_model_kwargs["quantization_config"] = bnb_config
elif torch.cuda.is_available():
    base_model_kwargs["torch_dtype"] = torch.float16

base_model = AutoModelForCausalLM.from_pretrained(
    trained_model_manifest["base_model"],
    **base_model_kwargs,
)

tokenizer = AutoTokenizer.from_pretrained(
    model_dir,
    trust_remote_code=True,
)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

tokenizer.padding_side = "right"

model = PeftModel.from_pretrained(
    base_model,
    model_dir,
    is_trainable=False,
)

model.eval()

# Standard variable names expected by later evaluation cells
finetuned_model = model
finetuned_tokenizer = tokenizer
trained_model = model
trained_tokenizer = tokenizer

SummaryPrinter.print_summary(
    "Fine-Tuned LoRA Adapter Loaded",
    {
        "Adapter Directory": str(model_dir),
        "Base Model": trained_model_manifest["base_model"],
        "Prompt Version": trained_model_manifest.get("prompt_version"),
        "Task Contract": trained_model_manifest.get("task_contract_version"),
        "Train Rows": trained_model_manifest.get("train_rows"),
    },
)

====================================================================
Load Saved Fine-Tuned LoRA Adapter  [v2.6]
====================================================================

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

====================================================================
Fine-Tuned LoRA Adapter Loaded
====================================================================
Adapter Directory           : /content/drive/MyDrive/RepoCoderStudio/outputs/trained_model
Base Model                  : Qwen/Qwen2.5-Coder-0.5B-Instruct
Prompt Version              : prompt_contract_v2.6
Task Contract               : task_contract_v2.6
Train Rows                  : 1776
====================================================================

In [15]:
# ============================================================
# 20. Fine-tuned Evaluation  [v2 — Modular Pipeline]
# ============================================================

import sys
import importlib

for module_name in list(sys.modules.keys()):
    if module_name == "src" or module_name.startswith("src."):
        del sys.modules[module_name]

importlib.invalidate_caches()

from src.config import CONFIG
from src.evaluator import EvaluationEngine
from src.logger import SectionPrinter

SectionPrinter.header("Fine-tuned Evaluation: LoRA Adapter  [v2]")

finetuned_evaluator = EvaluationEngine(CONFIG)

finetuned_prediction_logs, finetuned_metric_rows, finetuned_summary_df = finetuned_evaluator.evaluate(
    test_dataset=test_dataset,
    model_type="finetuned",
    max_examples_per_task=CONFIG.evaluation.demo_eval_examples_per_task,
    print_inspection=True,
    print_failures=True,
)

print("\nFine-tuned Summary:")
display(finetuned_summary_df)

16:33:37 | INFO     | RepoCoderStudio.Main | Tree-sitter Java grammar loaded (v2 structural analysis active).

====================================================================
Fine-tuned Evaluation: LoRA Adapter  [v2]
====================================================================

====================================================================
FINETUNED Evaluation  [v2.4]
====================================================================
16:33:40 | INFO     | RepoCoderStudio.Main | Loading base model: Qwen/Qwen2.5-Coder-0.5B-Instruct
16:33:43 | INFO     | RepoCoderStudio.Main | Loading LoRA adapter from /content/drive/MyDrive/RepoCoderStudio/outputs/adapters/RepoCoderStudio_CombinedStage_LoRA_v1_0
16:33:44 | INFO     | RepoCoderStudio.Main | [finetuned] 1/60 | T1

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading extra modules: 0.00B [00:00, ?B/s]

Downloading extra modules: 0.00B [00:00, ?B/s]

Downloading extra modules: 0.00B [00:00, ?B/s]

Downloading extra modules: 0.00B [00:00, ?B/s]

Downloading extra modules: 0.00B [00:00, ?B/s]

Downloading extra modules: 0.00B [00:00, ?B/s]

Downloading extra modules: 0.00B [00:00, ?B/s]

Downloading extra modules: 0.00B [00:00, ?B/s]

Downloading data:   0%|          | 0.00/917 [00:00<?, ?B/s]

Downloaded keywords to /root/.cache/huggingface/metrics/codebleu/default/downloads/extracted/67c115902ce4a05b395e29085b24f9706ff8a253b83cb2505a8d9d9cef445aea

Downloading data:   0%|          | 0.00/3.00M [00:00<?, ?B/s]

Downloaded languages.so to /root/.cache/huggingface/metrics/codebleu/default/downloads/46aff845b03a4565a25afbb505e64d45b6c12ef6546d66630b2dc81989359af1
16:34:15 | INFO     | RepoCoderStudio.Main | Official CodeBLEU metric available via evaluate/dvitel/codebleu.
16:34:16 | WARNING  | RepoCoderStudio.Main | Official CodeBLEU failed once and will be disabled for the rest of this run. lang=python; reason=Fraction.__new__() got an unexpected keyword argument '_normalize'
16:34:16 | INFO     | RepoCoderStudio.Main | [finetuned] 2/60 | T1
16:34:30 | INFO     | RepoCoderStudio.Main | [finetuned] 3/60 | T1
16:34:52 | INFO     | RepoCoderStudio.Main | [finetuned] 4/60 | T1
16:35:14 | INFO     | RepoCoderStudio.Main | [finetuned] 5/60 | T1
16:35:28 | INFO     | RepoCoderStudio.Main | [finetuned] 6/60 | T1
16:35:48 | INFO     | RepoCoderStudio.Main | [finetuned] 7/60 | T1
16:36:01 | INFO     | RepoCoderStudio.Main | [finetuned] 8/60 | T1
16:36:22 | INFO     | RepoCoderStudio.Main | [finetuned] 9/60 | T1
16:36:34 | INFO     | RepoCoderStudio.Main | [finetuned] 10/60 | T1
16:36:46 | INFO     | RepoCoderStudio.Main | [finetuned] 11/60 | T2
16:37:34 | INFO     | RepoCoderStudio.Main | [finetuned] 12/60 | T2

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

16:38:22 | INFO     | RepoCoderStudio.Main | [finetuned] 13/60 | T2

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

16:39:10 | INFO     | RepoCoderStudio.Main | [finetuned] 14/60 | T2

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

16:39:30 | INFO     | RepoCoderStudio.Main | [finetuned] 15/60 | T2

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

16:39:58 | INFO     | RepoCoderStudio.Main | [finetuned] 16/60 | T2

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

16:40:19 | INFO     | RepoCoderStudio.Main | [finetuned] 17/60 | T2

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

16:40:36 | INFO     | RepoCoderStudio.Main | [finetuned] 18/60 | T2

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

16:41:05 | INFO     | RepoCoderStudio.Main | [finetuned] 19/60 | T2

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

16:41:23 | INFO     | RepoCoderStudio.Main | [finetuned] 20/60 | T2

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

16:41:34 | INFO     | RepoCoderStudio.Main | [finetuned] 21/60 | T3

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

16:41:57 | INFO     | RepoCoderStudio.Main | [finetuned] 22/60 | T3

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

16:42:18 | INFO     | RepoCoderStudio.Main | [finetuned] 23/60 | T3

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

16:42:48 | INFO     | RepoCoderStudio.Main | [finetuned] 24/60 | T3

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

16:43:09 | INFO     | RepoCoderStudio.Main | [finetuned] 25/60 | T3

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

16:43:38 | INFO     | RepoCoderStudio.Main | [finetuned] 26/60 | T3

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

16:43:58 | INFO     | RepoCoderStudio.Main | [finetuned] 27/60 | T3

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

16:44:17 | INFO     | RepoCoderStudio.Main | [finetuned] 28/60 | T3

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

16:44:53 | INFO     | RepoCoderStudio.Main | [finetuned] 29/60 | T3

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

16:45:13 | INFO     | RepoCoderStudio.Main | [finetuned] 30/60 | T3

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

16:45:23 | INFO     | RepoCoderStudio.Main | [finetuned] 31/60 | T4

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

16:45:40 | INFO     | RepoCoderStudio.Main | [finetuned] 32/60 | T4
16:45:56 | INFO     | RepoCoderStudio.Main | [finetuned] 33/60 | T4
16:46:25 | INFO     | RepoCoderStudio.Main | [finetuned] 34/60 | T4
16:46:50 | INFO     | RepoCoderStudio.Main | [finetuned] 35/60 | T4
16:47:15 | INFO     | RepoCoderStudio.Main | [finetuned] 36/60 | T4
16:47:31 | INFO     | RepoCoderStudio.Main | [finetuned] 37/60 | T4
16:47:47 | INFO     | RepoCoderStudio.Main | [finetuned] 38/60 | T4
16:48:17 | INFO     | RepoCoderStudio.Main | [finetuned] 39/60 | T4
16:48:36 | INFO     | RepoCoderStudio.Main | [finetuned] 40/60 | T4
16:48:43 | INFO     | RepoCoderStudio.Main | [finetuned] 41/60 | T5

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

16:48:59 | INFO     | RepoCoderStudio.Main | [finetuned] 42/60 | T5

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

16:49:46 | INFO     | RepoCoderStudio.Main | [finetuned] 43/60 | T5
16:50:34 | INFO     | RepoCoderStudio.Main | [finetuned] 44/60 | T5
16:51:21 | INFO     | RepoCoderStudio.Main | [finetuned] 45/60 | T5
16:52:08 | INFO     | RepoCoderStudio.Main | [finetuned] 46/60 | T5
16:52:56 | INFO     | RepoCoderStudio.Main | [finetuned] 47/60 | T5
16:53:03 | INFO     | RepoCoderStudio.Main | [finetuned] 48/60 | T5
16:53:49 | INFO     | RepoCoderStudio.Main | [finetuned] 49/60 | T5
16:54:36 | INFO     | RepoCoderStudio.Main | [finetuned] 50/60 | T5
16:55:24 | INFO     | RepoCoderStudio.Main | [finetuned] 51/60 | T6
16:56:11 | INFO     | RepoCoderStudio.Main | [finetuned] 52/60 | T6
16:56:22 | INFO     | RepoCoderStudio.Main | [finetuned] 53/60 | T6
16:57:09 | INFO     | RepoCoderStudio.Main | [finetuned] 54/60 | T6
16:57:23 | INFO     | RepoCoderStudio.Main | [finetuned] 55/60 | T6
16:58:10 | INFO     | RepoCoderStudio.Main | [finetuned] 56/60 | T6
16:58:57 | INFO     | RepoCoderStudio.Main | [finetuned] 57/60 | T6
16:59:45 | INFO     | RepoCoderStudio.Main | [finetuned] 58/60 | T6
17:00:31 | INFO     | RepoCoderStudio.Main | [finetuned] 59/60 | T6
17:01:19 | INFO     | RepoCoderStudio.Main | [finetuned] 60/60 | T6
17:02:06 | INFO     | RepoCoderStudio.Main | Saved JSONL: /content/drive/MyDrive/RepoCoderStudio/outputs/evaluation/finetuned_prediction_logs.jsonl (60 rows)
17:02:06 | INFO     | RepoCoderStudio.Main | Saved JSONL: /content/drive/MyDrive/RepoCoderStudio/outputs/evaluation/finetuned_metric_rows.jsonl (60 rows)

======================================================================
  PREDICTION INSPECTION [FINETUNED]
======================================================================

[Task: T1 | Natural Language -> Python]
  INPUT     : Minimum sum possible by removing all occurrences of any array element | Function to find minimum sum after deletion ; Stores frequency of array elements ; Traverse the array ; Calculate sum ; Update frequency of the curr...
  REFERENCE : def minSum(A, N): ↵     mp = {} ↵     sum = 0 ↵     for i in range(N): ↵         sum += A[i] ↵         if A[i] in mp: ↵             mp[A[i]] += 1 ↵         else: ↵             mp[A[i]] = 1 ↵     minSum = float('inf') ↵  ...
  PREDICTION: def minSum(arr, n): ↵     freq = [0] * 100001 ↵     for i in range(n): ↵         freq[arr[i]] += 1 ↵     sum = 0 ↵     for i in range(n): ↵         sum += arr[i] ↵     for i in range(100001): ↵         freq[i] += freq[i ...
  METRICS   : primary_success=True | codebleu=0.7887 | csr_score=0.9091 | failure_category=ok

[Task: T1 | Natural Language -> Python]
  INPUT     : Maximum difference between a pair of adjacent elements by excluding every element once | Function to calculate maximum difference between adjacent elements excluding every array element once ; Traverse the array ; Stores...
  REFERENCE : def maxAdjacent(arr, N): ↵     res = [] ↵     for i in range(1, N - 1): ↵         prev = arr[0] ↵         maxi = - 1 * float('inf') ↵         for j in range(1, N): ↵             if(i == j): ↵                 continue ↵  ...
  PREDICTION: def maxDiff(arr, n): ↵     max_diff = 0 ↵     prev = arr[0] ↵     for i in range(1, n): ↵         if(arr[i] > prev): ↵             max_diff = max(max_diff, arr[i] - prev) ↵         prev = arr[i] ↵     return max_diff ↵ i...
  METRICS   : primary_success=True | codebleu=0.6479 | csr_score=0.8889 | failure_category=ok

[Task: T2 | Natural Language -> Java]
  INPUT     : Minimum sum possible by removing all occurrences of any array element | Function to find minimum sum after deletion ; Stores frequency of array elements ; Traverse the array ; Calculate sum ; Update frequency of the curr...
  REFERENCE : import java.util.*; class GFG {static int minSum(int A[], int N) {HashMap <Integer, Integer> mp = new HashMap <Integer, Integer> (); int sum = 0; for(int i = 0; i <N; i ++) {sum += A [i]; if(mp.containsKey(A [i])) {mp.pu...
  PREDICTION: import java.util.*; class GFG {static int minSum(int arr[], int n) {Map <Integer, Integer> map = new HashMap <Integer, Integer> (); for(int i = 0; i <n; i ++) {map.put(arr [i], map.getOrDefault(arr [i], 0) + 1);} int sum...
  METRICS   : primary_success=True | codebleu=0.7385 | csr_score=1.0000 | failure_category=ok

[Task: T2 | Natural Language -> Java]
  INPUT     : Maximum difference between a pair of adjacent elements by excluding every element once | Function to calculate maximum difference between adjacent elements excluding every array element once ; Traverse the array ; Stores...
  REFERENCE : import java.util.*; class GFG {static void maxAdjacent(int[] arr, int N) {ArrayList <Integer> res = new ArrayList <Integer> (); for(int i = 1; i <N - 1; i ++) {int prev = arr [0]; int maxi = Integer.MIN_VALUE; for(int j ...
  PREDICTION: import java.util.*; class GFG {static void maxDiff(int arr[], int n) {int max = Integer.MIN_VALUE; for(int i = 0; i <n; i ++) {if(arr [i] > max) {max = arr [i];}} for(int i = 0; i <n; i ++) {if(max - arr [i] > max) {max ...
  METRICS   : primary_success=True | codebleu=0.6891 | csr_score=0.8750 | failure_category=ok

[Task: T3 | Python -> Java]
  INPUT     : def minSum(A, N): ↵     mp = {} ↵     sum = 0 ↵     for i in range(N): ↵         sum += A[i] ↵         if A[i] in mp: ↵             mp[A[i]] += 1 ↵         else: ↵             mp[A[i]] = 1 ↵     minSum = float('inf') ↵  ...
  REFERENCE : import java.util.*; class GFG {static int minSum(int A[], int N) {HashMap <Integer, Integer> mp = new HashMap <Integer, Integer> (); int sum = 0; for(int i = 0; i <N; i ++) {sum += A [i]; if(mp.containsKey(A [i])) {mp.pu...
  PREDICTION: import java.util.*; class GFG {static int minSum(int arr[], int N) {Map <Integer, Integer> mp = new HashMap <> (); int sum = 0; for(int i = 0; i <N; i ++) {sum += arr [i]; if(mp.containsKey(arr [i])) {mp.put(arr [i], mp....
  METRICS   : primary_success=False | codebleu=0.9672 | csr_score=1.0000 | failure_category=java_compile_error

[Task: T3 | Python -> Java]
  INPUT     : def maxAdjacent(arr, N): ↵     res = [] ↵     for i in range(1, N - 1): ↵         prev = arr[0] ↵         maxi = - 1 * float('inf') ↵         for j in range(1, N): ↵             if(i == j): ↵                 continue ↵  ...
  REFERENCE : import java.util.*; class GFG {static void maxAdjacent(int[] arr, int N) {ArrayList <Integer> res = new ArrayList <Integer> (); for(int i = 1; i <N - 1; i ++) {int prev = arr [0]; int maxi = Integer.MIN_VALUE; for(int j ...
  PREDICTION: class GFG {static void maxAdjacent(int arr[], int N) {for(int i = 1; i <N - 1; i ++) {int prev = arr [0]; int maxi = - 1 * Integer.MAX_VALUE; for(int j = 1; j <N; j ++) {if(i == j) continue; maxi = Math.max(maxi, Math.ab...
  METRICS   : primary_success=False | codebleu=0.8972 | csr_score=0.8750 | failure_category=java_compile_error

[Task: T4 | Java -> Python]
  INPUT     : import java.util.*; class GFG {static int minSum(int A[], int N) {HashMap <Integer, Integer> mp = new HashMap <Integer, Integer> (); int sum = 0; for(int i = 0; i <N; i ++) {sum += A [i]; if(mp.containsKey(A [i])) {mp.pu...
  REFERENCE : def minSum(A, N): ↵     mp = {} ↵     sum = 0 ↵     for i in range(N): ↵         sum += A[i] ↵         if A[i] in mp: ↵             mp[A[i]] += 1 ↵         else: ↵             mp[A[i]] = 1 ↵     minSum = float('inf') ↵  ...
  PREDICTION: def minSum(A, N): ↵     mp = {} ↵     sum = 0 ↵     for i in range(N): ↵         sum += A[i] ↵         if(A[i] in mp): ↵             mp[A[i]] += 1 ↵         else: ↵             mp[A[i]] = 1 ↵     minSum = float('inf') ↵ ...
  METRICS   : primary_success=True | codebleu=0.8974 | csr_score=1.0000 | failure_category=ok

[Task: T4 | Java -> Python]
  INPUT     : import java.util.*; class GFG {static void maxAdjacent(int[] arr, int N) {ArrayList <Integer> res = new ArrayList <Integer> (); for(int i = 1; i <N - 1; i ++) {int prev = arr [0]; int maxi = Integer.MIN_VALUE; for(int j ...
  REFERENCE : def maxAdjacent(arr, N): ↵     res = [] ↵     for i in range(1, N - 1): ↵         prev = arr[0] ↵         maxi = - 1 * float('inf') ↵         for j in range(1, N): ↵             if(i == j): ↵                 continue ↵  ...
  PREDICTION: def maxAdjacent(arr, N): ↵     res = [] ↵     for i in range(1, N - 1): ↵         prev = arr[0] ↵         maxi = float('inf') ↵         for j in range(1, N): ↵             if(i == j): ↵                 continue ↵        ...
  METRICS   : primary_success=True | codebleu=0.9867 | csr_score=1.0000 | failure_category=ok

[Task: T5 | Python -> Natural Language]
  INPUT     : def minSum(A, N): ↵     mp = {} ↵     sum = 0 ↵     for i in range(N): ↵         sum += A[i] ↵         if A[i] in mp: ↵             mp[A[i]] += 1 ↵         else: ↵             mp[A[i]] = 1 ↵     minSum = float('inf') ↵  ...
  REFERENCE : Minimum sum possible by removing all occurrences of any array element | Function to find minimum sum after deletion ; Stores frequency of array elements ; Traverse the array ; Calculate sum ; Update frequency of the curr...
  PREDICTION: Minimum sum of array elements after removing at most one element | Function to return the minimum sum ; Create a map to store the frequency of each element ; Calculate the sum of the array ; Traverse the map ; Update the...
  METRICS   : csr_score=0.5385 | rouge_l=0.5370 | sacrebleu=19.6700 | failure_category=ok

[Task: T5 | Python -> Natural Language]
  INPUT     : def maxAdjacent(arr, N): ↵     res = [] ↵     for i in range(1, N - 1): ↵         prev = arr[0] ↵         maxi = - 1 * float('inf') ↵         for j in range(1, N): ↵             if(i == j): ↵                 continue ↵  ...
  REFERENCE : Maximum difference between a pair of adjacent elements by excluding every element once | Function to calculate maximum difference between adjacent elements excluding every array element once ; Traverse the array ; Stores...
  PREDICTION: Maximum absolute difference between adjacent elements in an array | Function to return the maximum absolute difference between adjacent elements ; Stores the result ; Iterate through the array ; If the current element is...
  METRICS   : csr_score=0.6000 | rouge_l=0.1635 | sacrebleu=3.3613 | failure_category=ok

[Task: T6 | Java -> Natural Language]
  INPUT     : import java.util.*; class GFG {static int minSum(int A[], int N) {HashMap <Integer, Integer> mp = new HashMap <Integer, Integer> (); int sum = 0; for(int i = 0; i <N; i ++) {sum += A [i]; if(mp.containsKey(A [i])) {mp.pu...
  REFERENCE : Minimum sum possible by removing all occurrences of any array element | Function to find minimum sum after deletion ; Stores frequency of array elements ; Traverse the array ; Calculate sum ; Update frequency of the curr...
  PREDICTION: Minimum sum of array elements after removing some elements | Python3 implementation of the approach ; Function to return the minimum sum of array elements after removing some elements ; Map to store the frequency of each...
  METRICS   : csr_score=0.5385 | rouge_l=0.1628 | sacrebleu=4.2112 | failure_category=ok

[Task: T6 | Java -> Natural Language]
  INPUT     : import java.util.*; class GFG {static void maxAdjacent(int[] arr, int N) {ArrayList <Integer> res = new ArrayList <Integer> (); for(int i = 1; i <N - 1; i ++) {int prev = arr [0]; int maxi = Integer.MIN_VALUE; for(int j ...
  REFERENCE : Maximum difference between a pair of adjacent elements by excluding every element once | Function to calculate maximum difference between adjacent elements excluding every array element once ; Traverse the array ; Stores...
  PREDICTION: Maximum difference between consecutive elements in an array | Python3 implementation of the approach ; Function to return the maximum difference between consecutive elements in the array ; To store the result ; Traverse ...
  METRICS   : csr_score=0.6000 | rouge_l=0.4062 | sacrebleu=19.4991 | failure_category=ok

======================================================================


======================================================================
  FAILURE ANALYSIS [FINETUNED]
======================================================================

Overall (60 predictions):
  ok                      :   52 (86.7%)
  java_compile_error      :    7 (11.7%)
  python_syntax_error     :    1 (1.7%)

Per task:
  T1: ok=10
  T2: ok=8  java_compile_error=2
  T3: java_compile_error=5  ok=5
  T4: ok=9  python_syntax_error=1
  T5: ok=10
  T6: ok=10

======================================================================


====================================================================
FINETUNED Evaluation Summary  [v2.4]
====================================================================
Evaluated Examples          : 60
Prediction Logs             : outputs/evaluation/finetuned_prediction_logs.jsonl
Metric Rows                 : outputs/evaluation/finetuned_metric_rows.jsonl
Summary CSV                 : /content/drive/MyDrive/RepoCoderStudio/outputs/evaluation/finetuned_summary.csv
====================================================================

Fine-tuned Summary:

,task_id,model_type,source_modality,target_modality,num_examples,primary_success,python_parse_success,java_compile_success,official_codebleu,codebleu,codebleu_lite,csr_score,csr_similarity,sacrebleu,rouge_l,semantic_similarity,prediction_empty
0,T1,finetuned,Natural Language,Python,10,1.0,1.0,NaN,NaN,0.736965,0.736965,0.869636,0.869636,NaN,NaN,NaN,0.0
1,T2,finetuned,Natural Language,Java,10,0.8,NaN,0.8,NaN,0.773736,0.773736,0.865714,0.865714,NaN,NaN,NaN,0.0
2,T3,finetuned,Python,Java,10,0.5,NaN,0.5,NaN,0.940181,0.940181,0.929167,0.929167,NaN,NaN,NaN,0.0
3,T4,finetuned,Java,Python,10,0.9,0.9,NaN,NaN,0.924830,0.924830,0.870909,0.870909,NaN,NaN,NaN,0.0
4,T5,finetuned,Python,Natural Language,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.818618,0.315327,0.699047,0.0
5,T6,finetuned,Java,Natural Language,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.594768,0.317001,0.669257,0.0

In [16]:
# ============================================================
# 21. Per-task Baseline vs Fine-tuned Comparison
# ============================================================

from src.comparison_engine import ComparisonEngine
from src.storage import ProjectStorageManager
from src.logger import SectionPrinter, SummaryPrinter

SectionPrinter.header("Per-task Baseline vs Fine-tuned Comparison")

comparison_engine = ComparisonEngine()

comparison_df = comparison_engine.compare(
    baseline_summary_df,
    finetuned_summary_df,
)

display(comparison_df)

per_task_tables = comparison_engine.per_task_tables(
    comparison_df,
)

storage = ProjectStorageManager(CONFIG)

storage.save_csv(
    comparison_df,
    "outputs/evaluation/baseline_vs_finetuned_comparison.csv",
)

for task_id, table in per_task_tables.items():
    print("\n" + "=" * 70)
    print(f"Task {task_id} Comparison")
    print("=" * 70)
    display(table)

    storage.save_csv(
        table,
        f"outputs/evaluation/per_task_comparison_{task_id}.csv",
    )

SummaryPrinter.print_summary(
    "Per-task Comparison Summary",
    {
        "Compared Tasks": len(per_task_tables),
        "Combined CSV": "outputs/evaluation/baseline_vs_finetuned_comparison.csv",
        "Per-task CSV Dir": "outputs/evaluation/",
    },
)

====================================================================
Per-task Baseline vs Fine-tuned Comparison
====================================================================

,baseline_task_id,baseline_model_type,baseline_source_modality,baseline_target_modality,baseline_num_examples,baseline_primary_success,baseline_python_parse_success,baseline_java_compile_success,baseline_official_codebleu,baseline_codebleu,...,delta_csr_score,delta_sacrebleu,delta_prediction_empty,delta_codebleu,delta_csr_similarity,delta_semantic_similarity,delta_num_examples,delta_primary_success,delta_java_compile_success,delta_rouge_l
0,T1,baseline,Natural Language,Python,10,0.7,0.7,NaN,NaN,0.391010,...,0.330909,NaN,0.0,0.345955,0.330909,NaN,0,0.3,NaN,NaN
1,T2,baseline,Natural Language,Java,10,0.4,NaN,0.4,NaN,0.636490,...,0.055952,NaN,0.0,0.137246,0.055952,NaN,0,0.4,0.4,NaN
2,T3,baseline,Python,Java,10,0.5,NaN,0.5,NaN,0.815425,...,0.090278,NaN,0.0,0.124756,0.090278,NaN,0,0.0,0.0,NaN
3,T4,baseline,Java,Python,10,0.9,0.9,NaN,NaN,0.811594,...,0.010909,NaN,0.0,0.113236,0.010909,NaN,0,0.0,NaN,NaN
4,T5,baseline,Python,Natural Language,10,NaN,NaN,NaN,NaN,NaN,...,NaN,8.321407,0.0,NaN,NaN,0.112538,0,NaN,NaN,0.147669
5,T6,baseline,Java,Natural Language,10,NaN,NaN,NaN,NaN,NaN,...,NaN,7.973764,0.0,NaN,NaN,0.098651,0,NaN,NaN,0.157132

17:02:56 | INFO     | RepoCoderStudio.Main | Saved CSV: /content/drive/MyDrive/RepoCoderStudio/outputs/evaluation/baseline_vs_finetuned_comparison.csv (6 rows)

======================================================================
Task T1 Comparison
======================================================================

                  metric   baseline  fine_tuned     delta  primary
0           num_examples  10.000000   10.000000  0.000000    False
1        primary_success   0.700000    1.000000  0.300000    False
2   python_parse_success   0.700000    1.000000  0.300000     True
3   java_compile_success        NaN         NaN       NaN    False
4      official_codebleu        NaN         NaN       NaN    False
5               codebleu   0.391010    0.736965  0.345955    False
6          codebleu_lite   0.391010    0.736965  0.345955    False
7              csr_score   0.538727    0.869636  0.330909    False
8         csr_similarity   0.538727    0.869636  0.330909    False
9              sacrebleu        NaN         NaN       NaN    False
10               rouge_l        NaN         NaN       NaN    False
11   semantic_similarity        NaN         NaN       NaN    False
12      prediction_empty   0.000000    0.000000  0.000000    False

17:02:56 | INFO     | RepoCoderStudio.Main | Saved CSV: /content/drive/MyDrive/RepoCoderStudio/outputs/evaluation/per_task_comparison_T1.csv (13 rows)

======================================================================
Task T2 Comparison
======================================================================

                  metric   baseline  fine_tuned     delta  primary
0           num_examples  10.000000   10.000000  0.000000    False
1        primary_success   0.400000    0.800000  0.400000    False
2   python_parse_success        NaN         NaN       NaN    False
3   java_compile_success   0.400000    0.800000  0.400000     True
4      official_codebleu        NaN         NaN       NaN    False
5               codebleu   0.636490    0.773736  0.137246    False
6          codebleu_lite   0.636490    0.773736  0.137246    False
7              csr_score   0.809762    0.865714  0.055952    False
8         csr_similarity   0.809762    0.865714  0.055952    False
9              sacrebleu        NaN         NaN       NaN    False
10               rouge_l        NaN         NaN       NaN    False
11   semantic_similarity        NaN         NaN       NaN    False
12      prediction_empty   0.000000    0.000000  0.000000    False

17:02:56 | INFO     | RepoCoderStudio.Main | Saved CSV: /content/drive/MyDrive/RepoCoderStudio/outputs/evaluation/per_task_comparison_T2.csv (13 rows)

======================================================================
Task T3 Comparison
======================================================================

                  metric   baseline  fine_tuned     delta  primary
0           num_examples  10.000000   10.000000  0.000000    False
1        primary_success   0.500000    0.500000  0.000000    False
2   python_parse_success        NaN         NaN       NaN    False
3   java_compile_success   0.500000    0.500000  0.000000     True
4      official_codebleu        NaN         NaN       NaN    False
5               codebleu   0.815425    0.940181  0.124756    False
6          codebleu_lite   0.815425    0.940181  0.124756    False
7              csr_score   0.838889    0.929167  0.090278    False
8         csr_similarity   0.838889    0.929167  0.090278    False
9              sacrebleu        NaN         NaN       NaN    False
10               rouge_l        NaN         NaN       NaN    False
11   semantic_similarity        NaN         NaN       NaN    False
12      prediction_empty   0.000000    0.000000  0.000000    False

17:02:56 | INFO     | RepoCoderStudio.Main | Saved CSV: /content/drive/MyDrive/RepoCoderStudio/outputs/evaluation/per_task_comparison_T3.csv (13 rows)

======================================================================
Task T4 Comparison
======================================================================

                  metric   baseline  fine_tuned     delta  primary
0           num_examples  10.000000   10.000000  0.000000    False
1        primary_success   0.900000    0.900000  0.000000    False
2   python_parse_success   0.900000    0.900000  0.000000     True
3   java_compile_success        NaN         NaN       NaN    False
4      official_codebleu        NaN         NaN       NaN    False
5               codebleu   0.811594    0.924830  0.113236    False
6          codebleu_lite   0.811594    0.924830  0.113236    False
7              csr_score   0.860000    0.870909  0.010909    False
8         csr_similarity   0.860000    0.870909  0.010909    False
9              sacrebleu        NaN         NaN       NaN    False
10               rouge_l        NaN         NaN       NaN    False
11   semantic_similarity        NaN         NaN       NaN    False
12      prediction_empty   0.000000    0.000000  0.000000    False

17:02:56 | INFO     | RepoCoderStudio.Main | Saved CSV: /content/drive/MyDrive/RepoCoderStudio/outputs/evaluation/per_task_comparison_T4.csv (13 rows)

======================================================================
Task T5 Comparison
======================================================================

                  metric   baseline  fine_tuned     delta  primary
0           num_examples  10.000000   10.000000  0.000000    False
1        primary_success        NaN         NaN       NaN    False
2   python_parse_success        NaN         NaN       NaN    False
3   java_compile_success        NaN         NaN       NaN    False
4      official_codebleu        NaN         NaN       NaN    False
5               codebleu        NaN         NaN       NaN    False
6          codebleu_lite        NaN         NaN       NaN    False
7              csr_score        NaN         NaN       NaN    False
8         csr_similarity        NaN         NaN       NaN    False
9              sacrebleu   1.497212    9.818618  8.321407    False
10               rouge_l   0.167657    0.315327  0.147669     True
11   semantic_similarity   0.586510    0.699047  0.112538    False
12      prediction_empty   0.000000    0.000000  0.000000    False

17:02:56 | INFO     | RepoCoderStudio.Main | Saved CSV: /content/drive/MyDrive/RepoCoderStudio/outputs/evaluation/per_task_comparison_T5.csv (13 rows)

======================================================================
Task T6 Comparison
======================================================================

                  metric   baseline  fine_tuned     delta  primary
0           num_examples  10.000000   10.000000  0.000000    False
1        primary_success        NaN         NaN       NaN    False
2   python_parse_success        NaN         NaN       NaN    False
3   java_compile_success        NaN         NaN       NaN    False
4      official_codebleu        NaN         NaN       NaN    False
5               codebleu        NaN         NaN       NaN    False
6          codebleu_lite        NaN         NaN       NaN    False
7              csr_score        NaN         NaN       NaN    False
8         csr_similarity        NaN         NaN       NaN    False
9              sacrebleu   1.621005    9.594768  7.973764    False
10               rouge_l   0.159869    0.317001  0.157132     True
11   semantic_similarity   0.570606    0.669257  0.098651    False
12      prediction_empty   0.000000    0.000000  0.000000    False

17:02:56 | INFO     | RepoCoderStudio.Main | Saved CSV: /content/drive/MyDrive/RepoCoderStudio/outputs/evaluation/per_task_comparison_T6.csv (13 rows)

====================================================================
Per-task Comparison Summary
====================================================================
Compared Tasks              : 6
Combined CSV                : outputs/evaluation/baseline_vs_finetuned_comparison.csv
Per-task CSV Dir            : outputs/evaluation/
====================================================================

In [24]:
# ============================================================
# 21A. Report-Style Overall Outcome Table
# ============================================================

import pandas as pd

from src.storage import ProjectStorageManager
from src.logger import SectionPrinter, SummaryPrinter

SectionPrinter.header("Report-Style Overall Outcome Table")

overall_outcome_table = pd.DataFrame([
    {
        "Task": "T1: Natural Language → Python",
        "Baseline": "70%",
        "Fine-Tuned": "100%",
        "Observation": (
            "Significant improvement in executable Python generation; "
            "Python parse success reached 100%."
        ),
    },
    {
        "Task": "T2: Natural Language → Java",
        "Baseline": "40%",
        "Fine-Tuned": "80%",
        "Observation": (
            "Java compilation success doubled after fine-tuning, with "
            "corresponding improvements in CodeBLEU-lite and CSR."
        ),
    },
    {
        "Task": "T3: Python → Java",
        "Baseline": "50%",
        "Fine-Tuned": "50%",
        "Observation": (
            "Primary compilation success remained unchanged, but translation "
            "quality improved substantially because CodeBLEU-lite and CSR increased."
        ),
    },
    {
        "Task": "T4: Java → Python",
        "Baseline": "90%",
        "Fine-Tuned": "90%",
        "Observation": (
            "Primary success remained stable while translation quality improved, "
            "showing refinement without regression."
        ),
    },
    {
        "Task": "T5: Python → Natural Language",
        "Baseline": "Improved",
        "Fine-Tuned": "Improved",
        "Observation": (
            "ROUGE-L, SacreBLEU, and semantic similarity all increased, "
            "producing clearer program explanations."
        ),
    },
    {
        "Task": "T6: Java → Natural Language",
        "Baseline": "Improved",
        "Fine-Tuned": "Improved",
        "Observation": (
            "Consistent improvements across all text-generation metrics, "
            "indicating better natural language summarization of Java programs."
        ),
    },
])

display(overall_outcome_table)

storage = ProjectStorageManager(CONFIG)

storage.save_csv(
    overall_outcome_table,
    "outputs/evaluation/report_overall_outcome_table.csv",
)

# Optional Markdown export for direct copy into report
markdown_path = (
    CONFIG.storage.project_root()
    / CONFIG.storage.outputs_dir
    / "evaluation"
    / "report_overall_outcome_table.md"
)

markdown_path.parent.mkdir(parents=True, exist_ok=True)

with open(markdown_path, "w", encoding="utf-8") as f:
    f.write("### Table: Overall Baseline vs Fine-Tuned Performance Across Tasks\n\n")
    f.write(overall_outcome_table.to_markdown(index=False))

SummaryPrinter.print_summary(
    "Report-Style Overall Outcome Table",
    {
        "Rows": len(overall_outcome_table),
        "CSV": "outputs/evaluation/report_overall_outcome_table.csv",
        "Markdown": "outputs/evaluation/report_overall_outcome_table.md",
    },
)

====================================================================
Report-Style Overall Outcome Table
====================================================================

,Task,Baseline,Fine-Tuned,Observation
0,T1: Natural Language → Python,70%,100%,Significant improvement in executable Python g...
1,T2: Natural Language → Java,40%,80%,Java compilation success doubled after fine-tu...
2,T3: Python → Java,50%,50%,Primary compilation success remained unchanged...
3,T4: Java → Python,90%,90%,Primary success remained stable while translat...
4,T5: Python → Natural Language,Improved,Improved,"ROUGE-L, SacreBLEU, and semantic similarity al..."
5,T6: Java → Natural Language,Improved,Improved,Consistent improvements across all text-genera...

17:36:11 | INFO     | RepoCoderStudio.Main | Saved CSV: /content/drive/MyDrive/RepoCoderStudio/outputs/evaluation/report_overall_outcome_table.csv (6 rows)

====================================================================
Report-Style Overall Outcome Table
====================================================================
Rows                        : 6
CSV                         : outputs/evaluation/report_overall_outcome_table.csv
Markdown                    : outputs/evaluation/report_overall_outcome_table.md
====================================================================

In [19]:
# ============================================================
# 22. Failure Analytics
# ============================================================

import pandas as pd

from src.failure_analyzer import FailureAnalyzer
from src.storage import ProjectStorageManager
from src.logger import SectionPrinter, SummaryPrinter

SectionPrinter.header("Failure Analytics")

storage = ProjectStorageManager(CONFIG)
failure_analyzer = FailureAnalyzer()

project_root = CONFIG.storage.project_root()

baseline_metrics_path = (
    project_root
    / CONFIG.storage.outputs_dir
    / "evaluation"
    / "baseline_metric_rows.jsonl"
)

finetuned_metrics_path = (
    project_root
    / CONFIG.storage.outputs_dir
    / "evaluation"
    / "finetuned_metric_rows.jsonl"
)

# ------------------------------------------------------------
# Load metric rows from memory or disk
# ------------------------------------------------------------

if "baseline_metric_rows" in globals():
    baseline_rows = baseline_metric_rows
elif baseline_metrics_path.exists():
    baseline_rows = pd.read_json(baseline_metrics_path, lines=True).to_dict("records")
else:
    raise FileNotFoundError(f"Missing baseline metric rows: {baseline_metrics_path}")

if "finetuned_metric_rows" in globals():
    finetuned_rows = finetuned_metric_rows
elif finetuned_metrics_path.exists():
    finetuned_rows = pd.read_json(finetuned_metrics_path, lines=True).to_dict("records")
else:
    raise FileNotFoundError(f"Missing fine-tuned metric rows: {finetuned_metrics_path}")

# ------------------------------------------------------------
# Analyze
# ------------------------------------------------------------

baseline_failure_df = failure_analyzer.analyze(baseline_rows)
finetuned_failure_df = failure_analyzer.analyze(finetuned_rows)

print("Baseline failure analytics:")
display(baseline_failure_df)

print("\nFine-tuned failure analytics:")
display(finetuned_failure_df)

# ------------------------------------------------------------
# Save
# ------------------------------------------------------------

storage.save_csv(
    baseline_failure_df,
    "outputs/evaluation/baseline_failure_analytics.csv",
)

storage.save_csv(
    finetuned_failure_df,
    "outputs/evaluation/finetuned_failure_analytics.csv",
)

SummaryPrinter.print_summary(
    "Failure Analytics Summary",
    {
        "Baseline Rows": len(baseline_failure_df),
        "Fine-tuned Rows": len(finetuned_failure_df),
        "Baseline CSV": "outputs/evaluation/baseline_failure_analytics.csv",
        "Fine-tuned CSV": "outputs/evaluation/finetuned_failure_analytics.csv",
    },
)

====================================================================
Failure Analytics
====================================================================
Baseline failure analytics:

,task_id,corpus_id,source_modality,target_modality,prediction_empty,raw_prediction,prompt_version,prompt_hash,response_header,official_codebleu,...,csr_similarity,scored_prediction,python_error,model_type,failure_category,java_compile_success,compile_error,sacrebleu,rouge_l,semantic_similarity
0,T1,xlcost_6347b5fff72f6575,Natural Language,Python,False,```python\ndef min_sum_after_deletion(arr):\n ...,prompt_contract_v2.6,69fe5435efaa060d9c53024e92985af2513a6b290a6b6b...,### Python,NaN,...,0.909091,def min_sum_after_deletion(arr):\n frequenc...,NaN,baseline,ok,NaN,NaN,NaN,NaN,NaN
1,T1,xlcost_9a7dde477f883166,Natural Language,Python,False,```python\ndef max_adjacent_diff(arr):\n # ...,prompt_contract_v2.6,07fc47816a577f19df74941bada51bbc58da33b9aa21dd...,### Python,NaN,...,0.888889,def max_adjacent_diff(arr):\n # Initialize ...,NaN,baseline,ok,NaN,NaN,NaN,NaN,NaN
2,T1,xlcost_fc06c07fb09820e8,Natural Language,Python,False,```python\ndef findSize(N):\n if N <= 1:\n ...,prompt_contract_v2.6,f47b9edee7630755a53997fdb2af914d22e63cab132257...,### Python,NaN,...,0.875000,def findSize(N):\n if N <= 1:\n retu...,NaN,baseline,ok,NaN,NaN,NaN,NaN,NaN
3,T1,xlcost_1a4bdacec5a19fef,Natural Language,Python,False,"```python\ndef lcm(a, b):\n return abs(a*b)...",prompt_contract_v2.6,4d70310330229c2ad1d54ff18a39a82a5ffc8fc4dc5718...,### Python,NaN,...,0.700000,"def lcm(a, b):\n return abs(a*b) // gcd(a, ...",NaN,baseline,ok,NaN,NaN,NaN,NaN,NaN
4,T1,xlcost_8fc31d09b3c0a1ac,Natural Language,Python,False,```python\ndef landau(n):\n # Implement the...,prompt_contract_v2.6,83d97b4f43eaab022b471bfdc44b3d4012e47e0cfaf61b...,### Python,NaN,...,0.000000,,empty_python_code,baseline,low_similarity,NaN,NaN,NaN,NaN,NaN
5,T1,xlcost_869c824b5762d30d,Natural Language,Python,False,"```python\ndef is_prime(n):\n """"""Check if a...",prompt_contract_v2.6,4c2e460a2e9a2343290dde0bdcdd49679dfdb63a23b1c3...,### Python,NaN,...,0.000000,,empty_python_code,baseline,low_similarity,NaN,NaN,NaN,NaN,NaN
6,T1,xlcost_61a7ef8a73562d47,Natural Language,Python,False,```python\ndef split_array_into_k_odd_subsets(...,prompt_contract_v2.6,fef0dbd16ec45e0b78c5ee4fd890e5b65a24ef1b62d691...,### Python,NaN,...,0.400000,"def split_array_into_k_odd_subsets(arr, k):\n ...",NaN,baseline,ok,NaN,NaN,NaN,NaN,NaN
7,T1,xlcost_c1e17f9a3ac4e7fd,Natural Language,Python,False,```python\ndef compute_division_pairs(arr):\n ...,prompt_contract_v2.6,75b1c67b14207b07f2eb76f8f12aa7f910fb59a086a016...,### Python,NaN,...,0.000000,,empty_python_code,baseline,low_similarity,NaN,NaN,NaN,NaN,NaN
8,T1,xlcost_3247abc5f496b107,Natural Language,Python,False,```python\ndef array_sum_xor(arr):\n xor_su...,prompt_contract_v2.6,a41097b5228436d1f14204fe43be62ff0193d15c6949b0...,### Python,NaN,...,0.900000,def array_sum_xor(arr):\n xor_sum = 0\n ...,NaN,baseline,ok,NaN,NaN,NaN,NaN,NaN
9,T1,xlcost_ffa450b09b8b2d9a,Natural Language,Python,False,"```python\ndef is_reciprocal_of_roots(a, b, c)...",prompt_contract_v2.6,f662116e2db0aa9eddf363a3df9784a8d3f51a2c9cf20f...,### Python,NaN,...,0.714286,"def is_reciprocal_of_roots(a, b, c):\n # Ch...",NaN,baseline,ok,NaN,NaN,NaN,NaN,NaN
10,T2,xlcost_6347b5fff72f6575,Natural Language,Java,False,```java\npublic class Solution {\n public i...,prompt_contract_v2.6,654c3090a225e99c3c87b45f6682090b227af2f30ab62c...,### Java,NaN,...,0.555556,public class Solution {\n public int minSum...,NaN,baseline,ok,0.0,/tmp/tmpzrb4sna6/Solution.java:12: error: miss...,NaN,NaN,NaN
11,T2,xlcost_9a7dde477f883166,Natural Language,Java,False,```java\npublic class MaxDifferenceCalculator ...,prompt_contract_v2.6,36610d838018973e3804cbc073d6b38982335cd13b479e...,### Java,NaN,...,0.888889,public class MaxDifferenceCalculator {\n pu...,NaN,baseline,ok,0.0,/tmp/tmpeemtxqfs/MaxDifferenceCalculator.java:...,NaN,NaN,NaN
12,T2,xlcost_fc06c07fb09820e8,Natural Language,Java,False,```java\npublic class Solution {\n public i...,prompt_contract_v2.6,2b982ee7401ef8f2b02cde25cb03898038e80c96db3b12...,### Java,NaN,...,0.714286,public class Solution {\n public int findSi...,NaN,baseline,ok,0.0,/tmp/tmpm5a81f5q/Solution.java:32: error: miss...,NaN,NaN,NaN
13,T2,xlcost_1a4bdacec5a19fef,Natural Language,Java,False,```java\npublic class PrimeFactorization {\n ...,prompt_contract_v2.6,c283d527eabad761c4ecca86285e0d7345b00a26bd070a...,### Java,NaN,...,1.000000,public class PrimeFactorization {\n public ...,NaN,baseline,ok,1.0,,NaN,NaN,NaN
14,T2,xlcost_8fc31d09b3c0a1ac,Natural Language,Java,False,```java\npublic class Landau {\n public sta...,prompt_contract_v2.6,cecc217fd1e2d894e071efd71b3e0fd03de31ceb707eb3...,### Java,NaN,...,0.500000,public class Landau {\n public static int l...,NaN,baseline,ok,1.0,,NaN,NaN,NaN
15,T2,xlcost_869c824b5762d30d,Natural Language,Java,False,```java\npublic class PrimeChecker {\n publ...,prompt_contract_v2.6,10d84a583c27364750061d5e34ff55f8224a7b9cfc727e...,### Java,NaN,...,1.000000,public class PrimeChecker {\n public static...,NaN,baseline,ok,1.0,,NaN,NaN,NaN
16,T2,xlcost_61a7ef8a73562d47,Natural Language,Java,False,```java\npublic class OddSubsetSplitter {\n ...,prompt_contract_v2.6,3e07aa2353476d6ce4f3a3fa38723b9aad32a41c749835...,### Java,NaN,...,0.875000,public class OddSubsetSplitter {\n public s...,NaN,baseline,ok,0.0,/tmp/tmpioiye0y8/OddSubsetSplitter.java:22: er...,NaN,NaN,NaN
17,T2,xlcost_c1e17f9a3ac4e7fd,Natural Language,Java,False,```java\nimport java.util.HashMap;\nimport jav...,prompt_contract_v2.6,f0f71a81df6149c8f398c3fee18ba0414f7fb45dbdabdb...,### Java,NaN,...,0.888889,import java.util.HashMap;\nimport java.util.Ma...,NaN,baseline,ok,0.0,/tmp/tmpiccvjlui/Main.java:25: error: cannot f...,NaN,NaN,NaN
18,T2,xlcost_3247abc5f496b107,Natural Language,Java,False,```java\npublic class ArrayXOR {\n public s...,prompt_contract_v2.6,9a02e0539485fef57bcbc295a180d0d6e444aba1c80711...,### Java,NaN,...,0.875000,public class ArrayXOR {\n public static voi...,NaN,baseline,ok,0.0,/tmp/tmpzpw21tr_/ArrayXOR.java:20: error: cann...,NaN,NaN,NaN
19,T2,xlcost_ffa450b09b8b2d9a,Natural Language,Java,False,```java\npublic class QuadraticEquation {\n ...,prompt_contract_v2.6,af3f9bcbff19c53ea0c5817085dc9358340c875afa5ccf...,### Java,NaN,...,0.800000,public class QuadraticEquation {\n public s...,NaN,baseline,ok,1.0,,NaN,NaN,NaN
20,T3,xlcost_6347b5fff72f6575,Python,Java,False,```java\npublic class MinSum {\n public sta...,prompt_contract_v2.6,2a99c1589f0859a353ef0ad18aed72f8e8a85a42c618ae...,### Java Translation,NaN,...,1.000000,public class MinSum {\n public static int m...,NaN,baseline,ok,0.0,/tmp/tmp32wq1hdg/MinSum.java:7: error: ')' exp...,NaN,NaN,NaN
21,T3,xlcost_9a7dde477f883166,Python,Java,False,```java\npublic class MaxAdjacent {\n publi...,prompt_contract_v2.6,41d97e6373d06219c9a2d5f0c04f235cf909e8f8927b42...,### Java Translation,NaN,...,0.875000,public class MaxAdjacent {\n public static ...,NaN,baseline,ok,1.0,,NaN,NaN,NaN
22,T3,xlcost_fc06c07fb09820e8,Python,Java,False,```java\npublic class Solution {\n public i...,prompt_contract_v2.6,f30f756ba4544dacdbc3e6c7589ce03b68c0d6360a12d3...,### Java Translation,NaN,...,1.000000,public class Solution {\n public int countO...,NaN,baseline,ok,0.0,/tmp/tmph_5jkui4/Solution.java:13: error: cann...,NaN,NaN,NaN
23,T3,xlcost_1a4bdacec5a19fef,Python,Java,False,```java\npublic class Prime {\n public stat...,prompt_contract_v2.6,90579ccbc7cf5cefea0a58280c66a08362e0b44b8261fa...,### Java Translation,NaN,...,1.000000,public class Prime {\n public static boolea...,NaN,baseline,ok,0.0,/tmp/tmp3lgqbb_f/Prime.java:19: error: no suit...,NaN,NaN,NaN
24,T3,xlcost_8fc31d09b3c0a1ac,Python,Java,False,```java\npublic class LCMFinder {\n public ...,prompt_contract_v2.6,2f4b93cab83844883a9d1ab810a99ab14f7727ed8a2214...,### Java Translation,NaN,...,0.000000,,NaN,baseline,low_similarity,0.0,,NaN,NaN,NaN
25,T3,xlcost_869c824b5762d30d,Python,Java,False,```java\npublic class PrimeChecker {\n publ...,prompt_contract_v2.6,a02803fe4595589de84921fe0f381e17c794e00cbaf630...,### Java Translation,NaN,...,0.750000,public class PrimeChecker {\n public static...,NaN,baseline,ok,1.0,,NaN,NaN,NaN
26,T3,xlcost_61a7ef8a73562d47,Python,Java,False,```java\npublic class ArrayChecker {\n publ...,prompt_contract_v2.6,71bcc0f2f8922f6810073f73323c83d0a2544f4730348f...,### Java Translation,NaN,...,0.875000,public class ArrayChecker {\n public static...,NaN,baseline,ok,1.0,,NaN,NaN,NaN
27,T3,xlcost_c1e17f9a3ac4e7fd,Python,Java,False,```java\nimport java.util.*;\n\npublic class S...,prompt_contract_v2.6,e8988400259a578ce850931233a8ab7096e5cdaf680518...,### Java Translation,NaN,...,0.888889,import java.util.*;\n\npublic class Solution {...,NaN,baseline,ok,0.0,/tmp/tmpf862bn1c/Solution.java:26: error: '.cl...,NaN,NaN,NaN
28,T3,xlcost_3247abc5f496b107,Python,Java,False,```java\npublic class InsertElement {\n pub...,prompt_contract_v2.6,16a83c83fbd1ec8559c8eb4330d34c4e1915277ebec154...,### Java Translation,NaN,...,1.000000,public class InsertElement {\n public stati...,NaN,baseline,ok,1.0,,NaN,NaN,NaN
29,T3,xlcost_ffa450b09b8b2d9a,Python,Java,False,```java\npublic class Solution {\n public s...,prompt_contract_v2.6,18ed936bf002b6b2790220d675e2b351da0d54a0908d1c...,### Java Translation,NaN,...,1.000000,public class Solution {\n public static voi...,NaN,baseline,ok,1.0,,NaN,NaN,NaN
30,T4,xlcost_6347b5fff72f6575,Java,Python,False,"```python\ndef min_sum(A, N):\n # Create a ...",prompt_contract_v2.6,00165a5214eef9dfbdcb5c40f52c0e491dafa26b1d33a3...,### Python Translation,NaN,...,1.000000,"def min_sum(A, N):\n # Create a dictionary ...",NaN,baseline,ok,NaN,NaN,NaN,NaN,NaN
31,T4,xlcost_9a7dde477f883166,Java,Python,False,"```python\ndef max_adjacent(arr, N):\n res ...",prompt_contract_v2.6,e6153a0bdffbbdb87d17385496fd6abd70aa71505d3e33...,### Python Translation,NaN,...,1.000000,"def max_adjacent(arr, N):\n res = []\n f...",NaN,baseline,ok,NaN,NaN,NaN,NaN,NaN
32,T4,xlcost_fc06c07fb09820e8,Java,Python,False,```python\ndef find_size(N):\n if N == 0:\n...,prompt_contract_v2.6,591145a6b725b69e925f540ef35c1e9708b52f385bdd66...,### Python Translation,NaN,...,1.000000,def find_size(N):\n if N == 0:\n ret...,NaN,baseline,ok,NaN,NaN,NaN,NaN,NaN
33,T4,xlcost_1a4bdacec5a19fef,Java,Python,False,```python\ndef is_prime(n):\n if n == 1:\n ...,prompt_contract_v2.6,4f6f941f351ed141e86a74689532756f3a94483c904bb1...,### Python Translation,NaN,...,1.000000,def is_prime(n):\n if n == 1:\n retu...,NaN,baseline,ok,NaN,NaN,NaN,NaN,NaN
34,T4,xlcost_8fc31d09b3c0a1ac,Java,Python,False,```python\ndef find_lcm(arr):\n if len(arr)...,prompt_contract_v2.6,62eee5cbafa91912d222b2f23cbe3f7792f42c20a5249f...,### Python Translation,NaN,...,1.000000,def find_lcm(arr):\n if len(arr) == 0:\n ...,NaN,baseline,ok,NaN,NaN,NaN,NaN,NaN
35,T4,xlcost_869c824b5762d30d,Java,Python,False,```python\ndef is_prime(n):\n if n == 1:\n ...,prompt_contract_v2.6,ffcad1a775097a5e235c82def37b8fd29ab79917e15bcc...,### Python Translation,NaN,...,0.700000,def is_prime(n):\n if n == 1:\n retu...,NaN,baseline,ok,NaN,NaN,NaN,NaN,NaN
36,T4,xlcost_61a7ef8a73562d47,Java,Python,False,"```python\ndef check_array(n, k, arr):\n cn...",prompt_contract_v2.6,1162dbad0f26b4dcae8e593d979fe9a49f822b03933e73...,### Python Translation,NaN,...,1.000000,"def check_array(n, k, arr):\n cnt = 0\n ...",NaN,baseline,ok,NaN,NaN,NaN,NaN,NaN
37,T4,xlcost_c1e17f9a3ac4e7fd,Java,Python,False,"```python\ndef func(arr, n):\n ans = 0\n ...",prompt_contract_v2.6,44f8495208464a9312f65f5f62ef4074d124e9f7b0f8d6...,### Python Translation,NaN,...,0.000000,"def func(arr, n):\n ans = 0\n maxx = 0\n...",SyntaxError('invalid syntax. Perhaps you forgo...,baseline,ok,NaN,NaN,NaN,NaN,NaN
38,T4,xlcost_3247abc5f496b107,Java,Python,False,"```python\ndef insert_element(a, n):\n # In...",prompt_contract_v2.6,24c0c8eed72b7a6e46856ba5002bb5ba1764dd2cbc1fbf...,### Python Translation,NaN,...,0.900000,"def insert_element(a, n):\n # Initialize va...",NaN,baseline,ok,NaN,NaN,NaN,NaN,NaN
39,T4,xlcost_ffa450b09b8b2d9a,Java,Python,False,"```python\ndef check_solution(a, b, c):\n i...",prompt_contract_v2.6,7d0f3765ff357f32ab485501eee641968a248065f13488...,### Python Translation,NaN,...,1.000000,"def check_solution(a, b, c):\n if a == c:\n...",NaN,baseline,ok,NaN,NaN,NaN,NaN,NaN
40,T5,xlcost_6347b5fff72f6575,Python,Natural Language,False,The function `minSum` takes two parameters: an...,prompt_contract_v2.6,892eca7fff5063866d4a717dccfc8fd009d05ea8425981...,### Explanation,NaN,...,NaN,The function `minSum` takes two parameters: an...,NaN,baseline,ok,NaN,NaN,1.704693,0.169935,0.651459
41,T5,xlcost_9a7dde477f883166,Python,Natural Language,False,The function `maxAdjacent` takes an array `arr...,prompt_contract_v2.6,d0b2e895ac4c483c404c650a8455cd9d793a75f516dfe0...,### Explanation,NaN,...,NaN,The function `maxAdjacent` takes an array `arr...,NaN,baseline,ok,NaN,NaN,0.729373,0.156863,0.723045
42,T5,xlcost_fc06c07fb09820e8,Python,Natural Language,False,The task is to count the number of ones in a b...,prompt_contract_v2.6,dec392c55d9338b2baf700f66a65cc4f9c5ebcedf73641...,### Explanation,NaN,...,NaN,The task is to count the number of ones in a b...,NaN,baseline,ok,NaN,NaN,2.786913,0.181818,0.435726
43,T5,xlcost_1a4bdacec5a19fef,Python,Natural Language,False,The task is to find the smallest divisor of a ...,prompt_contract_v2.6,5916c9f4f39987376dddc7b741dbece39c5bf5f463d055...,### Explanation,NaN,...,NaN,The task is to find the smallest divisor of a ...,NaN,baseline,ok,NaN,NaN,1.276045,0.160665,0.680122
44,T5,xlcost_8fc31d09b3c0a1ac,Python,Natural Language,False,The task is to implement a function `findWays`...,prompt_contract_v2.6,20de146b27180146e6d7070053fb29eeeb977792a2a054...,### Explanation,NaN,...,NaN,The task is to implement a function `findWays`...,NaN,baseline,ok,NaN,NaN,0.511175,0.158311,0.624203
45,T5,xlcost_869c824b5762d30d,Python,Natural Language,False,The task is to implement a function `isPrime` ...,prompt_contract_v2.6,1fac6ab109920b4ecb0628fb3cf0c5755241b0324c687a...,### Explanation,NaN,...,NaN,The task is to implement a function `isPrime` ...,NaN,baseline,ok,NaN,NaN,0.948475,0.162712,0.656263
46,T5,xlcost_61a7ef8a73562d47,Python,Natural Language,False,The task is to determine if there are at least...,prompt_contract_v2.6,8b2aa9dad7341912fb877e848fbf8c43a1c0c876a66936...,### Explanation,NaN,...,NaN,The task is to determine if there are at least...,NaN,baseline,ok,NaN,NaN,0.992571,0.153846,0.601953
47,T5,xlcost_c1e17f9a3ac4e7fd,Python,Natural Language,False,The task is to compute the sum of frequencies ...,prompt_contract_v2.6,4dd8e9b707613de7f5b6bcb44bd5ed501e46293e5ee460...,### Explanation,NaN,...,NaN,The task is to compute the sum of frequencies ...,NaN,baseline,ok,NaN,NaN,1.906044,0.144092,0.651968
48,T5,xlcost_3247abc5f496b107,Python,Natural Language,False,The task is to implement a function `insert_el...,prompt_contract_v2.6,42e69c554a35a4cb9597d8ed267bb136be2bac43b86faa...,### Explanation,NaN,...,NaN,The task is to implement a function `insert_el...,NaN,baseline,ok,NaN,NaN,3.927727,0.269608,0.554916
49,T5,xlcost_ffa450b09b8b2d9a,Python,Natural Language,False,The function `checkSolution` takes three argum...,prompt_contract_v2.6,bcff63ba5677ef8528e995165c9aba4dd5863cbcb06266...,### Explanation,NaN,...,NaN,The function `checkSolution` takes three argum...,NaN,baseline,ok,NaN,NaN,0.189099,0.118721,0.285440
50,T6,xlcost_6347b5fff72f6575,Java,Natural Language,False,The task is to find the minimum sum of a subar...,prompt_contract_v2.6,937b8ca34a7cbb6a67c44424e8a410cc58bc8ffa8f35e8...,### Explanation,NaN,...,NaN,The task is to find the minimum sum of a subar...,NaN,baseline,ok,NaN,NaN,1.172258,0.175000,0.748377
51,T6,xlcost_9a7dde477f883166,Java,Natural Language,False,The task is to find the maximum adjacent diffe...,prompt_contract_v2.6,510ba5c6ca7ce4977b0192d31106bab8d0a21f2ee95ee3...,### Explanation,NaN,...,NaN,The task is to find the maximum adjacent diffe...,NaN,baseline,ok,NaN,NaN,1.036719,0.176211,0.621426
52,T6,xlcost_fc06c07fb09820e8,Java,Natural Language,False,The task is to implement a method `CountOnes` ...,prompt_contract_v2.6,2971c1d19da5ce6aa896ed74775754f3e8f1dafd664c20...,### Explanation,NaN,...,NaN,The task is to implement a method `CountOnes` ...,NaN,baseline,ok,NaN,NaN,3.081023,0.184358,0.520782
53,T6,xlcost_1a4bdacec5a19fef,Java,Natural Language,False,The task is to implement a method `minDivisior...,prompt_contract_v2.6,d126c284f3544d0085ad39847563cd3ecee5e42706c28b...,### Explanation,NaN,...,NaN,The task is to implement a method `minDivisior...,NaN,baseline,ok,NaN,NaN,1.511344,0.177083,0.549383
54,T6,xlcost_8fc31d09b3c0a1ac,Java,Natural Language,False,The task is to implement a method `findWays` t...,prompt_contract_v2.6,343345ba125b17c51b4404093ac327327de044ae6d26c7...,### Explanation,NaN,...,NaN,The task is to implement a method `findWays` t...,NaN,baseline,ok,NaN,NaN,0.611271,0.104072,0.485716
55,T6,xlcost_869c824b5762d30d,Java,Natural Language,False,The task is to implement a method `isPrime` in...,prompt_contract_v2.6,6b9e6d95365c07993306e3c3dc70b301ff98603f8adb19...,### Explanation,NaN,...,NaN,The task is to implement a method `isPrime` in...,NaN,baseline,ok,NaN,NaN,0.700023,0.138686,0.604318
56,T6,xlcost_61a7ef8a73562d47,Java,Natural Language,False,The task is to implement a method `checkArray`...,prompt_contract_v2.6,309156335c1cdd0ffed174bd93991fb9510d3f80a267b2...,### Explanation,NaN,...,NaN,The task is to implement a method `checkArray`...,NaN,baseline,ok,NaN,NaN,1.623300,0.126437,0.533235
57,T6,xlcost_c1e17f9a3ac4e7fd,Java,Natural Language,False,The task is to compute the sum of frequencies ...,prompt_contract_v2.6,95150ff283a5ff9b783caea79ff237ce9007375a7f605a...,### Explanation,NaN,...,NaN,The task is to compute the sum of frequencies ...,NaN,baseline,ok,NaN,NaN,2.506129,0.200717,0.624305
58,T6,xlcost_3247abc5f496b107,Java,Natural Language,False,The task is to implement a function `insert_el...,prompt_contract_v2.6,177a917d9c4abc9c8b2898a87cd9031c2d21e2d0a5bbc6...,### Explanation,NaN,...,NaN,The task is to implement a function `insert_el...,NaN,baseline,ok,NaN,NaN,3.704235,0.229167,0.755055
59,T6,xlcost_ffa450b09b8b2d9a,Java,Natural Language,False,The task is to implement a method `checkSoluti...,prompt_contract_v2.6,5a6b914ec9baddd681fdc434a8ba39efe6e0fb4fe8c0da...,### Explanation,NaN,...,NaN,The task is to implement a method `checkSoluti...,NaN,baseline,ok,NaN,NaN,0.263745,0.086957,0.263466

Fine-tuned failure analytics:

,task_id,corpus_id,source_modality,target_modality,prediction_empty,raw_prediction,prompt_version,prompt_hash,response_header,official_codebleu,...,csr_similarity,scored_prediction,python_error,model_type,failure_category,java_compile_success,compile_error,sacrebleu,rouge_l,semantic_similarity
0,T1,xlcost_6347b5fff72f6575,Natural Language,Python,False,"def minSum(arr, n):\n freq = [0] * 100001\n...",prompt_contract_v2.6,69fe5435efaa060d9c53024e92985af2513a6b290a6b6b...,### Python,NaN,...,0.909091,"def minSum(arr, n):\n freq = [0] * 100001\n...",NaN,finetuned,ok,NaN,NaN,NaN,NaN,NaN
1,T1,xlcost_9a7dde477f883166,Natural Language,Python,False,"def maxDiff(arr, n):\n max_diff = 0\n pr...",prompt_contract_v2.6,07fc47816a577f19df74941bada51bbc58da33b9aa21dd...,### Python,NaN,...,0.888889,"def maxDiff(arr, n):\n max_diff = 0\n pr...",NaN,finetuned,ok,NaN,NaN,NaN,NaN,NaN
2,T1,xlcost_fc06c07fb09820e8,Natural Language,Python,False,def findSize(N):\n if(N == 1):\n ret...,prompt_contract_v2.6,f47b9edee7630755a53997fdb2af914d22e63cab132257...,### Python,NaN,...,0.875000,def findSize(N):\n if(N == 1):\n ret...,NaN,finetuned,ok,NaN,NaN,NaN,NaN,NaN
3,T1,xlcost_1a4bdacec5a19fef,Natural Language,Python,False,def isPrime(n):\n if(n <= 1):\n retu...,prompt_contract_v2.6,4d70310330229c2ad1d54ff18a39a82a5ffc8fc4dc5718...,### Python,NaN,...,0.700000,def isPrime(n):\n if(n <= 1):\n retu...,NaN,finetuned,ok,NaN,NaN,NaN,NaN,NaN
4,T1,xlcost_8fc31d09b3c0a1ac,Natural Language,Python,False,"def gcd(a, b):\n while(b):\n a, b = ...",prompt_contract_v2.6,83d97b4f43eaab022b471bfdc44b3d4012e47e0cfaf61b...,### Python,NaN,...,0.700000,"def gcd(a, b):\n while(b):\n a, b = ...",NaN,finetuned,ok,NaN,NaN,NaN,NaN,NaN
5,T1,xlcost_869c824b5762d30d,Natural Language,Python,False,def isPrime(n):\n if(n <= 1):\n retu...,prompt_contract_v2.6,4c2e460a2e9a2343290dde0bdcdd49679dfdb63a23b1c3...,### Python,NaN,...,1.000000,def isPrime(n):\n if(n <= 1):\n retu...,NaN,finetuned,ok,NaN,NaN,NaN,NaN,NaN
6,T1,xlcost_61a7ef8a73562d47,Natural Language,Python,False,"def canSplit(arr, n, k):\n odd = 0\n for...",prompt_contract_v2.6,fef0dbd16ec45e0b78c5ee4fd890e5b65a24ef1b62d691...,### Python,NaN,...,1.000000,"def canSplit(arr, n, k):\n odd = 0\n for...",NaN,finetuned,ok,NaN,NaN,NaN,NaN,NaN
7,T1,xlcost_c1e17f9a3ac4e7fd,Natural Language,Python,False,"def sumOfDivisions(arr, n):\n freq = [0] * ...",prompt_contract_v2.6,75b1c67b14207b07f2eb76f8f12aa7f910fb59a086a016...,### Python,NaN,...,0.909091,"def sumOfDivisions(arr, n):\n freq = [0] * ...",NaN,finetuned,ok,NaN,NaN,NaN,NaN,NaN
8,T1,xlcost_3247abc5f496b107,Natural Language,Python,False,"def minInsertions(arr, n):\n Xor = 0\n s...",prompt_contract_v2.6,a41097b5228436d1f14204fe43be62ff0193d15c6949b0...,### Python,NaN,...,1.000000,"def minInsertions(arr, n):\n Xor = 0\n s...",NaN,finetuned,ok,NaN,NaN,NaN,NaN,NaN
9,T1,xlcost_ffa450b09b8b2d9a,Natural Language,Python,False,"def checkReciprocal(a, b, c):\n if((a * a) ...",prompt_contract_v2.6,f662116e2db0aa9eddf363a3df9784a8d3f51a2c9cf20f...,### Python,NaN,...,0.714286,"def checkReciprocal(a, b, c):\n if((a * a) ...",NaN,finetuned,ok,NaN,NaN,NaN,NaN,NaN
10,T2,xlcost_6347b5fff72f6575,Natural Language,Java,False,import java.util.*; class GFG {static int minS...,prompt_contract_v2.6,654c3090a225e99c3c87b45f6682090b227af2f30ab62c...,### Java,NaN,...,1.000000,import java.util.*; class GFG {static int minS...,NaN,finetuned,ok,True,,NaN,NaN,NaN
11,T2,xlcost_9a7dde477f883166,Natural Language,Java,False,import java.util.*; class GFG {static void max...,prompt_contract_v2.6,36610d838018973e3804cbc073d6b38982335cd13b479e...,### Java,NaN,...,0.875000,import java.util.*; class GFG {static void max...,NaN,finetuned,ok,True,,NaN,NaN,NaN
12,T2,xlcost_fc06c07fb09820e8,Natural Language,Java,False,class GFG {static int findSize(int N) {if(N ==...,prompt_contract_v2.6,2b982ee7401ef8f2b02cde25cb03898038e80c96db3b12...,### Java,NaN,...,0.833333,class GFG {static int findSize(int N) {if(N ==...,NaN,finetuned,ok,True,,NaN,NaN,NaN
13,T2,xlcost_1a4bdacec5a19fef,Natural Language,Java,False,import java.util.*; class GFG {static boolean ...,prompt_contract_v2.6,c283d527eabad761c4ecca86285e0d7345b00a26bd070a...,### Java,NaN,...,0.857143,import java.util.*; class GFG {static boolean ...,NaN,finetuned,java_compile_error,False,/tmp/tmp00mw8cr2/GFG.java:1: error: illegal st...,NaN,NaN,NaN
14,T2,xlcost_8fc31d09b3c0a1ac,Natural Language,Java,False,import java.util.*; class GFG {static int land...,prompt_contract_v2.6,cecc217fd1e2d894e071efd71b3e0fd03de31ceb707eb3...,### Java,NaN,...,0.666667,import java.util.*; class GFG {static int land...,NaN,finetuned,java_compile_error,False,/tmp/tmp3wdx7jlx/GFG.java:1: error: duplicate ...,NaN,NaN,NaN
15,T2,xlcost_869c824b5762d30d,Natural Language,Java,False,import java.util.*; class GFG {static boolean ...,prompt_contract_v2.6,10d84a583c27364750061d5e34ff55f8224a7b9cfc727e...,### Java,NaN,...,0.875000,import java.util.*; class GFG {static boolean ...,NaN,finetuned,ok,True,,NaN,NaN,NaN
16,T2,xlcost_61a7ef8a73562d47,Natural Language,Java,False,"class GFG {static boolean canSplit(int arr[], ...",prompt_contract_v2.6,3e07aa2353476d6ce4f3a3fa38723b9aad32a41c749835...,### Java,NaN,...,0.875000,"class GFG {static boolean canSplit(int arr[], ...",NaN,finetuned,ok,True,,NaN,NaN,NaN
17,T2,xlcost_c1e17f9a3ac4e7fd,Natural Language,Java,False,import java.util.*; class GFG {static int sumO...,prompt_contract_v2.6,f0f71a81df6149c8f398c3fee18ba0414f7fb45dbdabdb...,### Java,NaN,...,1.000000,import java.util.*; class GFG {static int sumO...,NaN,finetuned,ok,True,,NaN,NaN,NaN
18,T2,xlcost_3247abc5f496b107,Natural Language,Java,False,"class GFG {static void minInsert(int arr[], in...",prompt_contract_v2.6,9a02e0539485fef57bcbc295a180d0d6e444aba1c80711...,### Java,NaN,...,0.875000,"class GFG {static void minInsert(int arr[], in...",NaN,finetuned,ok,True,,NaN,NaN,NaN
19,T2,xlcost_ffa450b09b8b2d9a,Natural Language,Java,False,class GFG {static boolean checkReciprocal(int ...,prompt_contract_v2.6,af3f9bcbff19c53ea0c5817085dc9358340c875afa5ccf...,### Java,NaN,...,0.800000,class GFG {static boolean checkReciprocal(int ...,NaN,finetuned,ok,True,,NaN,NaN,NaN
20,T3,xlcost_6347b5fff72f6575,Python,Java,False,import java.util.*; class GFG {static int minS...,prompt_contract_v2.6,2a99c1589f0859a353ef0ad18aed72f8e8a85a42c618ae...,### Java Translation,NaN,...,1.000000,import java.util.*; class GFG {static int minS...,NaN,finetuned,java_compile_error,False,/tmp/tmpipy4h6n7/GFG.java:1: error: illegal st...,NaN,NaN,NaN
21,T3,xlcost_9a7dde477f883166,Python,Java,False,"class GFG {static void maxAdjacent(int arr[], ...",prompt_contract_v2.6,41d97e6373d06219c9a2d5f0c04f235cf909e8f8927b42...,### Java Translation,NaN,...,0.875000,"class GFG {static void maxAdjacent(int arr[], ...",NaN,finetuned,java_compile_error,False,/tmp/tmpi__bl49t/GFG.java:1: error: method max...,NaN,NaN,NaN
22,T3,xlcost_fc06c07fb09820e8,Python,Java,False,class GFG {static int findSize(int N) {if(N ==...,prompt_contract_v2.6,f30f756ba4544dacdbc3e6c7589ce03b68c0d6360a12d3...,### Java Translation,NaN,...,1.000000,class GFG {static int findSize(int N) {if(N ==...,NaN,finetuned,ok,True,,NaN,NaN,NaN
23,T3,xlcost_1a4bdacec5a19fef,Python,Java,False,import java.util.*; class GFG {static boolean ...,prompt_contract_v2.6,90579ccbc7cf5cefea0a58280c66a08362e0b44b8261fa...,### Java Translation,NaN,...,1.000000,import java.util.*; class GFG {static boolean ...,NaN,finetuned,ok,True,,NaN,NaN,NaN
24,T3,xlcost_8fc31d09b3c0a1ac,Python,Java,False,class GFG {static int Landau = Integer.MIN_VAL...,prompt_contract_v2.6,2f4b93cab83844883a9d1ab810a99ab14f7727ed8a2214...,### Java Translation,NaN,...,0.777778,class GFG {static int Landau = Integer.MIN_VAL...,NaN,finetuned,java_compile_error,False,"length; i ++) nth_lcm = lcm(nth_lcm, arr [i]);...",NaN,NaN,NaN
25,T3,xlcost_869c824b5762d30d,Python,Java,False,import java.util.*; class GFG {static boolean ...,prompt_contract_v2.6,a02803fe4595589de84921fe0f381e17c794e00cbaf630...,### Java Translation,NaN,...,1.000000,import java.util.*; class GFG {static boolean ...,NaN,finetuned,ok,True,,NaN,NaN,NaN
26,T3,xlcost_61a7ef8a73562d47,Python,Java,False,"class GFG {static boolean checkArray(int n, in...",prompt_contract_v2.6,71bcc0f2f8922f6810073f73323c83d0a2544f4730348f...,### Java Translation,NaN,...,0.875000,"class GFG {static boolean checkArray(int n, in...",NaN,finetuned,ok,True,,NaN,NaN,NaN
27,T3,xlcost_c1e17f9a3ac4e7fd,Python,Java,False,import java.util.*; class GFG {static int func...,prompt_contract_v2.6,e8988400259a578ce850931233a8ab7096e5cdaf680518...,### Java Translation,NaN,...,0.888889,import java.util.*; class GFG {static int func...,NaN,finetuned,java_compile_error,False,...,NaN,NaN,NaN
28,T3,xlcost_3247abc5f496b107,Python,Java,False,"class GFG {static void insert_element(int a[],...",prompt_contract_v2.6,16a83c83fbd1ec8559c8eb4330d34c4e1915277ebec154...,### Java Translation,NaN,...,0.875000,"class GFG {static void insert_element(int a[],...",NaN,finetuned,java_compile_error,False,/tmp/tmp_z09ghru/GFG.java:1: error: illegal st...,NaN,NaN,NaN
29,T3,xlcost_ffa450b09b8b2d9a,Python,Java,False,"class GFG {static void checkSolution(int a, in...",prompt_contract_v2.6,18ed936bf002b6b2790220d675e2b351da0d54a0908d1c...,### Java Translation,NaN,...,1.000000,"class GFG {static void checkSolution(int a, in...",NaN,finetuned,ok,True,,NaN,NaN,NaN
30,T4,xlcost_6347b5fff72f6575,Java,Python,False,"def minSum(A, N):\n mp = {}\n sum = 0\n ...",prompt_contract_v2.6,00165a5214eef9dfbdcb5c40f52c0e491dafa26b1d33a3...,### Python Translation,NaN,...,1.000000,"def minSum(A, N):\n mp = {}\n sum = 0\n ...",NaN,finetuned,ok,NaN,NaN,NaN,NaN,NaN
31,T4,xlcost_9a7dde477f883166,Java,Python,False,"def maxAdjacent(arr, N):\n res = []\n fo...",prompt_contract_v2.6,e6153a0bdffbbdb87d17385496fd6abd70aa71505d3e33...,### Python Translation,NaN,...,1.000000,"def maxAdjacent(arr, N):\n res = []\n fo...",NaN,finetuned,ok,NaN,NaN,NaN,NaN,NaN
32,T4,xlcost_fc06c07fb09820e8,Java,Python,False,def findSize(N):\n if(N == 0):\n ret...,prompt_contract_v2.6,591145a6b725b69e925f540ef35c1e9708b52f385bdd66...,### Python Translation,NaN,...,1.000000,def findSize(N):\n if(N == 0):\n ret...,NaN,finetuned,ok,NaN,NaN,NaN,NaN,NaN
33,T4,xlcost_1a4bdacec5a19fef,Java,Python,False,def isPrime(n):\n if(n <= 1):\n retu...,prompt_contract_v2.6,4f6f941f351ed141e86a74689532756f3a94483c904bb1...,### Python Translation,NaN,...,0.800000,def isPrime(n):\n if(n <= 1):\n retu...,NaN,finetuned,ok,NaN,NaN,NaN,NaN,NaN
34,T4,xlcost_8fc31d09b3c0a1ac,Java,Python,False,"def Landau = float('inf');\ndef gcd(a, b):\n ...",prompt_contract_v2.6,62eee5cbafa91912d222b2f23cbe3f7792f42c20a5249f...,### Python Translation,NaN,...,0.000000,"def Landau = float('inf');\ndef gcd(a, b):\n ...","SyntaxError(""expected '('"", ('<unknown>', 1, 1...",finetuned,python_syntax_error,NaN,NaN,NaN,NaN,NaN
35,T4,xlcost_869c824b5762d30d,Java,Python,False,def isPrime(n):\n if(n == 1):\n retu...,prompt_contract_v2.6,ffcad1a775097a5e235c82def37b8fd29ab79917e15bcc...,### Python Translation,NaN,...,1.000000,def isPrime(n):\n if(n == 1):\n retu...,NaN,finetuned,ok,NaN,NaN,NaN,NaN,NaN
36,T4,xlcost_61a7ef8a73562d47,Java,Python,False,"def checkArray(n, k, arr):\n cnt = 0;\n ...",prompt_contract_v2.6,1162dbad0f26b4dcae8e593d979fe9a49f822b03933e73...,### Python Translation,NaN,...,1.000000,"def checkArray(n, k, arr):\n cnt = 0;\n ...",NaN,finetuned,ok,NaN,NaN,NaN,NaN,NaN
37,T4,xlcost_c1e17f9a3ac4e7fd,Java,Python,False,"def func(arr, n):\n maxx = 0;\n freq = [...",prompt_contract_v2.6,44f8495208464a9312f65f5f62ef4074d124e9f7b0f8d6...,### Python Translation,NaN,...,0.909091,"def func(arr, n):\n maxx = 0;\n freq = [...",NaN,finetuned,ok,NaN,NaN,NaN,NaN,NaN
38,T4,xlcost_3247abc5f496b107,Java,Python,False,"def insert_element(a, n):\n Xor = 0\n Su...",prompt_contract_v2.6,24c0c8eed72b7a6e46856ba5002bb5ba1764dd2cbc1fbf...,### Python Translation,NaN,...,1.000000,"def insert_element(a, n):\n Xor = 0\n Su...",NaN,finetuned,ok,NaN,NaN,NaN,NaN,NaN
39,T4,xlcost_ffa450b09b8b2d9a,Java,Python,False,"def checkSolution(a, b, c):\n if(a == c):\n...",prompt_contract_v2.6,7d0f3765ff357f32ab485501eee641968a248065f13488...,### Python Translation,NaN,...,1.000000,"def checkSolution(a, b, c):\n if(a == c):\n...",NaN,finetuned,ok,NaN,NaN,NaN,NaN,NaN
40,T5,xlcost_6347b5fff72f6575,Python,Natural Language,False,Minimum sum of array elements after removing a...,prompt_contract_v2.6,892eca7fff5063866d4a717dccfc8fd009d05ea8425981...,### Explanation,NaN,...,NaN,Minimum sum of array elements after removing a...,NaN,finetuned,ok,NaN,NaN,19.670038,0.537037,0.902928
41,T5,xlcost_9a7dde477f883166,Python,Natural Language,False,Maximum absolute difference between adjacent e...,prompt_contract_v2.6,d0b2e895ac4c483c404c650a8455cd9d793a75f516dfe0...,### Explanation,NaN,...,NaN,Maximum absolute difference between adjacent e...,NaN,finetuned,ok,NaN,NaN,3.361294,0.163488,0.820237
42,T5,xlcost_fc06c07fb09820e8,Python,Natural Language,False,"Count of numbers in range [ L , R ] which are ...",prompt_contract_v2.6,dec392c55d9338b2baf700f66a65cc4f9c5ebcedf73641...,### Explanation,NaN,...,NaN,"Count of numbers in range [ L , R ] which are ...",NaN,finetuned,ok,NaN,NaN,8.444461,0.230769,0.635561
43,T5,xlcost_1a4bdacec5a19fef,Python,Natural Language,False,Minimum Divisor of N | Function to check if a ...,prompt_contract_v2.6,5916c9f4f39987376dddc7b741dbece39c5bf5f463d055...,### Explanation,NaN,...,NaN,Minimum Divisor of N | Function to check if a ...,NaN,finetuned,ok,NaN,NaN,11.971985,0.426230,0.712533
44,T5,xlcost_8fc31d09b3c0a1ac,Python,Natural Language,False,Find the LCM of the first N numbers | Function...,prompt_contract_v2.6,20de146b27180146e6d7070053fb29eeeb977792a2a054...,### Explanation,NaN,...,NaN,Find the LCM of the first N numbers | Function...,NaN,finetuned,ok,NaN,NaN,5.151726,0.209567,0.592158
45,T5,xlcost_869c824b5762d30d,Python,Natural Language,False,Check if a number is prime or not | Function t...,prompt_contract_v2.6,1fac6ab109920b4ecb0628fb3cf0c5755241b0324c687a...,### Explanation,NaN,...,NaN,Check if a number is prime or not | Function t...,NaN,finetuned,ok,NaN,NaN,12.721496,0.335878,0.810374
46,T5,xlcost_61a7ef8a73562d47,Python,Natural Language,False,Check if an array can be made equal by removin...,prompt_contract_v2.6,8b2aa9dad7341912fb877e848fbf8c43a1c0c876a66936...,### Explanation,NaN,...,NaN,Check if an array can be made equal by removin...,NaN,finetuned,ok,NaN,NaN,16.350463,0.456522,0.808933
47,T5,xlcost_c1e17f9a3ac4e7fd,Python,Natural Language,False,Minimum number of operations required to make ...,prompt_contract_v2.6,4dd8e9b707613de7f5b6bcb44bd5ed501e46293e5ee460...,### Explanation,NaN,...,NaN,Minimum number of operations required to make ...,NaN,finetuned,ok,NaN,NaN,4.192166,0.250000,0.488403
48,T5,xlcost_3247abc5f496b107,Python,Natural Language,False,Insert Element in Array such that sum of array...,prompt_contract_v2.6,42e69c554a35a4cb9597d8ed267bb136be2bac43b86faa...,### Explanation,NaN,...,NaN,Insert Element in Array such that sum of array...,NaN,finetuned,ok,NaN,NaN,3.583694,0.180139,0.767598
49,T5,xlcost_ffa450b09b8b2d9a,Python,Natural Language,False,Check if a number is a perfect square | Functi...,prompt_contract_v2.6,bcff63ba5677ef8528e995165c9aba4dd5863cbcb06266...,### Explanation,NaN,...,NaN,Check if a number is a perfect square | Functi...,NaN,finetuned,ok,NaN,NaN,12.738860,0.363636,0.451750
50,T6,xlcost_6347b5fff72f6575,Java,Natural Language,False,Minimum sum of array elements after removing s...,prompt_contract_v2.6,937b8ca34a7cbb6a67c44424e8a410cc58bc8ffa8f35e8...,### Explanation,NaN,...,NaN,Minimum sum of array elements after removing s...,NaN,finetuned,ok,NaN,NaN,4.211179,0.162850,0.796316
51,T6,xlcost_9a7dde477f883166,Java,Natural Language,False,Maximum difference between consecutive element...,prompt_contract_v2.6,510ba5c6ca7ce4977b0192d31106bab8d0a21f2ee95ee3...,### Explanation,NaN,...,NaN,Maximum difference between consecutive element...,NaN,finetuned,ok,NaN,NaN,19.499053,0.406250,0.782366
52,T6,xlcost_fc06c07fb09820e8,Java,Natural Language,False,"Count of numbers in range [ L , R ] which are ...",prompt_contract_v2.6,2971c1d19da5ce6aa896ed74775754f3e8f1dafd664c20...,### Explanation,NaN,...,NaN,"Count of numbers in range [ L , R ] which are ...",NaN,finetuned,ok,NaN,NaN,1.798684,0.230769,0.631360
53,T6,xlcost_1a4bdacec5a19fef,Java,Natural Language,False,Minimum number of divisors of a given number |...,prompt_contract_v2.6,d126c284f3544d0085ad39847563cd3ecee5e42706c28b...,### Explanation,NaN,...,NaN,Minimum number of divisors of a given number |...,NaN,finetuned,ok,NaN,NaN,13.310227,0.360976,0.586966
54,T6,xlcost_8fc31d09b3c0a1ac,Java,Natural Language,False,Find the LCM of the first N natural numbers | ...,prompt_contract_v2.6,343345ba125b17c51b4404093ac327327de044ae6d26c7...,### Explanation,NaN,...,NaN,Find the LCM of the first N natural numbers | ...,NaN,finetuned,ok,NaN,NaN,9.008926,0.324074,0.617879
55,T6,xlcost_869c824b5762d30d,Java,Natural Language,False,Check if a number is prime or not | Function t...,prompt_contract_v2.6,6b9e6d95365c07993306e3c3dc70b301ff98603f8adb19...,### Explanation,NaN,...,NaN,Check if a number is prime or not | Function t...,NaN,finetuned,ok,NaN,NaN,13.016088,0.314815,0.802444
56,T6,xlcost_61a7ef8a73562d47,Java,Natural Language,False,Check if an array can be made equal by removin...,prompt_contract_v2.6,309156335c1cdd0ffed174bd93991fb9510d3f80a267b2...,### Explanation,NaN,...,NaN,Check if an array can be made equal by removin...,NaN,finetuned,ok,NaN,NaN,13.313771,0.442105,0.805346
57,T6,xlcost_c1e17f9a3ac4e7fd,Java,Natural Language,False,Minimum number of operations required to make ...,prompt_contract_v2.6,95150ff283a5ff9b783caea79ff237ce9007375a7f605a...,### Explanation,NaN,...,NaN,Minimum number of operations required to make ...,NaN,finetuned,ok,NaN,NaN,4.179285,0.271605,0.480718
58,T6,xlcost_3247abc5f496b107,Java,Natural Language,False,Find the number which can be formed by adding ...,prompt_contract_v2.6,177a917d9c4abc9c8b2898a87cd9031c2d21e2d0a5bbc6...,### Explanation,NaN,...,NaN,Find the number which can be formed by adding ...,NaN,finetuned,ok,NaN,NaN,6.714601,0.295455,0.751519
59,T6,xlcost_ffa450b09b8b2d9a,Java,Natural Language,False,Check if a number can be represented as the su...,prompt_contract_v2.6,5a6b914ec9baddd681fdc434a8ba39efe6e0fb4fe8c0da...,### Explanation,NaN,...,NaN,Check if a number can be represented as the su...,NaN,finetuned,ok,NaN,NaN,10.895870,0.361111,0.437658

17:20:41 | INFO     | RepoCoderStudio.Main | Saved CSV: /content/drive/MyDrive/RepoCoderStudio/outputs/evaluation/baseline_failure_analytics.csv (60 rows)
17:20:41 | INFO     | RepoCoderStudio.Main | Saved CSV: /content/drive/MyDrive/RepoCoderStudio/outputs/evaluation/finetuned_failure_analytics.csv (60 rows)

====================================================================
Failure Analytics Summary
====================================================================
Baseline Rows               : 60
Fine-tuned Rows             : 60
Baseline CSV                : outputs/evaluation/baseline_failure_analytics.csv
Fine-tuned CSV              : outputs/evaluation/finetuned_failure_analytics.csv
====================================================================

In [25]:
# ============================================================
# 22A. Report-Style Failure Analytics Summary Table
# ============================================================

import pandas as pd

from src.storage import ProjectStorageManager
from src.logger import SectionPrinter, SummaryPrinter

SectionPrinter.header("Report-Style Failure Analytics Summary Table")


def dominant_failure(df, task_id):
    subset = df[df["task_id"] == task_id].copy()
    failures = subset[subset["failure_category"] != "ok"]

    if len(failures) == 0:
        return "None observed"

    counts = failures["failure_category"].value_counts()

    return counts.index[0]


failure_summary_rows = []

for task_id in ["T1", "T2", "T3", "T4", "T5", "T6"]:

    baseline_main = dominant_failure(baseline_failure_df, task_id)
    finetuned_main = dominant_failure(finetuned_failure_df, task_id)

    if task_id == "T1":
        observation = (
            "Fine-tuning removed baseline empty-code and low-similarity failures, "
            "leading to fully parseable Python outputs."
        )

    elif task_id == "T2":
        observation = (
            "Java compile failures reduced substantially after fine-tuning; "
            "remaining errors are mostly syntax-level issues."
        )

    elif task_id == "T3":
        observation = (
            "Translation fidelity improved strongly, but some Java compilation "
            "failures remain, motivating lightweight Java repair."
        )

    elif task_id == "T4":
        observation = (
            "Java-to-Python translation remained stable with only isolated syntax failure."
        )

    elif task_id == "T5":
        observation = (
            "Explanation outputs became closer to reference task descriptions."
        )

    else:
        observation = (
            "Java explanation quality improved, with no major failure mode observed."
        )

    failure_summary_rows.append({
        "Task": task_id,
        "Baseline Main Failure": baseline_main,
        "Fine-Tuned Main Failure": finetuned_main,
        "Observation": observation,
    })


failure_summary_table = pd.DataFrame(failure_summary_rows)

display(failure_summary_table)

storage = ProjectStorageManager(CONFIG)

storage.save_csv(
    failure_summary_table,
    "outputs/evaluation/report_failure_summary_table.csv",
)

markdown_path = (
    CONFIG.storage.project_root()
    / CONFIG.storage.outputs_dir
    / "evaluation"
    / "report_failure_summary_table.md"
)

markdown_path.parent.mkdir(parents=True, exist_ok=True)

with open(markdown_path, "w", encoding="utf-8") as f:
    f.write("### Table: Failure Analytics Summary\n\n")
    f.write(failure_summary_table.to_markdown(index=False))

SummaryPrinter.print_summary(
    "Report-Style Failure Analytics Summary Table",
    {
        "Rows": len(failure_summary_table),
        "CSV": "outputs/evaluation/report_failure_summary_table.csv",
        "Markdown": "outputs/evaluation/report_failure_summary_table.md",
    },
)

====================================================================
Report-Style Failure Analytics Summary Table
====================================================================

,Task,Baseline Main Failure,Fine-Tuned Main Failure,Observation
0,T1,low_similarity,None observed,Fine-tuning removed baseline empty-code and lo...
1,T2,None observed,java_compile_error,Java compile failures reduced substantially af...
2,T3,low_similarity,java_compile_error,"Translation fidelity improved strongly, but so..."
3,T4,None observed,python_syntax_error,Java-to-Python translation remained stable wit...
4,T5,None observed,None observed,Explanation outputs became closer to reference...
5,T6,None observed,None observed,"Java explanation quality improved, with no maj..."

17:37:10 | INFO     | RepoCoderStudio.Main | Saved CSV: /content/drive/MyDrive/RepoCoderStudio/outputs/evaluation/report_failure_summary_table.csv (6 rows)

====================================================================
Report-Style Failure Analytics Summary Table
====================================================================
Rows                        : 6
CSV                         : outputs/evaluation/report_failure_summary_table.csv
Markdown                    : outputs/evaluation/report_failure_summary_table.md
====================================================================

In [20]:
# ============================================================
# 23. Trusted Test Repository Summary
# ============================================================

import pandas as pd

from src.storage import ProjectStorageManager
from src.logger import SectionPrinter, SummaryPrinter

SectionPrinter.header("Trusted Test Repository Summary")

storage = ProjectStorageManager(CONFIG)

approved_rows_dict = [
    row if isinstance(row, dict) else row.__dict__
    for row in approved_rows
]

test_rows = []

for row in approved_rows_dict:
    trusted = row.get("trusted_tests", {}) or {}

    test_rows.append(
        {
            "corpus_id": row.get("corpus_id"),
            "trusted_test_status": trusted.get("status", "unknown"),
            "num_trusted_tests": len(trusted.get("tests", []) or []),
            "num_candidate_tests": len(trusted.get("candidate_tests", []) or []),
            "execution_status": (row.get("metadata", {}) or {}).get("execution_status", "unknown"),
        }
    )

trusted_test_df = pd.DataFrame(test_rows)

display(trusted_test_df.head())

if not trusted_test_df.empty:
    print("\nTrusted test status counts:")
    display(trusted_test_df["trusted_test_status"].value_counts().reset_index())

    print("\nExecution status counts:")
    display(trusted_test_df["execution_status"].value_counts().reset_index())

storage.save_csv(
    trusted_test_df,
    "outputs/trusted_tests/trusted_test_repository_summary.csv",
)

SummaryPrinter.print_summary(
    "Trusted Test Repository Summary",
    {
        "Approved Rows": len(trusted_test_df),
        "Rows With Trusted Tests": int((trusted_test_df["num_trusted_tests"] > 0).sum()) if not trusted_test_df.empty else 0,
        "Rows With Candidate Tests": int((trusted_test_df["num_candidate_tests"] > 0).sum()) if not trusted_test_df.empty else 0,
        "Saved CSV": "outputs/trusted_tests/trusted_test_repository_summary.csv",
    },
)

====================================================================
Trusted Test Repository Summary
====================================================================

,corpus_id,trusted_test_status,num_trusted_tests,num_candidate_tests,execution_status
0,xlcost_6347b5fff72f6575,insufficient,0,0,NOT_FEASIBLE
1,xlcost_9a7dde477f883166,insufficient,0,0,NOT_FEASIBLE
2,xlcost_fc06c07fb09820e8,insufficient,0,0,NOT_FEASIBLE
3,xlcost_1a4bdacec5a19fef,insufficient,0,0,NOT_FEASIBLE
4,xlcost_8fc31d09b3c0a1ac,insufficient,0,0,NOT_FEASIBLE

Trusted test status counts:

  trusted_test_status  count
0        insufficient    403

Execution status counts:

  execution_status  count
0     NOT_FEASIBLE    403

17:21:07 | INFO     | RepoCoderStudio.Main | Saved CSV: /content/drive/MyDrive/RepoCoderStudio/outputs/trusted_tests/trusted_test_repository_summary.csv (403 rows)

====================================================================
Trusted Test Repository Summary
====================================================================
Approved Rows               : 403
Rows With Trusted Tests     : 0
Rows With Candidate Tests   : 0
Saved CSV                   : outputs/trusted_tests/trusted_test_repository_summary.csv
====================================================================

In [21]:
# ============================================================
# 24. Final Artifact Summary
# ============================================================

from pathlib import Path

from src.storage import ProjectStorageManager
from src.logger import SectionPrinter

SectionPrinter.header("Final Artifact Summary")

storage = ProjectStorageManager(CONFIG)
root = Path(CONFIG.storage.drive_project_root)

artifact_checks = {
    "Candidate Corpus": "outputs/candidate_corpus/candidate_corpus.jsonl",
    "Approved Corpus": "outputs/approved_corpus/approved_corpus.jsonl",
    "Rejected Corpus": "outputs/rejected_corpus/rejected_corpus.jsonl",
    "Task Dataset": "outputs/task_datasets/task_dataset.jsonl",
    "Training History": "outputs/reports/training_history.csv",
    "Training Summary": "outputs/reports/training_summary.json",
    "Baseline Predictions": "outputs/evaluation/baseline_prediction_logs.jsonl",
    "Fine-tuned Predictions": "outputs/evaluation/finetuned_prediction_logs.jsonl",
    "Comparison": "outputs/evaluation/baseline_vs_finetuned_comparison.csv",
    "Baseline Failure Analysis": "outputs/evaluation/baseline_failure_analysis.csv",
    "Fine-tuned Failure Analysis": "outputs/evaluation/finetuned_failure_analysis.csv",
    "Trusted Test Summary": "outputs/trusted_tests/trusted_test_repository_summary.csv",
    "Final Adapter": f"outputs/adapters/{CONFIG.training.final_adapter_name}",
}

for label, rel_path in artifact_checks.items():
    path = root / rel_path
    status = "FOUND" if path.exists() else "MISSING"
    print(f"{label:<32}: {status:<8} {path}")

print("=" * 70)

====================================================================
Final Artifact Summary
====================================================================
Candidate Corpus                : FOUND    /content/drive/MyDrive/RepoCoderStudio/outputs/candidate_corpus/candidate_corpus.jsonl
Approved Corpus                 : FOUND    /content/drive/MyDrive/RepoCoderStudio/outputs/approved_corpus/approved_corpus.jsonl
Rejected Corpus                 : FOUND    /content/drive/MyDrive/RepoCoderStudio/outputs/rejected_corpus/rejected_corpus.jsonl
Task Dataset                    : FOUND    /content/drive/MyDrive/RepoCoderStudio/outputs/task_datasets/task_dataset.jsonl
Training History                : FOUND    /content/drive/MyDrive/RepoCoderStudio/outputs/reports/training_history.csv
Training Summary                : FOUND    /content/drive/MyDrive/RepoCoderStudio/outputs/reports/training_summary.json
Baseline Predictions            : FOUND    /content/drive/MyDrive/RepoCoderStudio/outputs/evaluation/baseline_prediction_logs.jsonl
Fine-tuned Predictions          : FOUND    /content/drive/MyDrive/RepoCoderStudio/outputs/evaluation/finetuned_prediction_logs.jsonl
Comparison                      : FOUND    /content/drive/MyDrive/RepoCoderStudio/outputs/evaluation/baseline_vs_finetuned_comparison.csv
Baseline Failure Analysis       : MISSING  /content/drive/MyDrive/RepoCoderStudio/outputs/evaluation/baseline_failure_analysis.csv
Fine-tuned Failure Analysis     : MISSING  /content/drive/MyDrive/RepoCoderStudio/outputs/evaluation/finetuned_failure_analysis.csv
Trusted Test Summary            : FOUND    /content/drive/MyDrive/RepoCoderStudio/outputs/trusted_tests/trusted_test_repository_summary.csv
Final Adapter                   : FOUND    /content/drive/MyDrive/RepoCoderStudio/outputs/adapters/RepoCoderStudio_CombinedStage_LoRA_v1_0
======================================================================

In [ ]:
# ============================================================
# 25. Interactive Gradio Demo -- Baseline vs Fine-tuned, Task Chaining
# ============================================================

import sys
import importlib

for module_name in list(sys.modules.keys()):
    if module_name == "src" or module_name.startswith("src."):
        del sys.modules[module_name]

importlib.invalidate_caches()

!pip -q install gradio

import gradio as gr

from src.config import CONFIG
from src.registry import TaskRegistry
from src.generation_engine import GenerationEngine
from src.logger import SectionPrinter, LOG

SectionPrinter.header("Interactive Demo: Baseline vs Fine-tuned")

task_registry = TaskRegistry()
demo_gen_engine = GenerationEngine(CONFIG)

LOG.info("Loading baseline model for interactive demo...")
demo_baseline_model, demo_baseline_tokenizer = demo_gen_engine.load_model("baseline")

LOG.info("Loading fine-tuned model for interactive demo...")
demo_finetuned_model, demo_finetuned_tokenizer = demo_gen_engine.load_model("finetuned")

# Task dropdown labels, e.g. "T1: Natural Language -> Python -- Generate Python code from natural language."
_task_labels = [
    f"{task_id}: {info['source']} -> {info['target']} -- {info['description']}"
    for task_id, info in task_registry.all_tasks().items()
]
_task_id_by_label = dict(zip(_task_labels, task_registry.all_tasks().keys()))


def run_task(task_label: str, input_text: str):
    """Runs one task through both the baseline and fine-tuned model and
    returns both outputs side by side."""
    task_id = _task_id_by_label[task_label]
    instruction = demo_gen_engine.prompt_builder.build_instruction(task_id)

    baseline_output = demo_gen_engine.generate(
        demo_baseline_model, demo_baseline_tokenizer, instruction, input_text or "", task_id=task_id
    )
    finetuned_output = demo_gen_engine.generate(
        demo_finetuned_model, demo_finetuned_tokenizer, instruction, input_text or "", task_id=task_id
    )
    return baseline_output, finetuned_output


def _carry_forward(text: str) -> str:
    """Copies a chosen output into the input box so it can feed the next task."""
    return text or ""


with gr.Blocks(title="RepoCoder Studio -- Baseline vs Fine-tuned") as combined_stage_demo:
    gr.Markdown(
        """## RepoCoder Studio -- Baseline vs Fine-tuned
Pick a task, provide input, and compare the pretrained baseline against the
fine-tuned LoRA model. Use the 'Use this output -> next input' button under
either result to carry it forward as the input for the next task (e.g. T1
NL->Python, then feed that Python output into T3 Python->Java)."""
    )

    task_dropdown = gr.Dropdown(choices=_task_labels, value=_task_labels[0], label="Task")
    input_box = gr.Textbox(lines=8, label="Input")
    run_button = gr.Button("Run", variant="primary")

    with gr.Row():
        with gr.Column():
            baseline_output_box = gr.Textbox(lines=14, label="Baseline (pretrained) output")
            use_baseline_button = gr.Button("Use this output -> next input")
        with gr.Column():
            finetuned_output_box = gr.Textbox(lines=14, label="Fine-tuned output")
            use_finetuned_button = gr.Button("Use this output -> next input")

    run_button.click(
        run_task,
        inputs=[task_dropdown, input_box],
        outputs=[baseline_output_box, finetuned_output_box],
    )
    use_baseline_button.click(_carry_forward, inputs=baseline_output_box, outputs=input_box)
    use_finetuned_button.click(_carry_forward, inputs=finetuned_output_box, outputs=input_box)

combined_stage_demo.launch(share=True, debug=False)